#include "cthyst.h"
VALUE cls_Constant_Propagator;
VALUE AmethystCore_anything(VALUE self );
VALUE Amethyst_clas(VALUE self ,VALUE);
VALUE Amethyst_eof(VALUE self );
VALUE Constant_Propagator_root(VALUE self );
VALUE Constant_Propagator_step(VALUE self ,VALUE a0);
static VALUE c_474;
static VALUE c_476;
static VALUE c_477;
static VALUE c_478;
static VALUE c_480;
static VALUE c_482;
static VALUE s_root_Constant_Propagatorcb_1Constant_Propagator;
static VALUE s_sizeConstant_Propagator;
static VALUE s_step_Constant_Propagatorcb_10Constant_Propagator;
static VALUE s_step_Constant_Propagatorcb_1Constant_Propagator;
static VALUE s_step_Constant_Propagatorcb_2Constant_Propagator;
static VALUE s_step_Constant_Propagatorcb_3Constant_Propagator;
static VALUE s_step_Constant_Propagatorcb_4Constant_Propagator;
static VALUE s_step_Constant_Propagatorcb_5Constant_Propagator;
static VALUE s_step_Constant_Propagatorcb_6Constant_Propagator;
static VALUE s_step_Constant_Propagatorcb_7Constant_Propagator;
static VALUE s_step_Constant_Propagatorcb_8Constant_Propagator;
static VALUE s_step_Constant_Propagatorcb_9Constant_Propagator;
static VALUE s_valofConstant_Propagator;
VALUE Constant_Propagator_root(VALUE self ){VALUE vals[0]; VALUE bind=bind_new2(2);  int x;VALUE arg0,arg1,arg2,arg3;VALUE it;

  it=AmethystCore_anything(self ); FAILTEST(fail);
 bind_aset(bind,0/*it*/,it); it=rb_funcall(self,s_root_Constant_Propagatorcb_1Constant_Propagator,1,bind); 
 bind_aset(bind,1/*_result*/,it); it=bind_aget(bind,1/*_result*/);
return it;
fail: return failobj; }
VALUE Constant_Propagator_step(VALUE self ,VALUE a0){VALUE vals[1]; VALUE bind=bind_new2(26); bind_aset(bind,0/*el*/,a0); int x;VALUE arg0,arg1,arg2,arg3;VALUE it;

it=bind_aget(bind,0/*el*/);
 bind_aset(bind,1/*autovar*/,it); it=rb_funcall(self,s_step_Constant_Propagatorcb_1Constant_Propagator,1,bind); int oldpos1=ame_getpos(self); int oldlen1=ame_getlen(self); VALUE oldsrc1=ame_getsrc(self); int fail1=0;
ame_setsrc(self,bind_aget(bind,1/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeConstant_Propagator,0)));
 int oldpos2=ame_getpos(self);
alt1_1: ame_setpos(self,oldpos2);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto pass1;}
  it=c_474; arg0=it; it=Amethyst_clas(self ,arg0); FAILTEST(alt1_2);
 bind_aset(bind,2/*autovar*/,it); int oldpos3=ame_getpos(self); int oldlen2=ame_getlen(self); VALUE oldsrc2=ame_getsrc(self); int fail2=0;
ame_setsrc(self,bind_aget(bind,2/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeConstant_Propagator,0)));
 it=rb_ary_new3(0);
 bind_aset(bind,3/*autovar*/,it); int oldpos4; while(1){oldpos4=ame_getpos(self);   it=AmethystCore_anything(self ); FAILTEST(break1);
 bind_aset(bind,4/*autovar*/,it); it=rb_funcall(self,s_step_Constant_Propagatorcb_2Constant_Propagator,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos4=ame_getpos(self);goto break1;} } } break1: ame_setstop(self,Qnil);  ame_setpos(self,oldpos4); it=bind_aget(bind,3/*autovar*/);it=rb_funcall(self,s_step_Constant_Propagatorcb_3Constant_Propagator,1,bind); 
 bind_aset(bind,5/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass2);
	goto success2;
	pass2: fail2=1;
	success2: ame_setsrc(self,oldsrc2); ame_setpos(self,oldpos3); ame_setlen(self,oldlen2);
	if(fail2) goto alt1_2;
it=bind_aget(bind,5/*autovar*/);
 bind_aset(bind,6/*autovar*/,it);  
ame_setcut(self,Qnil);goto accept1;
alt1_2: ame_setpos(self,oldpos2);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto pass1;}
  it=c_476; arg0=it; it=Amethyst_clas(self ,arg0); FAILTEST(alt1_3);
 bind_aset(bind,7/*autovar*/,it); int oldpos5=ame_getpos(self); int oldlen3=ame_getlen(self); VALUE oldsrc3=ame_getsrc(self); int fail3=0;
ame_setsrc(self,bind_aget(bind,7/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeConstant_Propagator,0)));
   it=AmethystCore_anything(self ); FAILTEST(pass3);
 bind_aset(bind,8/*expr*/,it);  it=bind_aget(bind,8/*expr*/); arg0=it; it=rb_funcall(self,s_valofConstant_Propagator,1,arg0); FAILTEST(pass3);
 bind_aset(bind,9/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass3);
	goto success3;
	pass3: fail3=1;
	success3: ame_setsrc(self,oldsrc3); ame_setpos(self,oldpos5); ame_setlen(self,oldlen3);
	if(fail3) goto alt1_3;
it=bind_aget(bind,9/*autovar*/);
 bind_aset(bind,6/*autovar*/,it);  
ame_setcut(self,Qnil);goto accept1;
alt1_3: ame_setpos(self,oldpos2);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto pass1;}
  it=c_477; arg0=it; it=Amethyst_clas(self ,arg0); FAILTEST(alt1_4);
 bind_aset(bind,10/*autovar*/,it); int oldpos6=ame_getpos(self); int oldlen4=ame_getlen(self); VALUE oldsrc4=ame_getsrc(self); int fail4=0;
ame_setsrc(self,bind_aget(bind,10/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeConstant_Propagator,0)));
 int oldpos7=ame_getpos(self);
alt2_1: ame_setpos(self,oldpos7);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto pass4;}
  it=c_478; arg0=it; it=Amethyst_clas(self ,arg0); FAILTEST(alt2_2);
 bind_aset(bind,11/*autovar*/,it); int oldpos8=ame_getpos(self); int oldlen5=ame_getlen(self); VALUE oldsrc5=ame_getsrc(self); int fail5=0;
ame_setsrc(self,bind_aget(bind,11/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeConstant_Propagator,0)));
 it=rb_ary_new3(0);
 bind_aset(bind,12/*autovar*/,it); int oldpos9; while(1){oldpos9=ame_getpos(self);   it=AmethystCore_anything(self ); FAILTEST(break2);
 bind_aset(bind,13/*autovar*/,it); it=rb_funcall(self,s_step_Constant_Propagatorcb_4Constant_Propagator,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos9=ame_getpos(self);goto break2;} } } break2: ame_setstop(self,Qnil);  ame_setpos(self,oldpos9); it=bind_aget(bind,12/*autovar*/); it=rb_funcall(self,s_step_Constant_Propagatorcb_5Constant_Propagator,1,bind);  arg0=it; it=rb_funcall(self,s_valofConstant_Propagator,1,arg0); FAILTEST(pass5);
 bind_aset(bind,14/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass5);
	goto success5;
	pass5: fail5=1;
	success5: ame_setsrc(self,oldsrc5); ame_setpos(self,oldpos8); ame_setlen(self,oldlen5);
	if(fail5) goto alt2_2;
it=bind_aget(bind,14/*autovar*/);
 bind_aset(bind,15/*autovar*/,it);  
ame_setcut(self,Qnil);goto accept2;
alt2_2: ame_setpos(self,oldpos7);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto pass4;}
  it=c_480; arg0=it; it=Amethyst_clas(self ,arg0); FAILTEST(alt2_3);
 bind_aset(bind,16/*autovar*/,it); int oldpos10=ame_getpos(self); int oldlen6=ame_getlen(self); VALUE oldsrc6=ame_getsrc(self); int fail6=0;
ame_setsrc(self,bind_aget(bind,16/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeConstant_Propagator,0)));
 it=rb_ary_new3(0);
 bind_aset(bind,17/*autovar*/,it); int oldpos11; while(1){oldpos11=ame_getpos(self);   it=AmethystCore_anything(self ); FAILTEST(break3);
 bind_aset(bind,18/*autovar*/,it); it=rb_funcall(self,s_step_Constant_Propagatorcb_6Constant_Propagator,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos11=ame_getpos(self);goto break3;} } } break3: ame_setstop(self,Qnil);  ame_setpos(self,oldpos11); it=bind_aget(bind,17/*autovar*/);it=rb_funcall(self,s_step_Constant_Propagatorcb_7Constant_Propagator,1,bind); 
 bind_aset(bind,19/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass6);
	goto success6;
	pass6: fail6=1;
	success6: ame_setsrc(self,oldsrc6); ame_setpos(self,oldpos10); ame_setlen(self,oldlen6);
	if(fail6) goto alt2_3;
it=bind_aget(bind,19/*autovar*/);
 bind_aset(bind,15/*autovar*/,it);  
ame_setcut(self,Qnil);goto accept2;
  alt2_3:  ame_setpos(self,oldpos7); goto pass4;
 accept2:;
  it=Amethyst_eof(self ); FAILTEST(pass4);
	goto success4;
	pass4: fail4=1;
	success4: ame_setsrc(self,oldsrc4); ame_setpos(self,oldpos6); ame_setlen(self,oldlen4);
	if(fail4) goto alt1_4;
it=bind_aget(bind,15/*autovar*/);
 bind_aset(bind,6/*autovar*/,it);  
ame_setcut(self,Qnil);goto accept1;
alt1_4: ame_setpos(self,oldpos2);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto pass1;}
  it=c_482; arg0=it; it=Amethyst_clas(self ,arg0); FAILTEST(alt1_5);
 bind_aset(bind,20/*autovar*/,it); int oldpos12=ame_getpos(self); int oldlen7=ame_getlen(self); VALUE oldsrc7=ame_getsrc(self); int fail7=0;
ame_setsrc(self,bind_aget(bind,20/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeConstant_Propagator,0)));
 it=rb_ary_new3(0);
 bind_aset(bind,21/*autovar*/,it); int oldpos13; while(1){oldpos13=ame_getpos(self);   it=AmethystCore_anything(self ); FAILTEST(break4);
 bind_aset(bind,22/*autovar*/,it); it=rb_funcall(self,s_step_Constant_Propagatorcb_8Constant_Propagator,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos13=ame_getpos(self);goto break4;} } } break4: ame_setstop(self,Qnil);  ame_setpos(self,oldpos13); it=bind_aget(bind,21/*autovar*/);it=rb_funcall(self,s_step_Constant_Propagatorcb_5Constant_Propagator,1,bind); 
 bind_aset(bind,23/*val*/,it); it=rb_funcall(self,s_step_Constant_Propagatorcb_9Constant_Propagator,1,bind); 
 bind_aset(bind,24/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass7);
	goto success7;
	pass7: fail7=1;
	success7: ame_setsrc(self,oldsrc7); ame_setpos(self,oldpos12); ame_setlen(self,oldlen7);
	if(fail7) goto alt1_5;
it=bind_aget(bind,24/*autovar*/);
 bind_aset(bind,6/*autovar*/,it);  
ame_setcut(self,Qnil);goto accept1;
alt1_5: ame_setpos(self,oldpos2);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto pass1;}
   it=AmethystCore_anything(self ); FAILTEST(alt1_6);it=rb_funcall(self,s_step_Constant_Propagatorcb_10Constant_Propagator,1,bind); 
 bind_aset(bind,6/*autovar*/,it);  
ame_setcut(self,Qnil);goto accept1;
  alt1_6:  ame_setpos(self,oldpos2); goto pass1;
 accept1:;
  it=Amethyst_eof(self ); FAILTEST(pass1);
	goto success1;
	pass1: fail1=1;
	success1: ame_setsrc(self,oldsrc1); ame_setpos(self,oldpos1); ame_setlen(self,oldlen1);
	if(fail1) goto fail;
it=bind_aget(bind,6/*autovar*/);
 bind_aset(bind,25/*_result*/,it); it=bind_aget(bind,25/*_result*/);
return it;
fail: return failobj; }VALUE cls_Constant_Traverser;
VALUE AmethystCore_anything(VALUE self );
VALUE Amethyst_clas(VALUE self ,VALUE);
VALUE Amethyst_eof(VALUE self );
VALUE Constant_Traverser_root(VALUE self );
VALUE Constant_Traverser_traverse(VALUE self );
VALUE Constant_Traverser_traverse_item(VALUE self );
VALUE Constant_Traverser_visit(VALUE self );
static VALUE c_484;
static VALUE c_485;
static VALUE c_487;
static VALUE c_489;
static VALUE c_491;
static VALUE c_494;
static VALUE s_root_Constant_Traversercb_1Constant_Traverser;
static VALUE s_root_Constant_Traversercb_2Constant_Traverser;
static VALUE s_sizeConstant_Traverser;
static VALUE s_traverse_Constant_Traversercb_1Constant_Traverser;
static VALUE s_traverse_Constant_Traversercb_2Constant_Traverser;
static VALUE s_traverse_Constant_Traversercb_3Constant_Traverser;
static VALUE s_traverse_Constant_Traversercb_4Constant_Traverser;
static VALUE s_traverse_Constant_Traversercb_5Constant_Traverser;
static VALUE s_traverse_Constant_Traversercb_6Constant_Traverser;
static VALUE s_traverse_Constant_Traversercb_7Constant_Traverser;
static VALUE s_traverse_Constant_Traversercb_8Constant_Traverser;
static VALUE s_traverse_item_Constant_Traversercb_1Constant_Traverser;
static VALUE s_traverse_item_Constant_Traversercb_2Constant_Traverser;
static VALUE s_traverse_item_Constant_Traversercb_3Constant_Traverser;
static VALUE s_visit_Constant_Traversercb_1Constant_Traverser;
static VALUE s_visit_Constant_Traversercb_2Constant_Traverser;
static VALUE s_visit_Constant_Traversercb_3Constant_Traverser;
static VALUE s_visit_Constant_Traversercb_4Constant_Traverser;
static VALUE s_visit_Constant_Traversercb_5Constant_Traverser;
static VALUE s_visit_Constant_Traversercb_6Constant_Traverser;
VALUE Constant_Traverser_root(VALUE self ){VALUE vals[0]; VALUE bind=bind_new2(1);  int x;VALUE arg0,arg1,arg2,arg3;VALUE it;

it=rb_funcall(self,s_root_Constant_Traversercb_1Constant_Traverser,1,bind); it=rb_funcall(self,s_root_Constant_Traversercb_2Constant_Traverser,1,bind);   it=Constant_Traverser_traverse(self ); FAILTEST(fail);
 bind_aset(bind,0/*_result*/,it); it=bind_aget(bind,0/*_result*/);
return it;
fail: return failobj; }
VALUE Constant_Traverser_traverse(VALUE self ){VALUE vals[0]; VALUE bind=bind_new2(15);  int x;VALUE arg0,arg1,arg2,arg3;VALUE it;

it=rb_ary_new3(0);
 bind_aset(bind,0/*autovar*/,it); int oldpos1; while(1){oldpos1=ame_getpos(self);   it=AmethystCore_anything(self ); FAILTEST(break1);
 bind_aset(bind,1/*autovar*/,it); it=rb_funcall(self,s_traverse_Constant_Traversercb_1Constant_Traverser,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos1=ame_getpos(self);goto break1;} } } break1: ame_setstop(self,Qnil);  ame_setpos(self,oldpos1); it=bind_aget(bind,0/*autovar*/);it=rb_funcall(self,s_traverse_Constant_Traversercb_2Constant_Traverser,1,bind); 
 bind_aset(bind,2/*oldchanged*/,it); it=rb_funcall(self,s_visit_Constant_Traversercb_3Constant_Traverser,1,bind); 
 bind_aset(bind,3/*this*/,it); it=Qnil;
 bind_aset(bind,4/*clon*/,it); it=Qfalse;
 bind_aset(bind,5/*changed*/,it); it=rb_funcall(self,s_traverse_Constant_Traversercb_3Constant_Traverser,1,bind); 
 bind_aset(bind,6/*autovar*/,it); it=rb_funcall(self,s_traverse_Constant_Traversercb_4Constant_Traverser,1,bind); int oldpos2=ame_getpos(self); int oldlen1=ame_getlen(self); VALUE oldsrc1=ame_getsrc(self); int fail1=0;
ame_setsrc(self,bind_aget(bind,6/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeConstant_Traverser,0)));
   it=AmethystCore_anything(self ); FAILTEST(pass1);
 bind_aset(bind,7/*autovar*/,it); int oldpos3=ame_getpos(self); int oldlen2=ame_getlen(self); VALUE oldsrc2=ame_getsrc(self); int fail2=0;
ame_setsrc(self,bind_aget(bind,7/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeConstant_Traverser,0)));
 it=rb_ary_new3(0);
 bind_aset(bind,8/*autovar*/,it); int oldpos4; while(1){oldpos4=ame_getpos(self);   it=AmethystCore_anything(self ); FAILTEST(break2);
 bind_aset(bind,9/*autovar*/,it); int oldpos5=ame_getpos(self); int oldlen3=ame_getlen(self); VALUE oldsrc3=ame_getsrc(self); int fail3=0;
ame_setsrc(self,bind_aget(bind,9/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeConstant_Traverser,0)));
   it=AmethystCore_anything(self ); FAILTEST(pass3);
 bind_aset(bind,10/*key*/,it); it=rb_funcall(self,s_traverse_Constant_Traversercb_5Constant_Traverser,1,bind);   it=Constant_Traverser_traverse_item(self ); FAILTEST(pass3);
 bind_aset(bind,11/*val*/,it); it=rb_funcall(self,s_traverse_Constant_Traversercb_6Constant_Traverser,1,bind); 
 bind_aset(bind,12/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass3);
	goto success3;
	pass3: fail3=1;
	success3: ame_setsrc(self,oldsrc3); ame_setpos(self,oldpos5); ame_setlen(self,oldlen3);
	if(fail3) goto break2;
it=bind_aget(bind,12/*autovar*/);
 bind_aset(bind,13/*autovar*/,it); it=rb_funcall(self,s_traverse_Constant_Traversercb_7Constant_Traverser,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos4=ame_getpos(self);goto break2;} } } break2: ame_setstop(self,Qnil);  ame_setpos(self,oldpos4); it=bind_aget(bind,8/*autovar*/);  it=Amethyst_eof(self ); FAILTEST(pass2);
	goto success2;
	pass2: fail2=1;
	success2: ame_setsrc(self,oldsrc2); ame_setpos(self,oldpos3); ame_setlen(self,oldlen2);
	if(fail2) goto pass1;
  it=Amethyst_eof(self ); FAILTEST(pass1);
	goto success1;
	pass1: fail1=1;
	success1: ame_setsrc(self,oldsrc1); ame_setpos(self,oldpos2); ame_setlen(self,oldlen1);
	if(fail1) goto fail;
it=rb_funcall(self,s_traverse_Constant_Traversercb_8Constant_Traverser,1,bind); 
 bind_aset(bind,14/*_result*/,it); it=bind_aget(bind,14/*_result*/);
return it;
fail: return failobj; }
VALUE Constant_Traverser_traverse_item(VALUE self ){VALUE vals[0]; VALUE bind=bind_new2(10);  int x;VALUE arg0,arg1,arg2,arg3;VALUE it;

int oldpos1=ame_getpos(self);
alt1_1: ame_setpos(self,oldpos1);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
   it=Constant_Traverser_visit(self ); FAILTEST(alt1_2);
 bind_aset(bind,0/*a*/,it); it=rb_funcall(self,s_traverse_item_Constant_Traversercb_1Constant_Traverser,1,bind); it=bind_aget(bind,0/*a*/);
 bind_aset(bind,1/*_result*/,it);  
ame_setcut(self,Qnil);goto accept1;
alt1_2: ame_setpos(self,oldpos1);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
  it=c_491; arg0=it; it=Amethyst_clas(self ,arg0); FAILTEST(alt1_3);
 bind_aset(bind,2/*autovar*/,it); int oldpos2=ame_getpos(self); int oldlen1=ame_getlen(self); VALUE oldsrc1=ame_getsrc(self); int fail1=0;
ame_setsrc(self,bind_aget(bind,2/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeConstant_Traverser,0)));
 it=rb_ary_new3(0);
 bind_aset(bind,3/*ar*/,it); it=rb_ary_new3(0);
 bind_aset(bind,4/*autovar*/,it); int oldpos3; while(1){oldpos3=ame_getpos(self);   it=Constant_Traverser_traverse_item(self ); FAILTEST(break1);
 bind_aset(bind,5/*it*/,it); it=rb_funcall(self,s_traverse_item_Constant_Traversercb_2Constant_Traverser,1,bind); 
 bind_aset(bind,6/*autovar*/,it); it=rb_funcall(self,s_traverse_item_Constant_Traversercb_3Constant_Traverser,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos3=ame_getpos(self);goto break1;} } } break1: ame_setstop(self,Qnil);  ame_setpos(self,oldpos3); it=bind_aget(bind,4/*autovar*/);it=bind_aget(bind,3/*ar*/);
 bind_aset(bind,7/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass1);
	goto success1;
	pass1: fail1=1;
	success1: ame_setsrc(self,oldsrc1); ame_setpos(self,oldpos2); ame_setlen(self,oldlen1);
	if(fail1) goto alt1_3;
it=bind_aget(bind,7/*autovar*/);
 bind_aset(bind,1/*_result*/,it);  
ame_setcut(self,Qnil);goto accept1;
alt1_3: ame_setpos(self,oldpos1);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
  it=c_494; arg0=it; it=Amethyst_clas(self ,arg0); FAILTEST(alt1_4);
 bind_aset(bind,8/*autovar*/,it); int oldpos4=ame_getpos(self); int oldlen2=ame_getlen(self); VALUE oldsrc2=ame_getsrc(self); int fail2=0;
ame_setsrc(self,bind_aget(bind,8/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeConstant_Traverser,0)));
   it=Constant_Traverser_traverse(self ); FAILTEST(pass2);
 bind_aset(bind,9/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass2);
	goto success2;
	pass2: fail2=1;
	success2: ame_setsrc(self,oldsrc2); ame_setpos(self,oldpos4); ame_setlen(self,oldlen2);
	if(fail2) goto alt1_4;
it=bind_aget(bind,9/*autovar*/);
 bind_aset(bind,1/*_result*/,it);  
ame_setcut(self,Qnil);goto accept1;
alt1_4: ame_setpos(self,oldpos1);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
   it=AmethystCore_anything(self ); FAILTEST(alt1_5);
 bind_aset(bind,1/*_result*/,it);  
ame_setcut(self,Qnil);goto accept1;
  alt1_5:  ame_setpos(self,oldpos1); goto fail;
 accept1:;
it=bind_aget(bind,1/*_result*/);
return it;
fail: return failobj; }
VALUE Constant_Traverser_visit(VALUE self ){VALUE vals[0]; VALUE bind=bind_new2(16);  int x;VALUE arg0,arg1,arg2,arg3;VALUE it;

int oldpos1=ame_getpos(self);
alt1_1: ame_setpos(self,oldpos1);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
  it=c_484; arg0=it; it=Amethyst_clas(self ,arg0); FAILTEST(alt1_2);
 bind_aset(bind,0/*autovar*/,it); int oldpos2=ame_getpos(self); int oldlen1=ame_getlen(self); VALUE oldsrc1=ame_getsrc(self); int fail1=0;
ame_setsrc(self,bind_aget(bind,0/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeConstant_Traverser,0)));
   it=Constant_Traverser_traverse_item(self ); FAILTEST(pass1);
 bind_aset(bind,1/*expr*/,it); it=rb_funcall(self,s_visit_Constant_Traversercb_1Constant_Traverser,1,bind); 
 bind_aset(bind,2/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass1);
	goto success1;
	pass1: fail1=1;
	success1: ame_setsrc(self,oldsrc1); ame_setpos(self,oldpos2); ame_setlen(self,oldlen1);
	if(fail1) goto alt1_2;
it=bind_aget(bind,2/*autovar*/);
 bind_aset(bind,3/*_result*/,it);  
ame_setcut(self,Qnil);goto accept1;
alt1_2: ame_setpos(self,oldpos1);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
  it=c_485; arg0=it; it=Amethyst_clas(self ,arg0); FAILTEST(alt1_3);
 bind_aset(bind,4/*autovar*/,it); int oldpos3=ame_getpos(self); int oldlen2=ame_getlen(self); VALUE oldsrc2=ame_getsrc(self); int fail2=0;
ame_setsrc(self,bind_aget(bind,4/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeConstant_Traverser,0)));
 it=rb_ary_new3(0);
 bind_aset(bind,5/*autovar*/,it); int oldpos4; while(1){oldpos4=ame_getpos(self);   it=AmethystCore_anything(self ); FAILTEST(break1);
 bind_aset(bind,6/*autovar*/,it); it=rb_funcall(self,s_visit_Constant_Traversercb_2Constant_Traverser,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos4=ame_getpos(self);goto break1;} } } break1: ame_setstop(self,Qnil);  ame_setpos(self,oldpos4); it=bind_aget(bind,5/*autovar*/);it=rb_funcall(self,s_visit_Constant_Traversercb_3Constant_Traverser,1,bind); 
 bind_aset(bind,7/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass2);
	goto success2;
	pass2: fail2=1;
	success2: ame_setsrc(self,oldsrc2); ame_setpos(self,oldpos3); ame_setlen(self,oldlen2);
	if(fail2) goto alt1_3;
it=bind_aget(bind,7/*autovar*/);
 bind_aset(bind,3/*_result*/,it);  
ame_setcut(self,Qnil);goto accept1;
alt1_3: ame_setpos(self,oldpos1);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
  it=c_487; arg0=it; it=Amethyst_clas(self ,arg0); FAILTEST(alt1_4);
 bind_aset(bind,8/*autovar*/,it); int oldpos5=ame_getpos(self); int oldlen3=ame_getlen(self); VALUE oldsrc3=ame_getsrc(self); int fail3=0;
ame_setsrc(self,bind_aget(bind,8/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeConstant_Traverser,0)));
 it=rb_ary_new3(0);
 bind_aset(bind,9/*autovar*/,it); int oldpos6; while(1){oldpos6=ame_getpos(self);   it=AmethystCore_anything(self ); FAILTEST(break2);
 bind_aset(bind,10/*autovar*/,it); it=rb_funcall(self,s_visit_Constant_Traversercb_4Constant_Traverser,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos6=ame_getpos(self);goto break2;} } } break2: ame_setstop(self,Qnil);  ame_setpos(self,oldpos6); it=bind_aget(bind,9/*autovar*/);it=rb_funcall(self,s_visit_Constant_Traversercb_3Constant_Traverser,1,bind); 
 bind_aset(bind,11/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass3);
	goto success3;
	pass3: fail3=1;
	success3: ame_setsrc(self,oldsrc3); ame_setpos(self,oldpos5); ame_setlen(self,oldlen3);
	if(fail3) goto alt1_4;
it=bind_aget(bind,11/*autovar*/);
 bind_aset(bind,3/*_result*/,it);  
ame_setcut(self,Qnil);goto accept1;
alt1_4: ame_setpos(self,oldpos1);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
  it=c_489; arg0=it; it=Amethyst_clas(self ,arg0); FAILTEST(alt1_5);
 bind_aset(bind,12/*autovar*/,it); int oldpos7=ame_getpos(self); int oldlen4=ame_getlen(self); VALUE oldsrc4=ame_getsrc(self); int fail4=0;
ame_setsrc(self,bind_aget(bind,12/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeConstant_Traverser,0)));
 it=rb_ary_new3(0);
 bind_aset(bind,13/*autovar*/,it); int oldpos8; while(1){oldpos8=ame_getpos(self);   it=AmethystCore_anything(self ); FAILTEST(break3);
 bind_aset(bind,14/*autovar*/,it); it=rb_funcall(self,s_visit_Constant_Traversercb_5Constant_Traverser,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos8=ame_getpos(self);goto break3;} } } break3: ame_setstop(self,Qnil);  ame_setpos(self,oldpos8); it=bind_aget(bind,13/*autovar*/);it=rb_funcall(self,s_visit_Constant_Traversercb_6Constant_Traverser,1,bind); 
 bind_aset(bind,15/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass4);
	goto success4;
	pass4: fail4=1;
	success4: ame_setsrc(self,oldsrc4); ame_setpos(self,oldpos7); ame_setlen(self,oldlen4);
	if(fail4) goto alt1_5;
it=bind_aget(bind,15/*autovar*/);
 bind_aset(bind,3/*_result*/,it);  
ame_setcut(self,Qnil);goto accept1;
  alt1_5:  ame_setpos(self,oldpos1); goto fail;
 accept1:;
it=bind_aget(bind,3/*_result*/);
return it;
fail: return failobj; }
void Init_constant_propagation_c(){ 
 cls_Constant_Propagator=rb_define_class("Constant_Propagator",rb_const_get(rb_cObject,rb_intern("Amethyst"))); 
failobj=rb_eval_string("FAIL");
c_474=rb_const_get(rb_cObject, rb_intern("Local"));rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),c_474);
c_476=rb_const_get(rb_cObject, rb_intern("Bind"));rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),c_476);
c_477=rb_const_get(rb_cObject, rb_intern("Act"));rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),c_477);
c_478=rb_const_get(rb_cObject, rb_intern("Local"));rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),c_478);
c_480=rb_const_get(rb_cObject, rb_intern("Exp"));rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),c_480);
c_482=rb_const_get(rb_cObject, rb_intern("CAct"));rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),c_482);
s_root_Constant_Propagatorcb_1Constant_Propagator=rb_intern("root_Constant_Propagatorcb_1");
s_sizeConstant_Propagator=rb_intern("size");
s_step_Constant_Propagatorcb_10Constant_Propagator=rb_intern("step_Constant_Propagatorcb_10");
s_step_Constant_Propagatorcb_1Constant_Propagator=rb_intern("step_Constant_Propagatorcb_1");
s_step_Constant_Propagatorcb_2Constant_Propagator=rb_intern("step_Constant_Propagatorcb_2");
s_step_Constant_Propagatorcb_3Constant_Propagator=rb_intern("step_Constant_Propagatorcb_3");
s_step_Constant_Propagatorcb_4Constant_Propagator=rb_intern("step_Constant_Propagatorcb_4");
s_step_Constant_Propagatorcb_5Constant_Propagator=rb_intern("step_Constant_Propagatorcb_5");
s_step_Constant_Propagatorcb_6Constant_Propagator=rb_intern("step_Constant_Propagatorcb_6");
s_step_Constant_Propagatorcb_7Constant_Propagator=rb_intern("step_Constant_Propagatorcb_7");
s_step_Constant_Propagatorcb_8Constant_Propagator=rb_intern("step_Constant_Propagatorcb_8");
s_step_Constant_Propagatorcb_9Constant_Propagator=rb_intern("step_Constant_Propagatorcb_9");
s_valofConstant_Propagator=rb_intern("valof");
rb_define_method(cls_Constant_Propagator,"root",Constant_Propagator_root,0);
rb_define_method(cls_Constant_Propagator,"step",Constant_Propagator_step,1);

 cls_Constant_Traverser=rb_define_class("Constant_Traverser",rb_const_get(rb_cObject,rb_intern("Traverser_Clone2"))); 
failobj=rb_eval_string("FAIL");
c_484=rb_const_get(rb_cObject, rb_intern("Bind"));rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),c_484);
c_485=rb_const_get(rb_cObject, rb_intern("Act"));rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),c_485);
c_487=rb_const_get(rb_cObject, rb_intern("Result"));rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),c_487);
c_489=rb_const_get(rb_cObject, rb_intern("Local"));rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),c_489);
c_491=rb_const_get(rb_cObject, rb_intern("Array"));rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),c_491);
c_494=rb_const_get(rb_cObject, rb_intern("AmethystAST"));rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),c_494);
s_root_Constant_Traversercb_1Constant_Traverser=rb_intern("root_Constant_Traversercb_1");
s_root_Constant_Traversercb_2Constant_Traverser=rb_intern("root_Constant_Traversercb_2");
s_sizeConstant_Traverser=rb_intern("size");
s_traverse_Constant_Traversercb_1Constant_Traverser=rb_intern("traverse_Constant_Traversercb_1");
s_traverse_Constant_Traversercb_2Constant_Traverser=rb_intern("traverse_Constant_Traversercb_2");
s_traverse_Constant_Traversercb_3Constant_Traverser=rb_intern("traverse_Constant_Traversercb_3");
s_traverse_Constant_Traversercb_4Constant_Traverser=rb_intern("traverse_Constant_Traversercb_4");
s_traverse_Constant_Traversercb_5Constant_Traverser=rb_intern("traverse_Constant_Traversercb_5");
s_traverse_Constant_Traversercb_6Constant_Traverser=rb_intern("traverse_Constant_Traversercb_6");
s_traverse_Constant_Traversercb_7Constant_Traverser=rb_intern("traverse_Constant_Traversercb_7");
s_traverse_Constant_Traversercb_8Constant_Traverser=rb_intern("traverse_Constant_Traversercb_8");
s_traverse_item_Constant_Traversercb_1Constant_Traverser=rb_intern("traverse_item_Constant_Traversercb_1");
s_traverse_item_Constant_Traversercb_2Constant_Traverser=rb_intern("traverse_item_Constant_Traversercb_2");
s_traverse_item_Constant_Traversercb_3Constant_Traverser=rb_intern("traverse_item_Constant_Traversercb_3");
s_visit_Constant_Traversercb_1Constant_Traverser=rb_intern("visit_Constant_Traversercb_1");
s_visit_Constant_Traversercb_2Constant_Traverser=rb_intern("visit_Constant_Traversercb_2");
s_visit_Constant_Traversercb_3Constant_Traverser=rb_intern("visit_Constant_Traversercb_3");
s_visit_Constant_Traversercb_4Constant_Traverser=rb_intern("visit_Constant_Traversercb_4");
s_visit_Constant_Traversercb_5Constant_Traverser=rb_intern("visit_Constant_Traversercb_5");
s_visit_Constant_Traversercb_6Constant_Traverser=rb_intern("visit_Constant_Traversercb_6");
rb_define_method(cls_Constant_Traverser,"root",Constant_Traverser_root,0);
rb_define_method(cls_Constant_Traverser,"traverse",Constant_Traverser_traverse,0);
rb_define_method(cls_Constant_Traverser,"traverse_item",Constant_Traverser_traverse_item,0);
rb_define_method(cls_Constant_Traverser,"visit",Constant_Traverser_visit,0);
 rb_eval_string("testversionconstant_propagation('c009af3a44fc9383bd1e15b2e8f7bf1e')");}
