#include "cthyst.h"
VALUE cls_AmethystCTranslator;
VALUE AmethystCTranslator_add_c_global(VALUE self ,VALUE a0,VALUE a1);
VALUE AmethystCTranslator_addcallback(VALUE self ,VALUE a0);
VALUE AmethystCTranslator_addlambda(VALUE self );
VALUE AmethystCTranslator_failwrap(VALUE self ,VALUE a0);
VALUE AmethystCTranslator_itrans(VALUE self );
VALUE AmethystCTranslator_rbcode(VALUE self );
VALUE AmethystCTranslator_rbtrans(VALUE self );
VALUE AmethystCTranslator_rbtrans2(VALUE self );
VALUE AmethystCTranslator_rw(VALUE self ,VALUE a0,VALUE a1);
VALUE AmethystCTranslator_trans(VALUE self );
VALUE AmethystCore__seq(VALUE self ,VALUE);
VALUE AmethystCore_anything(VALUE self );
VALUE Amethyst_eof(VALUE self );
VALUE Amethyst_fails(VALUE self );
VALUE Amethyst_spaces(VALUE self );
VALUE switchhashAmethystCTranslator1;
VALUE switchhashAmethystCTranslator2;
static VALUE c_435;
static VALUE c_436;
static VALUE c_437;
static VALUE c_438;
static VALUE c_439;
static VALUE c_440;
static VALUE c_442;
static VALUE c_443;
static VALUE c_445;
static VALUE c_446;
static VALUE c_447;
static VALUE c_450;
static VALUE c_453;
static VALUE c_454;
static VALUE c_456;
static VALUE s_add_c_global_AmethystCTranslatorcb_1AmethystCTranslator;
static VALUE s_addcallback_AmethystCTranslatorcb_1AmethystCTranslator;
static VALUE s_addlambda_AmethystCTranslatorcb_1AmethystCTranslator;
static VALUE s_addlambda_AmethystCTranslatorcb_2AmethystCTranslator;
static VALUE s_addlambda_AmethystCTranslatorcb_3AmethystCTranslator;
static VALUE s_addlambda_AmethystCTranslatorcb_4AmethystCTranslator;
static VALUE s_addlambda_AmethystCTranslatorcb_5AmethystCTranslator;
static VALUE s_applyAmethystCTranslator;
static VALUE s_failwrap_AmethystCTranslatorcb_1AmethystCTranslator;
static VALUE s_itrans_AmethystCTranslatorcb_1AmethystCTranslator;
static VALUE s_itrans_AmethystCTranslatorcb_2AmethystCTranslator;
static VALUE s_itrans_AmethystCTranslatorcb_3AmethystCTranslator;
static VALUE s_itrans_AmethystCTranslatorcb_4AmethystCTranslator;
static VALUE s_itrans_AmethystCTranslatorcb_5AmethystCTranslator;
static VALUE s_labelAmethystCTranslator;
static VALUE s_rbcode_AmethystCTranslatorcb_1AmethystCTranslator;
static VALUE s_rbcode_AmethystCTranslatorcb_2AmethystCTranslator;
static VALUE s_rbcode_AmethystCTranslatorcb_3AmethystCTranslator;
static VALUE s_rbcode_AmethystCTranslatorcb_4AmethystCTranslator;
static VALUE s_rbcode_AmethystCTranslatorcb_5AmethystCTranslator;
static VALUE s_rbcode_AmethystCTranslatorcb_6AmethystCTranslator;
static VALUE s_rbcode_AmethystCTranslatorcb_7AmethystCTranslator;
static VALUE s_rbtrans2_AmethystCTranslatorcb_1AmethystCTranslator;
static VALUE s_rbtrans2_AmethystCTranslatorcb_2AmethystCTranslator;
static VALUE s_rbtrans_AmethystCTranslatorcb_1AmethystCTranslator;
static VALUE s_rbtrans_AmethystCTranslatorcb_2AmethystCTranslator;
static VALUE s_rbtrans_AmethystCTranslatorcb_3AmethystCTranslator;
static VALUE s_rbtrans_AmethystCTranslatorcb_4AmethystCTranslator;
static VALUE s_rbtrans_AmethystCTranslatorcb_5AmethystCTranslator;
static VALUE s_rw_AmethystCTranslatorcb_1AmethystCTranslator;
static VALUE s_sizeAmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_10AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_11AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_12AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_13AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_14AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_15AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_16AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_17AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_18AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_19AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_1AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_20AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_21AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_22AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_23AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_24AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_25AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_26AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_27AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_28AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_29AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_2AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_30AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_31AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_32AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_33AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_34AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_35AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_36AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_37AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_38AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_39AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_3AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_40AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_41AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_42AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_43AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_44AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_45AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_46AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_47AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_48AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_49AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_4AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_50AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_51AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_52AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_53AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_54AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_55AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_56AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_57AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_58AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_59AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_5AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_60AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_6AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_7AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_8AmethystCTranslator;
static VALUE s_trans_AmethystCTranslatorcb_9AmethystCTranslator;
VALUE AmethystCTranslator_add_c_global(VALUE self ,VALUE a0,VALUE a1){VALUE vals[2]; VALUE bind=bind_new2(3); bind_aset(bind,0/*name*/,a0);bind_aset(bind,1/*expr*/,a1); int x;VALUE arg0,arg1,arg2,arg3;VALUE it;

it=rb_funcall(self,s_add_c_global_AmethystCTranslatorcb_1AmethystCTranslator,1,bind); 
 bind_aset(bind,2/*_result*/,it); it=bind_aget(bind,2/*_result*/);
return it;
fail: return failobj; }
VALUE AmethystCTranslator_addcallback(VALUE self ,VALUE a0){VALUE vals[1]; VALUE bind=bind_new2(3); bind_aset(bind,0/*s*/,a0); int x;VALUE arg0,arg1,arg2,arg3;VALUE it;

it=bind_aget(bind,0/*s*/);
 bind_aset(bind,1/*autovar*/,it); it=rb_funcall(self,s_rbcode_AmethystCTranslatorcb_4AmethystCTranslator,1,bind); int oldpos1=ame_getpos(self); int oldlen1=ame_getlen(self); VALUE oldsrc1=ame_getsrc(self); int fail1=0;
ame_setsrc(self,bind_aget(bind,1/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeAmethystCTranslator,0)));
   it=AmethystCTranslator_rbtrans2(self ); FAILTEST(pass1);
 bind_aset(bind,0/*s*/,it);   it=Amethyst_eof(self ); FAILTEST(pass1);
	goto success1;
	pass1: fail1=1;
	success1: ame_setsrc(self,oldsrc1); ame_setpos(self,oldpos1); ame_setlen(self,oldlen1);
	if(fail1) goto fail;
it=rb_funcall(self,s_addcallback_AmethystCTranslatorcb_1AmethystCTranslator,1,bind); 
 bind_aset(bind,2/*_result*/,it); it=bind_aget(bind,2/*_result*/);
return it;
fail: return failobj; }
VALUE AmethystCTranslator_addlambda(VALUE self ){VALUE vals[0]; VALUE bind=bind_new2(6);  int x;VALUE arg0,arg1,arg2,arg3;VALUE it;

it=rb_funcall(self,s_addlambda_AmethystCTranslatorcb_1AmethystCTranslator,1,bind); 
 bind_aset(bind,0/*lambd*/,it); it=rb_obj_clone(c_456);
 bind_aset(bind,1/*word*/,it); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_4AmethystCTranslator,1,bind); 
 bind_aset(bind,2/*rwo*/,it); it=rb_funcall(self,s_addlambda_AmethystCTranslatorcb_2AmethystCTranslator,1,bind);   it=AmethystCTranslator_trans(self ); FAILTEST(fail);
 bind_aset(bind,3/*body*/,it); 
 bind_aset(bind,4/*_result*/,it); it=bind_aget(bind,4/*_result*/);
 bind_aset(bind,5/*x*/,it); it=rb_funcall(self,s_addlambda_AmethystCTranslatorcb_3AmethystCTranslator,1,bind); it=rb_funcall(self,s_addlambda_AmethystCTranslatorcb_4AmethystCTranslator,1,bind); it=rb_funcall(self,s_addlambda_AmethystCTranslatorcb_5AmethystCTranslator,1,bind); 
 bind_aset(bind,4/*_result*/,it); it=bind_aget(bind,4/*_result*/);
return it;
fail: return failobj; }
VALUE AmethystCTranslator_failwrap(VALUE self ,VALUE a0){VALUE vals[1]; VALUE bind=bind_new2(2); bind_aset(bind,0/*s*/,a0); int x;VALUE arg0,arg1,arg2,arg3;VALUE it;

it=rb_funcall(self,s_failwrap_AmethystCTranslatorcb_1AmethystCTranslator,1,bind); 
 bind_aset(bind,1/*_result*/,it); it=bind_aget(bind,1/*_result*/);
return it;
fail: return failobj; }
VALUE AmethystCTranslator_itrans(VALUE self ){VALUE vals[0]; VALUE bind=bind_new2(10);  int x;VALUE arg0,arg1,arg2,arg3;VALUE it;

it=rb_ary_new3(0);
 bind_aset(bind,0/*ruby*/,it); it=rb_ary_new3(0);
 bind_aset(bind,1/*c*/,it); it=rb_ary_new3(0);
 bind_aset(bind,2/*init*/,it); it=rb_ary_new3(0);
 bind_aset(bind,3/*autovar*/,it); int oldpos1; while(1){oldpos1=ame_getpos(self); int oldpos2=ame_getpos(self);
alt1_1: ame_setpos(self,oldpos2);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto break1;}
   it=AmethystCore_anything(self ); FAILTEST(alt1_2);
 bind_aset(bind,4/*c*/,it); it=rb_funcall(self,s_itrans_AmethystCTranslatorcb_1AmethystCTranslator,1,bind); FAILTEST(alt1_2);it=bind_aget(bind,4/*c*/);
 bind_aset(bind,5/*_result*/,it); it=bind_aget(bind,5/*_result*/);
 bind_aset(bind,6/*autovar*/,it); it=rb_funcall(self,s_itrans_AmethystCTranslatorcb_2AmethystCTranslator,1,bind); it=bind_aget(bind,6/*autovar*/);
 bind_aset(bind,7/*autovar*/,it);  
ame_setcut(self,Qnil);goto accept1;
alt1_2: ame_setpos(self,oldpos2);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto break1;}
   it=AmethystCTranslator_trans(self ); FAILTEST(alt1_3);
 bind_aset(bind,8/*it*/,it); it=rb_funcall(self,s_itrans_AmethystCTranslatorcb_3AmethystCTranslator,1,bind); 
 bind_aset(bind,7/*autovar*/,it);  
ame_setcut(self,Qnil);goto accept1;
  alt1_3:  ame_setpos(self,oldpos2); goto break1;
 accept1:;
it=rb_funcall(self,s_itrans_AmethystCTranslatorcb_4AmethystCTranslator,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos1=ame_getpos(self);goto break1;} } } break1: ame_setstop(self,Qnil);  ame_setpos(self,oldpos1); it=bind_aget(bind,3/*autovar*/);it=rb_funcall(self,s_itrans_AmethystCTranslatorcb_5AmethystCTranslator,1,bind); 
 bind_aset(bind,9/*_result*/,it); it=bind_aget(bind,9/*_result*/);
return it;
fail: return failobj; }
VALUE AmethystCTranslator_rbcode(VALUE self ){VALUE vals[0]; VALUE bind=bind_new2(10);  int x;VALUE arg0,arg1,arg2,arg3;VALUE it;

it=rb_funcall(self,s_rbcode_AmethystCTranslatorcb_1AmethystCTranslator,1,bind); 
 bind_aset(bind,0/*s*/,it); it=rb_funcall(self,s_rbcode_AmethystCTranslatorcb_2AmethystCTranslator,1,bind); it=rb_funcall(self,s_rbcode_AmethystCTranslatorcb_3AmethystCTranslator,1,bind); 
 bind_aset(bind,1/*autovar*/,it); it=rb_funcall(self,s_rbcode_AmethystCTranslatorcb_4AmethystCTranslator,1,bind); int oldpos1=ame_getpos(self); int oldlen1=ame_getlen(self); VALUE oldsrc1=ame_getsrc(self); int fail1=0;
ame_setsrc(self,bind_aget(bind,1/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeAmethystCTranslator,0)));
   it=AmethystCore_anything(self ); FAILTEST(pass1);
 bind_aset(bind,2/*autovar*/,it); int oldpos2=ame_getpos(self); int oldlen2=ame_getlen(self); VALUE oldsrc2=ame_getsrc(self); int fail2=0;
ame_setsrc(self,bind_aget(bind,2/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeAmethystCTranslator,0)));
 it=rb_ary_new3(0);
 bind_aset(bind,3/*autovar*/,it); int oldpos3; while(1){oldpos3=ame_getpos(self);   it=AmethystCore_anything(self ); FAILTEST(break1);
 bind_aset(bind,4/*autovar*/,it); int oldpos4=ame_getpos(self); int oldlen3=ame_getlen(self); VALUE oldsrc3=ame_getsrc(self); int fail3=0;
ame_setsrc(self,bind_aget(bind,4/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeAmethystCTranslator,0)));
   it=AmethystCore_anything(self ); FAILTEST(pass3);
 bind_aset(bind,5/*k*/,it);   it=AmethystCore_anything(self ); FAILTEST(pass3);
 bind_aset(bind,6/*v*/,it);   it=Amethyst_eof(self ); FAILTEST(pass3);
	goto success3;
	pass3: fail3=1;
	success3: ame_setsrc(self,oldsrc3); ame_setpos(self,oldpos4); ame_setlen(self,oldlen3);
	if(fail3) goto break1;
it=rb_funcall(self,s_rbcode_AmethystCTranslatorcb_5AmethystCTranslator,1,bind); 
 bind_aset(bind,7/*autovar*/,it); it=rb_funcall(self,s_itrans_AmethystCTranslatorcb_4AmethystCTranslator,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos3=ame_getpos(self);goto break1;} } } break1: ame_setstop(self,Qnil);  ame_setpos(self,oldpos3); it=bind_aget(bind,3/*autovar*/);
 bind_aset(bind,8/*x*/,it);   it=Amethyst_eof(self ); FAILTEST(pass2);
	goto success2;
	pass2: fail2=1;
	success2: ame_setsrc(self,oldsrc2); ame_setpos(self,oldpos2); ame_setlen(self,oldlen2);
	if(fail2) goto pass1;
  it=Amethyst_eof(self ); FAILTEST(pass1);
	goto success1;
	pass1: fail1=1;
	success1: ame_setsrc(self,oldsrc1); ame_setpos(self,oldpos1); ame_setlen(self,oldlen1);
	if(fail1) goto fail;
it=rb_funcall(self,s_rbcode_AmethystCTranslatorcb_6AmethystCTranslator,1,bind); it=rb_funcall(self,s_rbcode_AmethystCTranslatorcb_7AmethystCTranslator,1,bind); 
 bind_aset(bind,9/*_result*/,it); it=bind_aget(bind,9/*_result*/);
return it;
fail: return failobj; }
VALUE AmethystCTranslator_rbtrans(VALUE self ){VALUE vals[0]; VALUE bind=bind_new2(23);  int x;VALUE arg0,arg1,arg2,arg3;VALUE it;

unsigned char chr1=FIX2LONG(rb_hash_aref(switchhashAmethystCTranslator2,rb_obj_class(ame_curobj(self))));  switch(chr1){case 0:;   it=AmethystCore_anything(self ); FAILTEST(fail);
 bind_aset(bind,0/*autovar*/,it); int oldpos1=ame_getpos(self);
alt1_1: ame_setpos(self,oldpos1);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
 it=bind_aget(bind,0/*autovar*/);
 bind_aset(bind,1/*autovar*/,it); int oldpos2=ame_getpos(self); int oldlen1=ame_getlen(self); VALUE oldsrc1=ame_getsrc(self); int fail1=0;
ame_setsrc(self,bind_aget(bind,1/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeAmethystCTranslator,0)));
   it=AmethystCTranslator_rbtrans2(self ); FAILTEST(pass1);
 bind_aset(bind,2/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass1);
	goto success1;
	pass1: fail1=1;
	success1: ame_setsrc(self,oldsrc1); ame_setpos(self,oldpos2); ame_setlen(self,oldlen1);
	if(fail1) goto alt1_2;
it=bind_aget(bind,2/*autovar*/);
 bind_aset(bind,3/*_result*/,it);  
ame_setcut(self,Qnil);goto accept1;
alt1_2: ame_setpos(self,oldpos1);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
 it=bind_aget(bind,0/*autovar*/);
 bind_aset(bind,3/*_result*/,it);  
ame_setcut(self,Qnil);goto accept1;
  alt1_3:  ame_setpos(self,oldpos1); goto fail;
 accept1:;
 break;case 1:;   it=AmethystCore_anything(self ); FAILTEST(fail);
 bind_aset(bind,4/*autovar*/,it); int oldpos3=ame_getpos(self);
alt2_1: ame_setpos(self,oldpos3);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
 it=bind_aget(bind,4/*autovar*/);
 bind_aset(bind,5/*autovar*/,it); int oldpos4=ame_getpos(self); int oldlen2=ame_getlen(self); VALUE oldsrc2=ame_getsrc(self); int fail2=0;
ame_setsrc(self,bind_aget(bind,5/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeAmethystCTranslator,0)));
   it=AmethystCTranslator_rbtrans2(self ); FAILTEST(pass2);
 bind_aset(bind,6/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass2);
	goto success2;
	pass2: fail2=1;
	success2: ame_setsrc(self,oldsrc2); ame_setpos(self,oldpos4); ame_setlen(self,oldlen2);
	if(fail2) goto alt2_2;
it=bind_aget(bind,6/*autovar*/);
 bind_aset(bind,3/*_result*/,it);  
ame_setcut(self,Qnil);goto accept2;
alt2_2: ame_setpos(self,oldpos3);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
 it=bind_aget(bind,4/*autovar*/);
 bind_aset(bind,3/*_result*/,it);  
ame_setcut(self,Qnil);goto accept2;
  alt2_3:  ame_setpos(self,oldpos3); goto fail;
 accept2:;
 break;case 2:;   it=AmethystCore_anything(self ); FAILTEST(fail);
 bind_aset(bind,7/*autovar*/,it); int oldpos5=ame_getpos(self);
alt3_1: ame_setpos(self,oldpos5);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
 it=bind_aget(bind,7/*autovar*/);
 bind_aset(bind,8/*autovar*/,it); int oldpos6=ame_getpos(self); int oldlen3=ame_getlen(self); VALUE oldsrc3=ame_getsrc(self); int fail3=0;
ame_setsrc(self,bind_aget(bind,8/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeAmethystCTranslator,0)));
   it=AmethystCTranslator_addlambda(self ); FAILTEST(pass3);
 bind_aset(bind,9/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass3);
	goto success3;
	pass3: fail3=1;
	success3: ame_setsrc(self,oldsrc3); ame_setpos(self,oldpos6); ame_setlen(self,oldlen3);
	if(fail3) goto alt3_2;
it=bind_aget(bind,9/*autovar*/);
 bind_aset(bind,3/*_result*/,it);  
ame_setcut(self,Qnil);goto accept3;
alt3_2: ame_setpos(self,oldpos5);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
 it=bind_aget(bind,7/*autovar*/);
 bind_aset(bind,3/*_result*/,it);  
ame_setcut(self,Qnil);goto accept3;
  alt3_3:  ame_setpos(self,oldpos5); goto fail;
 accept3:;
 break;case 3:;   it=AmethystCore_anything(self ); FAILTEST(fail);
 bind_aset(bind,10/*autovar*/,it); int oldpos7=ame_getpos(self);
alt4_1: ame_setpos(self,oldpos7);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
 it=bind_aget(bind,10/*autovar*/);
 bind_aset(bind,11/*autovar*/,it); int oldpos8=ame_getpos(self); int oldlen4=ame_getlen(self); VALUE oldsrc4=ame_getsrc(self); int fail4=0;
ame_setsrc(self,bind_aget(bind,11/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeAmethystCTranslator,0)));
   it=AmethystCore_anything(self ); FAILTEST(pass4);
 bind_aset(bind,12/*name*/,it);   it=Amethyst_eof(self ); FAILTEST(pass4);
	goto success4;
	pass4: fail4=1;
	success4: ame_setsrc(self,oldsrc4); ame_setpos(self,oldpos8); ame_setlen(self,oldlen4);
	if(fail4) goto alt4_2;
it=rb_funcall(self,s_rbtrans_AmethystCTranslatorcb_1AmethystCTranslator,1,bind); 
 bind_aset(bind,3/*_result*/,it);  
ame_setcut(self,Qnil);goto accept4;
alt4_2: ame_setpos(self,oldpos7);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
 it=bind_aget(bind,10/*autovar*/);
 bind_aset(bind,3/*_result*/,it);  
ame_setcut(self,Qnil);goto accept4;
  alt4_3:  ame_setpos(self,oldpos7); goto fail;
 accept4:;
 break;case 4:;   it=AmethystCore_anything(self ); FAILTEST(fail);
 bind_aset(bind,13/*autovar*/,it); int oldpos9=ame_getpos(self);
alt5_1: ame_setpos(self,oldpos9);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
 it=bind_aget(bind,13/*autovar*/);
 bind_aset(bind,14/*autovar*/,it); int oldpos10=ame_getpos(self); int oldlen5=ame_getlen(self); VALUE oldsrc5=ame_getsrc(self); int fail5=0;
ame_setsrc(self,bind_aget(bind,14/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeAmethystCTranslator,0)));
   it=AmethystCore_anything(self ); FAILTEST(pass5);
 bind_aset(bind,12/*name*/,it);   it=Amethyst_eof(self ); FAILTEST(pass5);
	goto success5;
	pass5: fail5=1;
	success5: ame_setsrc(self,oldsrc5); ame_setpos(self,oldpos10); ame_setlen(self,oldlen5);
	if(fail5) goto alt5_2;
it=rb_funcall(self,s_rbtrans_AmethystCTranslatorcb_2AmethystCTranslator,1,bind); 
 bind_aset(bind,3/*_result*/,it);  
ame_setcut(self,Qnil);goto accept5;
alt5_2: ame_setpos(self,oldpos9);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
 it=bind_aget(bind,13/*autovar*/);
 bind_aset(bind,3/*_result*/,it);  
ame_setcut(self,Qnil);goto accept5;
  alt5_3:  ame_setpos(self,oldpos9); goto fail;
 accept5:;
 break;case 5:;   it=AmethystCore_anything(self ); FAILTEST(fail);
 bind_aset(bind,15/*autovar*/,it); int oldpos11=ame_getpos(self);
alt6_1: ame_setpos(self,oldpos11);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
 it=bind_aget(bind,15/*autovar*/);
 bind_aset(bind,16/*autovar*/,it); int oldpos12=ame_getpos(self); int oldlen6=ame_getlen(self); VALUE oldsrc6=ame_getsrc(self); int fail6=0;
ame_setsrc(self,bind_aget(bind,16/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeAmethystCTranslator,0)));
 it=rb_ary_new3(0);
 bind_aset(bind,17/*autovar*/,it); int oldpos13; while(1){oldpos13=ame_getpos(self);   it=AmethystCore_anything(self ); FAILTEST(break1);
 bind_aset(bind,18/*autovar*/,it); it=rb_funcall(self,s_rbtrans_AmethystCTranslatorcb_3AmethystCTranslator,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos13=ame_getpos(self);goto break1;} } } break1: ame_setstop(self,Qnil);  ame_setpos(self,oldpos13); it=bind_aget(bind,17/*autovar*/);it=rb_funcall(self,s_rbtrans_AmethystCTranslatorcb_4AmethystCTranslator,1,bind); 
 bind_aset(bind,19/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass6);
	goto success6;
	pass6: fail6=1;
	success6: ame_setsrc(self,oldsrc6); ame_setpos(self,oldpos12); ame_setlen(self,oldlen6);
	if(fail6) goto alt6_2;
it=bind_aget(bind,19/*autovar*/);
 bind_aset(bind,3/*_result*/,it);  
ame_setcut(self,Qnil);goto accept6;
alt6_2: ame_setpos(self,oldpos11);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
 it=bind_aget(bind,15/*autovar*/);
 bind_aset(bind,3/*_result*/,it);  
ame_setcut(self,Qnil);goto accept6;
  alt6_3:  ame_setpos(self,oldpos11); goto fail;
 accept6:;
 break;case 6:;   it=AmethystCore_anything(self ); FAILTEST(fail);
 bind_aset(bind,20/*autovar*/,it); int oldpos14=ame_getpos(self);
alt7_1: ame_setpos(self,oldpos14);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
 it=bind_aget(bind,20/*autovar*/);
 bind_aset(bind,21/*autovar*/,it); int oldpos15=ame_getpos(self); int oldlen7=ame_getlen(self); VALUE oldsrc7=ame_getsrc(self); int fail7=0;
ame_setsrc(self,bind_aget(bind,21/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeAmethystCTranslator,0)));
 it=rb_funcall(self,s_rbtrans_AmethystCTranslatorcb_5AmethystCTranslator,1,bind); 
 bind_aset(bind,22/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass7);
	goto success7;
	pass7: fail7=1;
	success7: ame_setsrc(self,oldsrc7); ame_setpos(self,oldpos15); ame_setlen(self,oldlen7);
	if(fail7) goto alt7_2;
it=bind_aget(bind,22/*autovar*/);
 bind_aset(bind,3/*_result*/,it);  
ame_setcut(self,Qnil);goto accept7;
alt7_2: ame_setpos(self,oldpos14);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
 it=bind_aget(bind,20/*autovar*/);
 bind_aset(bind,3/*_result*/,it);  
ame_setcut(self,Qnil);goto accept7;
  alt7_3:  ame_setpos(self,oldpos14); goto fail;
 accept7:;
 break;case 7:;   it=AmethystCore_anything(self ); FAILTEST(fail);
 bind_aset(bind,3/*_result*/,it);  break;}it=bind_aget(bind,3/*_result*/);
return it;
fail: return failobj; }
VALUE AmethystCTranslator_rbtrans2(VALUE self ){VALUE vals[0]; VALUE bind=bind_new2(4);  int x;VALUE arg0,arg1,arg2,arg3;VALUE it;

it=rb_ary_new3(0);
 bind_aset(bind,0/*autovar*/,it); int oldpos1; while(1){oldpos1=ame_getpos(self);   it=AmethystCTranslator_rbtrans(self ); FAILTEST(break1);
 bind_aset(bind,1/*autovar*/,it); it=rb_funcall(self,s_rbtrans2_AmethystCTranslatorcb_1AmethystCTranslator,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos1=ame_getpos(self);goto break1;} } } break1: ame_setstop(self,Qnil);  ame_setpos(self,oldpos1); it=bind_aget(bind,0/*autovar*/);
 bind_aset(bind,2/*it*/,it); it=rb_funcall(self,s_rbtrans2_AmethystCTranslatorcb_2AmethystCTranslator,1,bind); 
 bind_aset(bind,3/*_result*/,it); it=bind_aget(bind,3/*_result*/);
return it;
fail: return failobj; }
VALUE AmethystCTranslator_rw(VALUE self ,VALUE a0,VALUE a1){VALUE vals[2]; VALUE bind=bind_new2(5); bind_aset(bind,1/*word*/,a0);bind_aset(bind,2/*prc*/,a1); int x;VALUE arg0,arg1,arg2,arg3;VALUE it;

it=rb_funcall(self,s_trans_AmethystCTranslatorcb_4AmethystCTranslator,1,bind); 
 bind_aset(bind,0/*rwo*/,it); it=rb_funcall(self,s_addlambda_AmethystCTranslatorcb_2AmethystCTranslator,1,bind);  it=bind_aget(bind,2/*prc*/); arg0=it; it=rb_funcall(self,s_applyAmethystCTranslator,1,arg0); FAILTEST(fail);
 bind_aset(bind,3/*x*/,it); it=rb_funcall(self,s_rw_AmethystCTranslatorcb_1AmethystCTranslator,1,bind); 
 bind_aset(bind,4/*_result*/,it); it=bind_aget(bind,4/*_result*/);
return it;
fail: return failobj; }
VALUE AmethystCTranslator_trans(VALUE self ){VALUE vals[0]; VALUE bind=bind_new2(88);  int x;VALUE arg0,arg1,arg2,arg3;VALUE it;

unsigned char chr1=FIX2LONG(rb_hash_aref(switchhashAmethystCTranslator1,rb_obj_class(ame_curobj(self))));  switch(chr1){case 0:;   it=AmethystCore_anything(self ); FAILTEST(fail);
 bind_aset(bind,0/*autovar*/,it); int oldpos1=ame_getpos(self); int oldlen1=ame_getlen(self); VALUE oldsrc1=ame_getsrc(self); int fail1=0;
ame_setsrc(self,bind_aget(bind,0/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeAmethystCTranslator,0)));
 it=rb_ary_new3(0);
 bind_aset(bind,1/*autovar*/,it); int oldpos2; while(1){oldpos2=ame_getpos(self);   it=AmethystCore_anything(self ); FAILTEST(break1);
 bind_aset(bind,2/*autovar*/,it); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_1AmethystCTranslator,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos2=ame_getpos(self);goto break1;} } } break1: ame_setstop(self,Qnil);  ame_setpos(self,oldpos2); it=bind_aget(bind,1/*autovar*/);
 bind_aset(bind,3/*it*/,it); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_2AmethystCTranslator,1,bind); 
 bind_aset(bind,4/*cbno*/,it); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_3AmethystCTranslator,1,bind); 
 bind_aset(bind,5/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass1);
	goto success1;
	pass1: fail1=1;
	success1: ame_setsrc(self,oldsrc1); ame_setpos(self,oldpos1); ame_setlen(self,oldlen1);
	if(fail1) goto fail;
it=bind_aget(bind,5/*autovar*/);
 bind_aset(bind,6/*_result*/,it);  break;case 10:;   it=AmethystCore_anything(self ); FAILTEST(fail);
 bind_aset(bind,7/*autovar*/,it); int oldpos3=ame_getpos(self); int oldlen2=ame_getlen(self); VALUE oldsrc2=ame_getsrc(self); int fail2=0;
ame_setsrc(self,bind_aget(bind,7/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeAmethystCTranslator,0)));
  it=rb_obj_clone(c_435); arg0=it; it=rb_funcall(self,s_labelAmethystCTranslator,1,arg0); FAILTEST(pass2);
 bind_aset(bind,8/*pass*/,it);  it=rb_obj_clone(c_436); arg0=it; it=rb_funcall(self,s_labelAmethystCTranslator,1,arg0); FAILTEST(pass2);
 bind_aset(bind,9/*oldpos*/,it);  it=rb_obj_clone(c_437); arg0=it; it=rb_funcall(self,s_labelAmethystCTranslator,1,arg0); FAILTEST(pass2);
 bind_aset(bind,10/*oldlen*/,it);  it=rb_obj_clone(c_438); arg0=it; it=rb_funcall(self,s_labelAmethystCTranslator,1,arg0); FAILTEST(pass2);
 bind_aset(bind,11/*oldsrc*/,it);  it=rb_obj_clone(c_439); arg0=it; it=rb_funcall(self,s_labelAmethystCTranslator,1,arg0); FAILTEST(pass2);
 bind_aset(bind,12/*success*/,it);  it=rb_obj_clone(c_440); arg0=it; it=rb_funcall(self,s_labelAmethystCTranslator,1,arg0); FAILTEST(pass2);
 bind_aset(bind,13/*fail*/,it); it=bind_aget(bind,8/*pass*/);
 bind_aset(bind,14/*word*/,it); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_4AmethystCTranslator,1,bind); 
 bind_aset(bind,15/*rwo*/,it); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_5AmethystCTranslator,1,bind); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_6AmethystCTranslator,1,bind); 
 bind_aset(bind,16/*autovar*/,it); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_7AmethystCTranslator,1,bind); int oldpos4=ame_getpos(self); int oldlen3=ame_getlen(self); VALUE oldsrc3=ame_getsrc(self); int fail3=0;
ame_setsrc(self,bind_aget(bind,16/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeAmethystCTranslator,0)));
   it=AmethystCTranslator_trans(self ); FAILTEST(pass3);
 bind_aset(bind,17/*to*/,it); 
 bind_aset(bind,18/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass3);
	goto success3;
	pass3: fail3=1;
	success3: ame_setsrc(self,oldsrc3); ame_setpos(self,oldpos4); ame_setlen(self,oldlen3);
	if(fail3) goto pass2;
it=bind_aget(bind,18/*autovar*/);
 bind_aset(bind,6/*_result*/,it); it=bind_aget(bind,6/*_result*/);
 bind_aset(bind,19/*x*/,it); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_8AmethystCTranslator,1,bind); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_9AmethystCTranslator,1,bind); 
 bind_aset(bind,20/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass2);
	goto success2;
	pass2: fail2=1;
	success2: ame_setsrc(self,oldsrc2); ame_setpos(self,oldpos3); ame_setlen(self,oldlen2);
	if(fail2) goto fail;
it=bind_aget(bind,20/*autovar*/);
 bind_aset(bind,6/*_result*/,it);  break;case 11:;   it=AmethystCore_anything(self ); FAILTEST(fail);
 bind_aset(bind,21/*autovar*/,it); int oldpos5=ame_getpos(self); int oldlen4=ame_getlen(self); VALUE oldsrc4=ame_getsrc(self); int fail4=0;
ame_setsrc(self,bind_aget(bind,21/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeAmethystCTranslator,0)));
 it=rb_funcall(self,s_trans_AmethystCTranslatorcb_10AmethystCTranslator,1,bind); 
 bind_aset(bind,23/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass4);
	goto success4;
	pass4: fail4=1;
	success4: ame_setsrc(self,oldsrc4); ame_setpos(self,oldpos5); ame_setlen(self,oldlen4);
	if(fail4) goto fail;
it=bind_aget(bind,23/*autovar*/);
 bind_aset(bind,6/*_result*/,it);  break;case 12:;   it=AmethystCore_anything(self ); FAILTEST(fail);
 bind_aset(bind,24/*autovar*/,it); int oldpos6=ame_getpos(self); int oldlen5=ame_getlen(self); VALUE oldsrc5=ame_getsrc(self); int fail5=0;
ame_setsrc(self,bind_aget(bind,24/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeAmethystCTranslator,0)));
 it=rb_funcall(self,s_trans_AmethystCTranslatorcb_11AmethystCTranslator,1,bind); 
 bind_aset(bind,25/*name*/,it); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_12AmethystCTranslator,1,bind); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_13AmethystCTranslator,1,bind); 
 bind_aset(bind,26/*autovar*/,it); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_14AmethystCTranslator,1,bind); int oldpos7=ame_getpos(self); int oldlen6=ame_getlen(self); VALUE oldsrc6=ame_getsrc(self); int fail6=0;
ame_setsrc(self,bind_aget(bind,26/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeAmethystCTranslator,0)));
   it=AmethystCTranslator_trans(self ); FAILTEST(pass6);
 bind_aset(bind,27/*body*/,it);   it=Amethyst_eof(self ); FAILTEST(pass6);
	goto success6;
	pass6: fail6=1;
	success6: ame_setsrc(self,oldsrc6); ame_setpos(self,oldpos7); ame_setlen(self,oldlen6);
	if(fail6) goto pass5;
it=rb_funcall(self,s_trans_AmethystCTranslatorcb_15AmethystCTranslator,1,bind); 
 bind_aset(bind,28/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass5);
	goto success5;
	pass5: fail5=1;
	success5: ame_setsrc(self,oldsrc5); ame_setpos(self,oldpos6); ame_setlen(self,oldlen5);
	if(fail5) goto fail;
it=bind_aget(bind,28/*autovar*/);
 bind_aset(bind,6/*_result*/,it);  break;case 13:;   it=AmethystCore_anything(self ); FAILTEST(fail);
 bind_aset(bind,29/*autovar*/,it); int oldpos8=ame_getpos(self); int oldlen7=ame_getlen(self); VALUE oldsrc7=ame_getsrc(self); int fail7=0;
ame_setsrc(self,bind_aget(bind,29/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeAmethystCTranslator,0)));
 it=rb_ary_new3(0);
 bind_aset(bind,30/*autovar*/,it); int oldpos9; while(1){oldpos9=ame_getpos(self);   it=AmethystCTranslator_trans(self ); FAILTEST(break2);
 bind_aset(bind,31/*autovar*/,it); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_16AmethystCTranslator,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos9=ame_getpos(self);goto break2;} } } break2: ame_setstop(self,Qnil);  ame_setpos(self,oldpos9); it=bind_aget(bind,30/*autovar*/);
 bind_aset(bind,32/*t*/,it); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_17AmethystCTranslator,1,bind); 
 bind_aset(bind,33/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass7);
	goto success7;
	pass7: fail7=1;
	success7: ame_setsrc(self,oldsrc7); ame_setpos(self,oldpos8); ame_setlen(self,oldlen7);
	if(fail7) goto fail;
it=bind_aget(bind,33/*autovar*/);
 bind_aset(bind,6/*_result*/,it);  break;case 14:;   it=AmethystCore_anything(self ); FAILTEST(fail);
 bind_aset(bind,34/*autovar*/,it); int oldpos10=ame_getpos(self); int oldlen8=ame_getlen(self); VALUE oldsrc8=ame_getsrc(self); int fail8=0;
ame_setsrc(self,bind_aget(bind,34/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeAmethystCTranslator,0)));
   it=Amethyst_eof(self ); FAILTEST(pass8);
	goto success8;
	pass8: fail8=1;
	success8: ame_setsrc(self,oldsrc8); ame_setpos(self,oldpos10); ame_setlen(self,oldlen8);
	if(fail8) goto fail;
it=rb_obj_clone(c_442);
 bind_aset(bind,6/*_result*/,it);  break;case 15:;   it=AmethystCore_anything(self ); FAILTEST(fail);
 bind_aset(bind,35/*autovar*/,it); int oldpos11=ame_getpos(self); int oldlen9=ame_getlen(self); VALUE oldsrc9=ame_getsrc(self); int fail9=0;
ame_setsrc(self,bind_aget(bind,35/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeAmethystCTranslator,0)));
  it=rb_obj_clone(c_443); arg0=it; it=rb_funcall(self,s_labelAmethystCTranslator,1,arg0); FAILTEST(pass9);
 bind_aset(bind,36/*chr*/,it); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_18AmethystCTranslator,1,bind); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_19AmethystCTranslator,1,bind); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_20AmethystCTranslator,1,bind); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_21AmethystCTranslator,1,bind); 
 bind_aset(bind,22/*s*/,it); it=rb_ary_new3(0);
 bind_aset(bind,37/*autovar*/,it); int oldpos12; while(1){oldpos12=ame_getpos(self);   it=AmethystCore_anything(self ); FAILTEST(break3);
 bind_aset(bind,38/*autovar*/,it); int oldpos13=ame_getpos(self); int oldlen10=ame_getlen(self); VALUE oldsrc10=ame_getsrc(self); int fail10=0;
ame_setsrc(self,bind_aget(bind,38/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeAmethystCTranslator,0)));
   it=AmethystCore_anything(self ); FAILTEST(pass10);
 bind_aset(bind,39/*c*/,it);   it=AmethystCTranslator_trans(self ); FAILTEST(pass10);
 bind_aset(bind,32/*t*/,it);   it=Amethyst_eof(self ); FAILTEST(pass10);
	goto success10;
	pass10: fail10=1;
	success10: ame_setsrc(self,oldsrc10); ame_setpos(self,oldpos13); ame_setlen(self,oldlen10);
	if(fail10) goto break3;
it=rb_funcall(self,s_trans_AmethystCTranslatorcb_22AmethystCTranslator,1,bind); 
 bind_aset(bind,40/*autovar*/,it); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_23AmethystCTranslator,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos12=ame_getpos(self);goto break3;} } } break3: ame_setstop(self,Qnil);  ame_setpos(self,oldpos12); it=bind_aget(bind,37/*autovar*/);it=rb_funcall(self,s_trans_AmethystCTranslatorcb_24AmethystCTranslator,1,bind); 
 bind_aset(bind,41/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass9);
	goto success9;
	pass9: fail9=1;
	success9: ame_setsrc(self,oldsrc9); ame_setpos(self,oldpos11); ame_setlen(self,oldlen9);
	if(fail9) goto fail;
it=bind_aget(bind,41/*autovar*/);
 bind_aset(bind,6/*_result*/,it);  break;case 16:;   it=Amethyst_fails(self ); FAILTEST(fail); break;case 1:;   it=AmethystCore_anything(self ); FAILTEST(fail);
 bind_aset(bind,42/*autovar*/,it); int oldpos14=ame_getpos(self);
alt1_1: ame_setpos(self,oldpos14);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
 it=bind_aget(bind,42/*autovar*/);
 bind_aset(bind,43/*autovar*/,it); int oldpos15=ame_getpos(self); int oldlen11=ame_getlen(self); VALUE oldsrc11=ame_getsrc(self); int fail11=0;
ame_setsrc(self,bind_aget(bind,43/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeAmethystCTranslator,0)));
   it=AmethystCore_anything(self ); FAILTEST(pass11);
 bind_aset(bind,44/*autovar*/,it); int oldpos16=ame_getpos(self); int oldlen12=ame_getlen(self); VALUE oldsrc12=ame_getsrc(self); int fail12=0;
ame_setsrc(self,bind_aget(bind,44/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeAmethystCTranslator,0)));
   it=Amethyst_spaces(self ); FAILTEST(pass12); it=rb_obj_clone(c_445); arg0=it; it=AmethystCore__seq(self ,arg0); FAILTEST(pass12);  it=Amethyst_eof(self ); FAILTEST(pass12);
	goto success12;
	pass12: fail12=1;
	success12: ame_setsrc(self,oldsrc12); ame_setpos(self,oldpos16); ame_setlen(self,oldlen12);
	if(fail12) goto pass11;
  it=Amethyst_eof(self ); FAILTEST(pass11);
	goto success11;
	pass11: fail11=1;
	success11: ame_setsrc(self,oldsrc11); ame_setpos(self,oldpos15); ame_setlen(self,oldlen11);
	if(fail11) goto alt1_2;
it=rb_obj_clone(c_446);
 bind_aset(bind,6/*_result*/,it);  
ame_setcut(self,Qnil);goto accept1;
alt1_2: ame_setpos(self,oldpos14);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
 it=bind_aget(bind,42/*autovar*/);
 bind_aset(bind,45/*autovar*/,it); int oldpos17=ame_getpos(self); int oldlen13=ame_getlen(self); VALUE oldsrc13=ame_getsrc(self); int fail13=0;
ame_setsrc(self,bind_aget(bind,45/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeAmethystCTranslator,0)));
   it=AmethystCore_anything(self ); FAILTEST(pass13);
 bind_aset(bind,25/*name*/,it); it=c_447;
 bind_aset(bind,46/*ii*/,it); it=rb_ary_new3(0);
 bind_aset(bind,47/*autovar*/,it); int oldpos18; while(1){oldpos18=ame_getpos(self);   it=AmethystCTranslator_trans(self ); FAILTEST(break4);
 bind_aset(bind,48/*aa*/,it); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_25AmethystCTranslator,1,bind); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_26AmethystCTranslator,1,bind); 
 bind_aset(bind,49/*autovar*/,it); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_27AmethystCTranslator,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos18=ame_getpos(self);goto break4;} } } break4: ame_setstop(self,Qnil);  ame_setpos(self,oldpos18); it=bind_aget(bind,47/*autovar*/);
 bind_aset(bind,50/*args*/,it); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_28AmethystCTranslator,1,bind); 
 bind_aset(bind,51/*s*/,it); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_29AmethystCTranslator,1,bind); 
 bind_aset(bind,52/*_result*/,it); it=bind_aget(bind,52/*_result*/);
 bind_aset(bind,53/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass13);
	goto success13;
	pass13: fail13=1;
	success13: ame_setsrc(self,oldsrc13); ame_setpos(self,oldpos17); ame_setlen(self,oldlen13);
	if(fail13) goto alt1_3;
it=bind_aget(bind,53/*autovar*/);
 bind_aset(bind,6/*_result*/,it);  
ame_setcut(self,Qnil);goto accept1;
  alt1_3:  ame_setpos(self,oldpos14); goto fail;
 accept1:;
 break;case 2:;   it=AmethystCore_anything(self ); FAILTEST(fail);
 bind_aset(bind,54/*autovar*/,it); int oldpos19=ame_getpos(self); int oldlen14=ame_getlen(self); VALUE oldsrc14=ame_getsrc(self); int fail14=0;
ame_setsrc(self,bind_aget(bind,54/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeAmethystCTranslator,0)));
   it=AmethystCTranslator_trans(self ); FAILTEST(pass14);
 bind_aset(bind,55/*e*/,it); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_30AmethystCTranslator,1,bind); 
 bind_aset(bind,56/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass14);
	goto success14;
	pass14: fail14=1;
	success14: ame_setsrc(self,oldsrc14); ame_setpos(self,oldpos19); ame_setlen(self,oldlen14);
	if(fail14) goto fail;
it=bind_aget(bind,56/*autovar*/);
 bind_aset(bind,6/*_result*/,it);  break;case 3:;   it=AmethystCore_anything(self ); FAILTEST(fail);
 bind_aset(bind,57/*autovar*/,it); int oldpos20=ame_getpos(self); int oldlen15=ame_getlen(self); VALUE oldsrc15=ame_getsrc(self); int fail15=0;
ame_setsrc(self,bind_aget(bind,57/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeAmethystCTranslator,0)));
 it=rb_ary_new3(0);
 bind_aset(bind,58/*autovar*/,it); int oldpos21; while(1){oldpos21=ame_getpos(self);   it=AmethystCore_anything(self ); FAILTEST(break5);
 bind_aset(bind,59/*autovar*/,it); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_31AmethystCTranslator,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos21=ame_getpos(self);goto break5;} } } break5: ame_setstop(self,Qnil);  ame_setpos(self,oldpos21); it=bind_aget(bind,58/*autovar*/);it=rb_funcall(self,s_trans_AmethystCTranslatorcb_32AmethystCTranslator,1,bind); 
 bind_aset(bind,60/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass15);
	goto success15;
	pass15: fail15=1;
	success15: ame_setsrc(self,oldsrc15); ame_setpos(self,oldpos20); ame_setlen(self,oldlen15);
	if(fail15) goto fail;
it=bind_aget(bind,60/*autovar*/);
 bind_aset(bind,6/*_result*/,it);  break;case 4:;   it=AmethystCore_anything(self ); FAILTEST(fail);
 bind_aset(bind,61/*autovar*/,it); int oldpos22=ame_getpos(self); int oldlen16=ame_getlen(self); VALUE oldsrc16=ame_getsrc(self); int fail16=0;
ame_setsrc(self,bind_aget(bind,61/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeAmethystCTranslator,0)));
   it=Amethyst_eof(self ); FAILTEST(pass16);
	goto success16;
	pass16: fail16=1;
	success16: ame_setsrc(self,oldsrc16); ame_setpos(self,oldpos22); ame_setlen(self,oldlen16);
	if(fail16) goto fail;
it=rb_obj_clone(c_450);
 bind_aset(bind,6/*_result*/,it);  break;case 5:;   it=AmethystCore_anything(self ); FAILTEST(fail);
 bind_aset(bind,62/*autovar*/,it); int oldpos23=ame_getpos(self); int oldlen17=ame_getlen(self); VALUE oldsrc17=ame_getsrc(self); int fail17=0;
ame_setsrc(self,bind_aget(bind,62/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeAmethystCTranslator,0)));
 it=rb_funcall(self,s_trans_AmethystCTranslatorcb_33AmethystCTranslator,1,bind); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_34AmethystCTranslator,1,bind); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_35AmethystCTranslator,1,bind); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_36AmethystCTranslator,1,bind); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_37AmethystCTranslator,1,bind); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_38AmethystCTranslator,1,bind); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_39AmethystCTranslator,1,bind); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_40AmethystCTranslator,1,bind); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_41AmethystCTranslator,1,bind); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_42AmethystCTranslator,1,bind); 
 bind_aset(bind,63/*autovar*/,it); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_43AmethystCTranslator,1,bind); int oldpos24=ame_getpos(self); int oldlen18=ame_getlen(self); VALUE oldsrc18=ame_getsrc(self); int fail18=0;
ame_setsrc(self,bind_aget(bind,63/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeAmethystCTranslator,0)));
   it=AmethystCore_anything(self ); FAILTEST(pass18);
 bind_aset(bind,64/*autovar*/,it); int oldpos25=ame_getpos(self); int oldlen19=ame_getlen(self); VALUE oldsrc19=ame_getsrc(self); int fail19=0;
ame_setsrc(self,bind_aget(bind,64/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeAmethystCTranslator,0)));
 it=rb_ary_new3(0);
 bind_aset(bind,65/*autovar*/,it); int oldpos26; while(1){oldpos26=ame_getpos(self);   it=AmethystCTranslator_trans(self ); FAILTEST(break6);
 bind_aset(bind,66/*autovar*/,it); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_44AmethystCTranslator,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos26=ame_getpos(self);goto break6;} } } break6: ame_setstop(self,Qnil);  ame_setpos(self,oldpos26); it=bind_aget(bind,65/*autovar*/);
 bind_aset(bind,67/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass19);
	goto success19;
	pass19: fail19=1;
	success19: ame_setsrc(self,oldsrc19); ame_setpos(self,oldpos25); ame_setlen(self,oldlen19);
	if(fail19) goto pass18;
it=bind_aget(bind,67/*autovar*/);
 bind_aset(bind,32/*t*/,it);   it=Amethyst_eof(self ); FAILTEST(pass18);
	goto success18;
	pass18: fail18=1;
	success18: ame_setsrc(self,oldsrc18); ame_setpos(self,oldpos24); ame_setlen(self,oldlen18);
	if(fail18) goto pass17;
  it=AmethystCTranslator_rbcode(self ); FAILTEST(pass17);
 bind_aset(bind,68/*rbcode*/,it); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_45AmethystCTranslator,1,bind); 
 bind_aset(bind,22/*s*/,it); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_46AmethystCTranslator,1,bind); 
 bind_aset(bind,69/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass17);
	goto success17;
	pass17: fail17=1;
	success17: ame_setsrc(self,oldsrc17); ame_setpos(self,oldpos23); ame_setlen(self,oldlen17);
	if(fail17) goto fail;
it=bind_aget(bind,69/*autovar*/);
 bind_aset(bind,6/*_result*/,it);  break;case 6:;   it=AmethystCore_anything(self ); FAILTEST(fail);
 bind_aset(bind,70/*autovar*/,it); int oldpos27=ame_getpos(self); int oldlen20=ame_getlen(self); VALUE oldsrc20=ame_getsrc(self); int fail20=0;
ame_setsrc(self,bind_aget(bind,70/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeAmethystCTranslator,0)));
 it=rb_ary_new3(0);
 bind_aset(bind,71/*autovar*/,it); int oldpos28; while(1){oldpos28=ame_getpos(self);   it=AmethystCore_anything(self ); FAILTEST(break7);
 bind_aset(bind,72/*autovar*/,it); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_47AmethystCTranslator,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos28=ame_getpos(self);goto break7;} } } break7: ame_setstop(self,Qnil);  ame_setpos(self,oldpos28); it=bind_aget(bind,71/*autovar*/);it=rb_funcall(self,s_trans_AmethystCTranslatorcb_48AmethystCTranslator,1,bind); 
 bind_aset(bind,73/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass20);
	goto success20;
	pass20: fail20=1;
	success20: ame_setsrc(self,oldsrc20); ame_setpos(self,oldpos27); ame_setlen(self,oldlen20);
	if(fail20) goto fail;
it=bind_aget(bind,73/*autovar*/);
 bind_aset(bind,6/*_result*/,it);  break;case 7:;   it=AmethystCore_anything(self ); FAILTEST(fail);
 bind_aset(bind,74/*autovar*/,it); int oldpos29=ame_getpos(self); int oldlen21=ame_getlen(self); VALUE oldsrc21=ame_getsrc(self); int fail21=0;
ame_setsrc(self,bind_aget(bind,74/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeAmethystCTranslator,0)));
 it=rb_funcall(self,s_trans_AmethystCTranslatorcb_49AmethystCTranslator,1,bind); 
 bind_aset(bind,75/*accept*/,it); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_50AmethystCTranslator,1,bind); 
 bind_aset(bind,76/*reject*/,it); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_51AmethystCTranslator,1,bind); 
 bind_aset(bind,9/*oldpos*/,it); it=bind_aget(bind,76/*reject*/);
 bind_aset(bind,14/*word*/,it); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_4AmethystCTranslator,1,bind); 
 bind_aset(bind,15/*rwo*/,it); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_5AmethystCTranslator,1,bind);   it=AmethystCTranslator_trans(self ); FAILTEST(pass21);
 bind_aset(bind,32/*t*/,it); 
 bind_aset(bind,6/*_result*/,it); it=bind_aget(bind,6/*_result*/);
 bind_aset(bind,19/*x*/,it); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_8AmethystCTranslator,1,bind); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_52AmethystCTranslator,1,bind); 
 bind_aset(bind,77/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass21);
	goto success21;
	pass21: fail21=1;
	success21: ame_setsrc(self,oldsrc21); ame_setpos(self,oldpos29); ame_setlen(self,oldlen21);
	if(fail21) goto fail;
it=bind_aget(bind,77/*autovar*/);
 bind_aset(bind,6/*_result*/,it);  break;case 8:;   it=AmethystCore_anything(self ); FAILTEST(fail);
 bind_aset(bind,78/*autovar*/,it); int oldpos30=ame_getpos(self); int oldlen22=ame_getlen(self); VALUE oldsrc22=ame_getsrc(self); int fail22=0;
ame_setsrc(self,bind_aget(bind,78/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeAmethystCTranslator,0)));
 it=rb_funcall(self,s_trans_AmethystCTranslatorcb_53AmethystCTranslator,1,bind); 
 bind_aset(bind,79/*brk*/,it); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_51AmethystCTranslator,1,bind); 
 bind_aset(bind,9/*oldpos*/,it); it=bind_aget(bind,79/*brk*/);
 bind_aset(bind,14/*word*/,it); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_4AmethystCTranslator,1,bind); 
 bind_aset(bind,15/*rwo*/,it); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_5AmethystCTranslator,1,bind);   it=AmethystCTranslator_trans(self ); FAILTEST(pass22);
 bind_aset(bind,32/*t*/,it); 
 bind_aset(bind,6/*_result*/,it); it=bind_aget(bind,6/*_result*/);
 bind_aset(bind,19/*x*/,it); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_8AmethystCTranslator,1,bind); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_54AmethystCTranslator,1,bind); 
 bind_aset(bind,80/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass22);
	goto success22;
	pass22: fail22=1;
	success22: ame_setsrc(self,oldsrc22); ame_setpos(self,oldpos30); ame_setlen(self,oldlen22);
	if(fail22) goto fail;
it=bind_aget(bind,80/*autovar*/);
 bind_aset(bind,6/*_result*/,it);  break;case 9:;   it=AmethystCore_anything(self ); FAILTEST(fail);
 bind_aset(bind,81/*autovar*/,it); int oldpos31=ame_getpos(self); int oldlen23=ame_getlen(self); VALUE oldsrc23=ame_getsrc(self); int fail23=0;
ame_setsrc(self,bind_aget(bind,81/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeAmethystCTranslator,0)));
 it=rb_funcall(self,s_trans_AmethystCTranslatorcb_49AmethystCTranslator,1,bind); 
 bind_aset(bind,75/*accept*/,it); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_4AmethystCTranslator,1,bind); 
 bind_aset(bind,13/*fail*/,it); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_51AmethystCTranslator,1,bind); 
 bind_aset(bind,9/*oldpos*/,it);  it=rb_obj_clone(c_453); arg0=it; it=rb_funcall(self,s_labelAmethystCTranslator,1,arg0); FAILTEST(pass23);
 bind_aset(bind,82/*alt*/,it); it=c_454;
 bind_aset(bind,83/*altno*/,it); it=rb_ary_new3(0);
 bind_aset(bind,84/*autovar*/,it); int oldpos32; while(1){oldpos32=ame_getpos(self); int oldpos33=ame_getpos(self);
   it=AmethystCore_anything(self ); FAILTEST(reject1); x=1; goto accept2;  reject1: x=0; accept2: it=Qnil; ame_setpos(self,oldpos33); if (x==0) goto break8;it=rb_funcall(self,s_trans_AmethystCTranslatorcb_55AmethystCTranslator,1,bind); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_56AmethystCTranslator,1,bind); 
 bind_aset(bind,14/*word*/,it); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_4AmethystCTranslator,1,bind); 
 bind_aset(bind,15/*rwo*/,it); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_5AmethystCTranslator,1,bind);   it=AmethystCTranslator_trans(self ); FAILTEST(break8);
 bind_aset(bind,6/*_result*/,it); it=bind_aget(bind,6/*_result*/);
 bind_aset(bind,19/*x*/,it); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_8AmethystCTranslator,1,bind); 
 bind_aset(bind,85/*_result*/,it); it=bind_aget(bind,85/*_result*/);
 bind_aset(bind,86/*autovar*/,it); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_57AmethystCTranslator,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos32=ame_getpos(self);goto break8;} } } break8: ame_setstop(self,Qnil);  ame_setpos(self,oldpos32); it=bind_aget(bind,84/*autovar*/);
 bind_aset(bind,32/*t*/,it); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_58AmethystCTranslator,1,bind); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_59AmethystCTranslator,1,bind); it=rb_funcall(self,s_trans_AmethystCTranslatorcb_60AmethystCTranslator,1,bind); 
 bind_aset(bind,87/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass23);
	goto success23;
	pass23: fail23=1;
	success23: ame_setsrc(self,oldsrc23); ame_setpos(self,oldpos31); ame_setlen(self,oldlen23);
	if(fail23) goto fail;
it=bind_aget(bind,87/*autovar*/);
 bind_aset(bind,6/*_result*/,it);  break;}it=bind_aget(bind,6/*_result*/);
return it;
fail: return failobj; }
void Init_ctranslator2_c(){ 
 cls_AmethystCTranslator=rb_define_class("AmethystCTranslator",rb_const_get(rb_cObject,rb_intern("Amethyst"))); 
failobj=rb_eval_string("FAIL");
c_435=rb_str_new2("pass");rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),c_435);
c_436=rb_str_new2("oldpos");rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),c_436);
c_437=rb_str_new2("oldlen");rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),c_437);
c_438=rb_str_new2("oldsrc");rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),c_438);
c_439=rb_str_new2("success");rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),c_439);
c_440=rb_str_new2("fail");rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),c_440);
c_442=rb_str_new2("ame_setstop(self,Qtrue);");rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),c_442);
c_443=rb_str_new2("chr");rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),c_443);
c_445=rb_str_new2("_find");rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),c_445);
c_446=rb_str_new2("_find");rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),c_446);
c_447=rb_funcall(rb_str_new2("0"),rb_intern("to_i"),0);rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),c_447);
c_450=rb_str_new2("ame_setcut(self,Qtrue);");rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),c_450);
c_453=rb_str_new2("alt");rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),c_453);
c_454=rb_funcall(rb_str_new2("0"),rb_intern("to_i"),0);rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),c_454);
c_456=rb_str_new2("fail");rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),c_456);
s_add_c_global_AmethystCTranslatorcb_1AmethystCTranslator=rb_intern("add_c_global_AmethystCTranslatorcb_1");
s_addcallback_AmethystCTranslatorcb_1AmethystCTranslator=rb_intern("addcallback_AmethystCTranslatorcb_1");
s_addlambda_AmethystCTranslatorcb_1AmethystCTranslator=rb_intern("addlambda_AmethystCTranslatorcb_1");
s_addlambda_AmethystCTranslatorcb_2AmethystCTranslator=rb_intern("addlambda_AmethystCTranslatorcb_2");
s_addlambda_AmethystCTranslatorcb_3AmethystCTranslator=rb_intern("addlambda_AmethystCTranslatorcb_3");
s_addlambda_AmethystCTranslatorcb_4AmethystCTranslator=rb_intern("addlambda_AmethystCTranslatorcb_4");
s_addlambda_AmethystCTranslatorcb_5AmethystCTranslator=rb_intern("addlambda_AmethystCTranslatorcb_5");
s_applyAmethystCTranslator=rb_intern("apply");
s_failwrap_AmethystCTranslatorcb_1AmethystCTranslator=rb_intern("failwrap_AmethystCTranslatorcb_1");
s_itrans_AmethystCTranslatorcb_1AmethystCTranslator=rb_intern("itrans_AmethystCTranslatorcb_1");
s_itrans_AmethystCTranslatorcb_2AmethystCTranslator=rb_intern("itrans_AmethystCTranslatorcb_2");
s_itrans_AmethystCTranslatorcb_3AmethystCTranslator=rb_intern("itrans_AmethystCTranslatorcb_3");
s_itrans_AmethystCTranslatorcb_4AmethystCTranslator=rb_intern("itrans_AmethystCTranslatorcb_4");
s_itrans_AmethystCTranslatorcb_5AmethystCTranslator=rb_intern("itrans_AmethystCTranslatorcb_5");
s_labelAmethystCTranslator=rb_intern("label");
s_rbcode_AmethystCTranslatorcb_1AmethystCTranslator=rb_intern("rbcode_AmethystCTranslatorcb_1");
s_rbcode_AmethystCTranslatorcb_2AmethystCTranslator=rb_intern("rbcode_AmethystCTranslatorcb_2");
s_rbcode_AmethystCTranslatorcb_3AmethystCTranslator=rb_intern("rbcode_AmethystCTranslatorcb_3");
s_rbcode_AmethystCTranslatorcb_4AmethystCTranslator=rb_intern("rbcode_AmethystCTranslatorcb_4");
s_rbcode_AmethystCTranslatorcb_5AmethystCTranslator=rb_intern("rbcode_AmethystCTranslatorcb_5");
s_rbcode_AmethystCTranslatorcb_6AmethystCTranslator=rb_intern("rbcode_AmethystCTranslatorcb_6");
s_rbcode_AmethystCTranslatorcb_7AmethystCTranslator=rb_intern("rbcode_AmethystCTranslatorcb_7");
s_rbtrans2_AmethystCTranslatorcb_1AmethystCTranslator=rb_intern("rbtrans2_AmethystCTranslatorcb_1");
s_rbtrans2_AmethystCTranslatorcb_2AmethystCTranslator=rb_intern("rbtrans2_AmethystCTranslatorcb_2");
s_rbtrans_AmethystCTranslatorcb_1AmethystCTranslator=rb_intern("rbtrans_AmethystCTranslatorcb_1");
s_rbtrans_AmethystCTranslatorcb_2AmethystCTranslator=rb_intern("rbtrans_AmethystCTranslatorcb_2");
s_rbtrans_AmethystCTranslatorcb_3AmethystCTranslator=rb_intern("rbtrans_AmethystCTranslatorcb_3");
s_rbtrans_AmethystCTranslatorcb_4AmethystCTranslator=rb_intern("rbtrans_AmethystCTranslatorcb_4");
s_rbtrans_AmethystCTranslatorcb_5AmethystCTranslator=rb_intern("rbtrans_AmethystCTranslatorcb_5");
s_rw_AmethystCTranslatorcb_1AmethystCTranslator=rb_intern("rw_AmethystCTranslatorcb_1");
s_sizeAmethystCTranslator=rb_intern("size");
s_trans_AmethystCTranslatorcb_10AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_10");
s_trans_AmethystCTranslatorcb_11AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_11");
s_trans_AmethystCTranslatorcb_12AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_12");
s_trans_AmethystCTranslatorcb_13AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_13");
s_trans_AmethystCTranslatorcb_14AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_14");
s_trans_AmethystCTranslatorcb_15AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_15");
s_trans_AmethystCTranslatorcb_16AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_16");
s_trans_AmethystCTranslatorcb_17AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_17");
s_trans_AmethystCTranslatorcb_18AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_18");
s_trans_AmethystCTranslatorcb_19AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_19");
s_trans_AmethystCTranslatorcb_1AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_1");
s_trans_AmethystCTranslatorcb_20AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_20");
s_trans_AmethystCTranslatorcb_21AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_21");
s_trans_AmethystCTranslatorcb_22AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_22");
s_trans_AmethystCTranslatorcb_23AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_23");
s_trans_AmethystCTranslatorcb_24AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_24");
s_trans_AmethystCTranslatorcb_25AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_25");
s_trans_AmethystCTranslatorcb_26AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_26");
s_trans_AmethystCTranslatorcb_27AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_27");
s_trans_AmethystCTranslatorcb_28AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_28");
s_trans_AmethystCTranslatorcb_29AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_29");
s_trans_AmethystCTranslatorcb_2AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_2");
s_trans_AmethystCTranslatorcb_30AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_30");
s_trans_AmethystCTranslatorcb_31AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_31");
s_trans_AmethystCTranslatorcb_32AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_32");
s_trans_AmethystCTranslatorcb_33AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_33");
s_trans_AmethystCTranslatorcb_34AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_34");
s_trans_AmethystCTranslatorcb_35AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_35");
s_trans_AmethystCTranslatorcb_36AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_36");
s_trans_AmethystCTranslatorcb_37AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_37");
s_trans_AmethystCTranslatorcb_38AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_38");
s_trans_AmethystCTranslatorcb_39AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_39");
s_trans_AmethystCTranslatorcb_3AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_3");
s_trans_AmethystCTranslatorcb_40AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_40");
s_trans_AmethystCTranslatorcb_41AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_41");
s_trans_AmethystCTranslatorcb_42AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_42");
s_trans_AmethystCTranslatorcb_43AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_43");
s_trans_AmethystCTranslatorcb_44AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_44");
s_trans_AmethystCTranslatorcb_45AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_45");
s_trans_AmethystCTranslatorcb_46AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_46");
s_trans_AmethystCTranslatorcb_47AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_47");
s_trans_AmethystCTranslatorcb_48AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_48");
s_trans_AmethystCTranslatorcb_49AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_49");
s_trans_AmethystCTranslatorcb_4AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_4");
s_trans_AmethystCTranslatorcb_50AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_50");
s_trans_AmethystCTranslatorcb_51AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_51");
s_trans_AmethystCTranslatorcb_52AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_52");
s_trans_AmethystCTranslatorcb_53AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_53");
s_trans_AmethystCTranslatorcb_54AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_54");
s_trans_AmethystCTranslatorcb_55AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_55");
s_trans_AmethystCTranslatorcb_56AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_56");
s_trans_AmethystCTranslatorcb_57AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_57");
s_trans_AmethystCTranslatorcb_58AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_58");
s_trans_AmethystCTranslatorcb_59AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_59");
s_trans_AmethystCTranslatorcb_5AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_5");
s_trans_AmethystCTranslatorcb_60AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_60");
s_trans_AmethystCTranslatorcb_6AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_6");
s_trans_AmethystCTranslatorcb_7AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_7");
s_trans_AmethystCTranslatorcb_8AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_8");
s_trans_AmethystCTranslatorcb_9AmethystCTranslator=rb_intern("trans_AmethystCTranslatorcb_9");
switchhashAmethystCTranslator1=rb_eval_string("Hash.new{|h,k|\nnext h[k]=0 if k<=Act\nnext h[k]=1 if k<=Apply\nnext h[k]=2 if k<=Bind\nnext h[k]=3 if k<=CAct\nnext h[k]=4 if k<=Cut\nnext h[k]=5 if k<=Grammar\nnext h[k]=6 if k<=Local\nnext h[k]=7 if k<=Lookahead\nnext h[k]=8 if k<=Many\nnext h[k]=9 if k<=Or\nnext h[k]=10 if k<=Pass\nnext h[k]=11 if k<=Result\nnext h[k]=12 if k<=Rule\nnext h[k]=13 if k<=Seq\nnext h[k]=14 if k<=Stop\nnext h[k]=15 if k<=Switch\nnext h[k]=16 if k<=Object\n}\n");rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),switchhashAmethystCTranslator1);
switchhashAmethystCTranslator2=rb_eval_string("Hash.new{|h,k|\nnext h[k]=0 if k<=Args\nnext h[k]=1 if k<=Array\nnext h[k]=2 if k<=Exp\nnext h[k]=3 if k<=Global\nnext h[k]=4 if k<=Key\nnext h[k]=5 if k<=Local\nnext h[k]=6 if k<=Result\nnext h[k]=7 if k<=Object\n}\n");rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),switchhashAmethystCTranslator2);
rb_define_method(cls_AmethystCTranslator,"add_c_global",AmethystCTranslator_add_c_global,2);
rb_define_method(cls_AmethystCTranslator,"addcallback",AmethystCTranslator_addcallback,1);
rb_define_method(cls_AmethystCTranslator,"addlambda",AmethystCTranslator_addlambda,0);
rb_define_method(cls_AmethystCTranslator,"failwrap",AmethystCTranslator_failwrap,1);
rb_define_method(cls_AmethystCTranslator,"itrans",AmethystCTranslator_itrans,0);
rb_define_method(cls_AmethystCTranslator,"rbcode",AmethystCTranslator_rbcode,0);
rb_define_method(cls_AmethystCTranslator,"rbtrans",AmethystCTranslator_rbtrans,0);
rb_define_method(cls_AmethystCTranslator,"rbtrans2",AmethystCTranslator_rbtrans2,0);
rb_define_method(cls_AmethystCTranslator,"rw",AmethystCTranslator_rw,2);
rb_define_method(cls_AmethystCTranslator,"trans",AmethystCTranslator_trans,0);
 rb_eval_string("testversionctranslator2('e71dec59b45ca507bcf38a8fa541e61a')");}
