#include "cthyst.h"
VALUE cls_Dataflow;
VALUE AmethystCore_anything(VALUE self );
VALUE Amethyst_clas(VALUE self ,VALUE);
VALUE Amethyst_eof(VALUE self );
VALUE Amethyst_fails(VALUE self );
VALUE Dataflow_root(VALUE self );
VALUE Dataflow_traverse(VALUE self );
VALUE Dataflow_traverse_item(VALUE self );
VALUE Dataflow_vars_in(VALUE self );
VALUE Dataflow_visit(VALUE self );
VALUE switchhashDataflow1;
VALUE switchhashDataflow2;
VALUE switchhashDataflow3;
static VALUE c_252;
static VALUE s_root_Dataflowcb_10Dataflow;
static VALUE s_root_Dataflowcb_11Dataflow;
static VALUE s_root_Dataflowcb_1Dataflow;
static VALUE s_root_Dataflowcb_2Dataflow;
static VALUE s_root_Dataflowcb_3Dataflow;
static VALUE s_root_Dataflowcb_4Dataflow;
static VALUE s_root_Dataflowcb_5Dataflow;
static VALUE s_root_Dataflowcb_6Dataflow;
static VALUE s_root_Dataflowcb_7Dataflow;
static VALUE s_root_Dataflowcb_8Dataflow;
static VALUE s_root_Dataflowcb_9Dataflow;
static VALUE s_sizeDataflow;
static VALUE s_traverse_Dataflowcb_1Dataflow;
static VALUE s_traverse_Dataflowcb_2Dataflow;
static VALUE s_traverse_Dataflowcb_3Dataflow;
static VALUE s_traverse_Dataflowcb_4Dataflow;
static VALUE s_traverse_Dataflowcb_5Dataflow;
static VALUE s_traverse_Dataflowcb_6Dataflow;
static VALUE s_traverse_Dataflowcb_7Dataflow;
static VALUE s_traverse_Dataflowcb_8Dataflow;
static VALUE s_traverse_item_Dataflowcb_1Dataflow;
static VALUE s_traverse_item_Dataflowcb_2Dataflow;
static VALUE s_traverse_item_Dataflowcb_3Dataflow;
static VALUE s_vars_in_Dataflowcb_10Dataflow;
static VALUE s_vars_in_Dataflowcb_11Dataflow;
static VALUE s_vars_in_Dataflowcb_12Dataflow;
static VALUE s_vars_in_Dataflowcb_13Dataflow;
static VALUE s_vars_in_Dataflowcb_14Dataflow;
static VALUE s_vars_in_Dataflowcb_1Dataflow;
static VALUE s_vars_in_Dataflowcb_2Dataflow;
static VALUE s_vars_in_Dataflowcb_3Dataflow;
static VALUE s_vars_in_Dataflowcb_4Dataflow;
static VALUE s_vars_in_Dataflowcb_5Dataflow;
static VALUE s_vars_in_Dataflowcb_6Dataflow;
static VALUE s_vars_in_Dataflowcb_7Dataflow;
static VALUE s_vars_in_Dataflowcb_8Dataflow;
static VALUE s_vars_in_Dataflowcb_9Dataflow;
static VALUE s_visit_Dataflowcb_10Dataflow;
static VALUE s_visit_Dataflowcb_11Dataflow;
static VALUE s_visit_Dataflowcb_12Dataflow;
static VALUE s_visit_Dataflowcb_13Dataflow;
static VALUE s_visit_Dataflowcb_14Dataflow;
static VALUE s_visit_Dataflowcb_15Dataflow;
static VALUE s_visit_Dataflowcb_16Dataflow;
static VALUE s_visit_Dataflowcb_17Dataflow;
static VALUE s_visit_Dataflowcb_18Dataflow;
static VALUE s_visit_Dataflowcb_19Dataflow;
static VALUE s_visit_Dataflowcb_1Dataflow;
static VALUE s_visit_Dataflowcb_20Dataflow;
static VALUE s_visit_Dataflowcb_21Dataflow;
static VALUE s_visit_Dataflowcb_22Dataflow;
static VALUE s_visit_Dataflowcb_23Dataflow;
static VALUE s_visit_Dataflowcb_24Dataflow;
static VALUE s_visit_Dataflowcb_25Dataflow;
static VALUE s_visit_Dataflowcb_26Dataflow;
static VALUE s_visit_Dataflowcb_27Dataflow;
static VALUE s_visit_Dataflowcb_28Dataflow;
static VALUE s_visit_Dataflowcb_29Dataflow;
static VALUE s_visit_Dataflowcb_2Dataflow;
static VALUE s_visit_Dataflowcb_30Dataflow;
static VALUE s_visit_Dataflowcb_31Dataflow;
static VALUE s_visit_Dataflowcb_32Dataflow;
static VALUE s_visit_Dataflowcb_33Dataflow;
static VALUE s_visit_Dataflowcb_34Dataflow;
static VALUE s_visit_Dataflowcb_35Dataflow;
static VALUE s_visit_Dataflowcb_36Dataflow;
static VALUE s_visit_Dataflowcb_37Dataflow;
static VALUE s_visit_Dataflowcb_38Dataflow;
static VALUE s_visit_Dataflowcb_39Dataflow;
static VALUE s_visit_Dataflowcb_3Dataflow;
static VALUE s_visit_Dataflowcb_40Dataflow;
static VALUE s_visit_Dataflowcb_41Dataflow;
static VALUE s_visit_Dataflowcb_4Dataflow;
static VALUE s_visit_Dataflowcb_5Dataflow;
static VALUE s_visit_Dataflowcb_6Dataflow;
static VALUE s_visit_Dataflowcb_7Dataflow;
static VALUE s_visit_Dataflowcb_8Dataflow;
static VALUE s_visit_Dataflowcb_9Dataflow;
VALUE Dataflow_root(VALUE self ){VALUE vals[0]; VALUE bind=bind_new2(13);  int x;VALUE arg0,arg1,arg2,arg3;VALUE it;

it=rb_funcall(self,s_root_Dataflowcb_1Dataflow,1,bind); 
 bind_aset(bind,0/*autovar*/,it); it=rb_funcall(self,s_root_Dataflowcb_2Dataflow,1,bind); int oldpos1=ame_getpos(self); int oldlen1=ame_getlen(self); VALUE oldsrc1=ame_getsrc(self); int fail1=0;
ame_setsrc(self,bind_aget(bind,0/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDataflow,0)));
  it=c_252; arg0=it; it=Amethyst_clas(self ,arg0); FAILTEST(pass1);
 bind_aset(bind,1/*autovar*/,it); int oldpos2=ame_getpos(self); int oldlen2=ame_getlen(self); VALUE oldsrc2=ame_getsrc(self); int fail2=0;
ame_setsrc(self,bind_aget(bind,1/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDataflow,0)));
 it=rb_funcall(self,s_root_Dataflowcb_3Dataflow,1,bind); it=rb_funcall(self,s_root_Dataflowcb_4Dataflow,1,bind); 
 bind_aset(bind,2/*autovar*/,it); it=rb_funcall(self,s_root_Dataflowcb_5Dataflow,1,bind); int oldpos3=ame_getpos(self); int oldlen3=ame_getlen(self); VALUE oldsrc3=ame_getsrc(self); int fail3=0;
ame_setsrc(self,bind_aget(bind,2/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDataflow,0)));
   it=AmethystCore_anything(self ); FAILTEST(pass3);
 bind_aset(bind,3/*autovar*/,it); int oldpos4=ame_getpos(self); int oldlen4=ame_getlen(self); VALUE oldsrc4=ame_getsrc(self); int fail4=0;
ame_setsrc(self,bind_aget(bind,3/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDataflow,0)));
 it=rb_ary_new3(0);
 bind_aset(bind,4/*autovar*/,it); int oldpos5; while(1){oldpos5=ame_getpos(self);   it=Dataflow_traverse_item(self ); FAILTEST(break1);
 bind_aset(bind,5/*autovar*/,it); it=rb_funcall(self,s_root_Dataflowcb_6Dataflow,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos5=ame_getpos(self);goto break1;} } } break1: ame_setstop(self,Qnil);  ame_setpos(self,oldpos5); it=bind_aget(bind,4/*autovar*/);
 bind_aset(bind,6/*var*/,it);   it=Amethyst_eof(self ); FAILTEST(pass4);
	goto success4;
	pass4: fail4=1;
	success4: ame_setsrc(self,oldsrc4); ame_setpos(self,oldpos4); ame_setlen(self,oldlen4);
	if(fail4) goto pass3;
  it=Amethyst_eof(self ); FAILTEST(pass3);
	goto success3;
	pass3: fail3=1;
	success3: ame_setsrc(self,oldsrc3); ame_setpos(self,oldpos3); ame_setlen(self,oldlen3);
	if(fail3) goto pass2;
it=rb_funcall(self,s_root_Dataflowcb_7Dataflow,1,bind); it=rb_funcall(self,s_root_Dataflowcb_8Dataflow,1,bind); 
 bind_aset(bind,7/*autovar*/,it); it=rb_funcall(self,s_root_Dataflowcb_9Dataflow,1,bind); int oldpos6=ame_getpos(self); int oldlen5=ame_getlen(self); VALUE oldsrc5=ame_getsrc(self); int fail5=0;
ame_setsrc(self,bind_aget(bind,7/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDataflow,0)));
   it=Dataflow_traverse_item(self ); FAILTEST(pass5);
 bind_aset(bind,8/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass5);
	goto success5;
	pass5: fail5=1;
	success5: ame_setsrc(self,oldsrc5); ame_setpos(self,oldpos6); ame_setlen(self,oldlen5);
	if(fail5) goto pass2;
it=bind_aget(bind,8/*autovar*/);
 bind_aset(bind,9/*body*/,it); it=rb_funcall(self,s_root_Dataflowcb_10Dataflow,1,bind); it=rb_funcall(self,s_root_Dataflowcb_11Dataflow,1,bind); it=rb_funcall(self,s_root_Dataflowcb_1Dataflow,1,bind); 
 bind_aset(bind,10/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass2);
	goto success2;
	pass2: fail2=1;
	success2: ame_setsrc(self,oldsrc2); ame_setpos(self,oldpos2); ame_setlen(self,oldlen2);
	if(fail2) goto pass1;
it=bind_aget(bind,10/*autovar*/);
 bind_aset(bind,11/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass1);
	goto success1;
	pass1: fail1=1;
	success1: ame_setsrc(self,oldsrc1); ame_setpos(self,oldpos1); ame_setlen(self,oldlen1);
	if(fail1) goto fail;
it=bind_aget(bind,11/*autovar*/);
 bind_aset(bind,12/*_result*/,it); it=bind_aget(bind,12/*_result*/);
return it;
fail: return failobj; }
VALUE Dataflow_traverse(VALUE self ){VALUE vals[0]; VALUE bind=bind_new2(15);  int x;VALUE arg0,arg1,arg2,arg3;VALUE it;

it=rb_ary_new3(0);
 bind_aset(bind,0/*autovar*/,it); int oldpos1; while(1){oldpos1=ame_getpos(self);   it=AmethystCore_anything(self ); FAILTEST(break1);
 bind_aset(bind,1/*autovar*/,it); it=rb_funcall(self,s_traverse_Dataflowcb_1Dataflow,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos1=ame_getpos(self);goto break1;} } } break1: ame_setstop(self,Qnil);  ame_setpos(self,oldpos1); it=bind_aget(bind,0/*autovar*/);it=rb_funcall(self,s_traverse_Dataflowcb_2Dataflow,1,bind); 
 bind_aset(bind,2/*oldchanged*/,it); it=rb_funcall(self,s_root_Dataflowcb_1Dataflow,1,bind); 
 bind_aset(bind,3/*this*/,it); it=Qnil;
 bind_aset(bind,4/*clon*/,it); it=Qfalse;
 bind_aset(bind,5/*changed*/,it); it=rb_funcall(self,s_traverse_Dataflowcb_3Dataflow,1,bind); 
 bind_aset(bind,6/*autovar*/,it); it=rb_funcall(self,s_traverse_Dataflowcb_4Dataflow,1,bind); int oldpos2=ame_getpos(self); int oldlen1=ame_getlen(self); VALUE oldsrc1=ame_getsrc(self); int fail1=0;
ame_setsrc(self,bind_aget(bind,6/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDataflow,0)));
   it=AmethystCore_anything(self ); FAILTEST(pass1);
 bind_aset(bind,7/*autovar*/,it); int oldpos3=ame_getpos(self); int oldlen2=ame_getlen(self); VALUE oldsrc2=ame_getsrc(self); int fail2=0;
ame_setsrc(self,bind_aget(bind,7/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDataflow,0)));
 it=rb_ary_new3(0);
 bind_aset(bind,8/*autovar*/,it); int oldpos4; while(1){oldpos4=ame_getpos(self);   it=AmethystCore_anything(self ); FAILTEST(break2);
 bind_aset(bind,9/*autovar*/,it); int oldpos5=ame_getpos(self); int oldlen3=ame_getlen(self); VALUE oldsrc3=ame_getsrc(self); int fail3=0;
ame_setsrc(self,bind_aget(bind,9/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDataflow,0)));
   it=AmethystCore_anything(self ); FAILTEST(pass3);
 bind_aset(bind,10/*key*/,it); it=rb_funcall(self,s_traverse_Dataflowcb_5Dataflow,1,bind);   it=Dataflow_traverse_item(self ); FAILTEST(pass3);
 bind_aset(bind,11/*val*/,it); it=rb_funcall(self,s_traverse_Dataflowcb_6Dataflow,1,bind); 
 bind_aset(bind,12/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass3);
	goto success3;
	pass3: fail3=1;
	success3: ame_setsrc(self,oldsrc3); ame_setpos(self,oldpos5); ame_setlen(self,oldlen3);
	if(fail3) goto break2;
it=bind_aget(bind,12/*autovar*/);
 bind_aset(bind,13/*autovar*/,it); it=rb_funcall(self,s_traverse_Dataflowcb_7Dataflow,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos4=ame_getpos(self);goto break2;} } } break2: ame_setstop(self,Qnil);  ame_setpos(self,oldpos4); it=bind_aget(bind,8/*autovar*/);  it=Amethyst_eof(self ); FAILTEST(pass2);
	goto success2;
	pass2: fail2=1;
	success2: ame_setsrc(self,oldsrc2); ame_setpos(self,oldpos3); ame_setlen(self,oldlen2);
	if(fail2) goto pass1;
  it=Amethyst_eof(self ); FAILTEST(pass1);
	goto success1;
	pass1: fail1=1;
	success1: ame_setsrc(self,oldsrc1); ame_setpos(self,oldpos2); ame_setlen(self,oldlen1);
	if(fail1) goto fail;
it=rb_funcall(self,s_traverse_Dataflowcb_8Dataflow,1,bind); 
 bind_aset(bind,14/*_result*/,it); it=bind_aget(bind,14/*_result*/);
return it;
fail: return failobj; }
VALUE Dataflow_traverse_item(VALUE self ){VALUE vals[0]; VALUE bind=bind_new2(10);  int x;VALUE arg0,arg1,arg2,arg3;VALUE it;

unsigned char chr1=FIX2LONG(rb_hash_aref(switchhashDataflow3,rb_obj_class(ame_curobj(self))));  switch(chr1){case 0:; int oldpos1=ame_getpos(self);
alt1_1: ame_setpos(self,oldpos1);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
   it=Dataflow_visit(self ); FAILTEST(alt1_2);
 bind_aset(bind,0/*a*/,it); it=rb_funcall(self,s_traverse_item_Dataflowcb_1Dataflow,1,bind); it=bind_aget(bind,0/*a*/);
 bind_aset(bind,1/*_result*/,it);  
ame_setcut(self,Qnil);goto accept1;
alt1_2: ame_setpos(self,oldpos1);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
   it=AmethystCore_anything(self ); FAILTEST(alt1_3);
 bind_aset(bind,2/*autovar*/,it); int oldpos2=ame_getpos(self); int oldlen1=ame_getlen(self); VALUE oldsrc1=ame_getsrc(self); int fail1=0;
ame_setsrc(self,bind_aget(bind,2/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDataflow,0)));
   it=Dataflow_traverse(self ); FAILTEST(pass1);
 bind_aset(bind,3/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass1);
	goto success1;
	pass1: fail1=1;
	success1: ame_setsrc(self,oldsrc1); ame_setpos(self,oldpos2); ame_setlen(self,oldlen1);
	if(fail1) goto alt1_3;
it=bind_aget(bind,3/*autovar*/);
 bind_aset(bind,1/*_result*/,it);  
ame_setcut(self,Qnil);goto accept1;
alt1_3: ame_setpos(self,oldpos1);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
   it=AmethystCore_anything(self ); FAILTEST(alt1_4);
 bind_aset(bind,1/*_result*/,it);  
ame_setcut(self,Qnil);goto accept1;
  alt1_4:  ame_setpos(self,oldpos1); goto fail;
 accept1:;
 break;case 1:; int oldpos3=ame_getpos(self);
alt2_1: ame_setpos(self,oldpos3);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
   it=Dataflow_visit(self ); FAILTEST(alt2_2);
 bind_aset(bind,0/*a*/,it); it=rb_funcall(self,s_traverse_item_Dataflowcb_1Dataflow,1,bind); it=bind_aget(bind,0/*a*/);
 bind_aset(bind,1/*_result*/,it);  
ame_setcut(self,Qnil);goto accept2;
alt2_2: ame_setpos(self,oldpos3);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
   it=AmethystCore_anything(self ); FAILTEST(alt2_3);
 bind_aset(bind,4/*autovar*/,it); int oldpos4=ame_getpos(self); int oldlen2=ame_getlen(self); VALUE oldsrc2=ame_getsrc(self); int fail2=0;
ame_setsrc(self,bind_aget(bind,4/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDataflow,0)));
 it=rb_ary_new3(0);
 bind_aset(bind,5/*ar*/,it); it=rb_ary_new3(0);
 bind_aset(bind,6/*autovar*/,it); int oldpos5; while(1){oldpos5=ame_getpos(self);   it=Dataflow_traverse_item(self ); FAILTEST(break1);
 bind_aset(bind,7/*it*/,it); it=rb_funcall(self,s_traverse_item_Dataflowcb_2Dataflow,1,bind); 
 bind_aset(bind,8/*autovar*/,it); it=rb_funcall(self,s_traverse_item_Dataflowcb_3Dataflow,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos5=ame_getpos(self);goto break1;} } } break1: ame_setstop(self,Qnil);  ame_setpos(self,oldpos5); it=bind_aget(bind,6/*autovar*/);it=bind_aget(bind,5/*ar*/);
 bind_aset(bind,9/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass2);
	goto success2;
	pass2: fail2=1;
	success2: ame_setsrc(self,oldsrc2); ame_setpos(self,oldpos4); ame_setlen(self,oldlen2);
	if(fail2) goto alt2_3;
it=bind_aget(bind,9/*autovar*/);
 bind_aset(bind,1/*_result*/,it);  
ame_setcut(self,Qnil);goto accept2;
alt2_3: ame_setpos(self,oldpos3);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
   it=AmethystCore_anything(self ); FAILTEST(alt2_4);
 bind_aset(bind,1/*_result*/,it);  
ame_setcut(self,Qnil);goto accept2;
  alt2_4:  ame_setpos(self,oldpos3); goto fail;
 accept2:;
 break;case 2:; int oldpos6=ame_getpos(self);
alt3_1: ame_setpos(self,oldpos6);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
   it=Dataflow_visit(self ); FAILTEST(alt3_2);
 bind_aset(bind,0/*a*/,it); it=rb_funcall(self,s_traverse_item_Dataflowcb_1Dataflow,1,bind); it=bind_aget(bind,0/*a*/);
 bind_aset(bind,1/*_result*/,it);  
ame_setcut(self,Qnil);goto accept3;
alt3_2: ame_setpos(self,oldpos6);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
   it=AmethystCore_anything(self ); FAILTEST(alt3_3);
 bind_aset(bind,1/*_result*/,it);  
ame_setcut(self,Qnil);goto accept3;
  alt3_3:  ame_setpos(self,oldpos6); goto fail;
 accept3:;
 break;}it=bind_aget(bind,1/*_result*/);
return it;
fail: return failobj; }
VALUE Dataflow_vars_in(VALUE self ){VALUE vals[0]; VALUE bind=bind_new2(36);  int x;VALUE arg0,arg1,arg2,arg3;VALUE it;

it=rb_ary_new3(0);
 bind_aset(bind,0/*ary*/,it); it=rb_funcall(self,s_vars_in_Dataflowcb_1Dataflow,1,bind); it=rb_ary_new3(0);
 bind_aset(bind,1/*autovar*/,it); int oldpos1; while(1){oldpos1=ame_getpos(self); unsigned char chr1=FIX2LONG(rb_hash_aref(switchhashDataflow2,rb_obj_class(ame_curobj(self))));  switch(chr1){case 0:; int oldpos2=ame_getpos(self);
alt1_1: ame_setpos(self,oldpos2);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto break1;}
   it=AmethystCore_anything(self ); FAILTEST(alt1_2);
 bind_aset(bind,2/*autovar*/,it); int oldpos3=ame_getpos(self); int oldlen1=ame_getlen(self); VALUE oldsrc1=ame_getsrc(self); int fail1=0;
ame_setsrc(self,bind_aget(bind,2/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDataflow,0)));
 it=rb_funcall(self,s_root_Dataflowcb_1Dataflow,1,bind); 
 bind_aset(bind,3/*autovar*/,it); it=rb_funcall(self,s_vars_in_Dataflowcb_2Dataflow,1,bind); it=rb_ary_new3(0);
 bind_aset(bind,4/*autovar*/,it); int oldpos4; while(1){oldpos4=ame_getpos(self);   it=AmethystCore_anything(self ); FAILTEST(break2);
 bind_aset(bind,5/*autovar*/,it); it=rb_funcall(self,s_root_Dataflowcb_6Dataflow,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos4=ame_getpos(self);goto break2;} } } break2: ame_setstop(self,Qnil);  ame_setpos(self,oldpos4); it=bind_aget(bind,4/*autovar*/);
 bind_aset(bind,6/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass1);
	goto success1;
	pass1: fail1=1;
	success1: ame_setsrc(self,oldsrc1); ame_setpos(self,oldpos3); ame_setlen(self,oldlen1);
	if(fail1) goto alt1_2;
it=bind_aget(bind,6/*autovar*/);
 bind_aset(bind,7/*autovar*/,it);  
ame_setcut(self,Qnil);goto accept1;
alt1_2: ame_setpos(self,oldpos2);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto break1;}
   it=AmethystCore_anything(self ); FAILTEST(alt1_3);
 bind_aset(bind,7/*autovar*/,it);  
ame_setcut(self,Qnil);goto accept1;
  alt1_3:  ame_setpos(self,oldpos2); goto break1;
 accept1:;
 break;case 1:; int oldpos5=ame_getpos(self);
alt2_1: ame_setpos(self,oldpos5);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto break1;}
   it=AmethystCore_anything(self ); FAILTEST(alt2_2);
 bind_aset(bind,8/*autovar*/,it); int oldpos6=ame_getpos(self); int oldlen2=ame_getlen(self); VALUE oldsrc2=ame_getsrc(self); int fail2=0;
ame_setsrc(self,bind_aget(bind,8/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDataflow,0)));
   it=Dataflow_vars_in(self ); FAILTEST(pass2);
 bind_aset(bind,9/*autovar*/,it); it=rb_funcall(self,s_vars_in_Dataflowcb_3Dataflow,1,bind); 
 bind_aset(bind,10/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass2);
	goto success2;
	pass2: fail2=1;
	success2: ame_setsrc(self,oldsrc2); ame_setpos(self,oldpos6); ame_setlen(self,oldlen2);
	if(fail2) goto alt2_2;
it=bind_aget(bind,10/*autovar*/);
 bind_aset(bind,7/*autovar*/,it);  
ame_setcut(self,Qnil);goto accept2;
alt2_2: ame_setpos(self,oldpos5);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto break1;}
   it=AmethystCore_anything(self ); FAILTEST(alt2_3);
 bind_aset(bind,7/*autovar*/,it);  
ame_setcut(self,Qnil);goto accept2;
  alt2_3:  ame_setpos(self,oldpos5); goto break1;
 accept2:;
 break;case 2:; int oldpos7=ame_getpos(self);
alt3_1: ame_setpos(self,oldpos7);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto break1;}
   it=AmethystCore_anything(self ); FAILTEST(alt3_2);
 bind_aset(bind,11/*autovar*/,it); int oldpos8=ame_getpos(self); int oldlen3=ame_getlen(self); VALUE oldsrc3=ame_getsrc(self); int fail3=0;
ame_setsrc(self,bind_aget(bind,11/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDataflow,0)));
   it=Dataflow_vars_in(self ); FAILTEST(pass3);
 bind_aset(bind,12/*autovar*/,it); it=rb_funcall(self,s_vars_in_Dataflowcb_4Dataflow,1,bind); 
 bind_aset(bind,13/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass3);
	goto success3;
	pass3: fail3=1;
	success3: ame_setsrc(self,oldsrc3); ame_setpos(self,oldpos8); ame_setlen(self,oldlen3);
	if(fail3) goto alt3_2;
it=bind_aget(bind,13/*autovar*/);
 bind_aset(bind,7/*autovar*/,it);  
ame_setcut(self,Qnil);goto accept3;
alt3_2: ame_setpos(self,oldpos7);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto break1;}
   it=AmethystCore_anything(self ); FAILTEST(alt3_3);
 bind_aset(bind,7/*autovar*/,it);  
ame_setcut(self,Qnil);goto accept3;
  alt3_3:  ame_setpos(self,oldpos7); goto break1;
 accept3:;
 break;case 3:; int oldpos9=ame_getpos(self);
alt4_1: ame_setpos(self,oldpos9);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto break1;}
   it=AmethystCore_anything(self ); FAILTEST(alt4_2);
 bind_aset(bind,14/*autovar*/,it); int oldpos10=ame_getpos(self); int oldlen4=ame_getlen(self); VALUE oldsrc4=ame_getsrc(self); int fail4=0;
ame_setsrc(self,bind_aget(bind,14/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDataflow,0)));
 it=rb_funcall(self,s_root_Dataflowcb_1Dataflow,1,bind); 
 bind_aset(bind,15/*autovar*/,it); it=rb_funcall(self,s_vars_in_Dataflowcb_5Dataflow,1,bind); it=rb_ary_new3(0);
 bind_aset(bind,16/*autovar*/,it); int oldpos11; while(1){oldpos11=ame_getpos(self);   it=AmethystCore_anything(self ); FAILTEST(break3);
 bind_aset(bind,17/*autovar*/,it); it=rb_funcall(self,s_vars_in_Dataflowcb_6Dataflow,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos11=ame_getpos(self);goto break3;} } } break3: ame_setstop(self,Qnil);  ame_setpos(self,oldpos11); it=bind_aget(bind,16/*autovar*/);
 bind_aset(bind,18/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass4);
	goto success4;
	pass4: fail4=1;
	success4: ame_setsrc(self,oldsrc4); ame_setpos(self,oldpos10); ame_setlen(self,oldlen4);
	if(fail4) goto alt4_2;
it=bind_aget(bind,18/*autovar*/);
 bind_aset(bind,7/*autovar*/,it);  
ame_setcut(self,Qnil);goto accept4;
alt4_2: ame_setpos(self,oldpos9);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto break1;}
   it=AmethystCore_anything(self ); FAILTEST(alt4_3);
 bind_aset(bind,7/*autovar*/,it);  
ame_setcut(self,Qnil);goto accept4;
  alt4_3:  ame_setpos(self,oldpos9); goto break1;
 accept4:;
 break;case 4:; int oldpos12=ame_getpos(self);
alt5_1: ame_setpos(self,oldpos12);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto break1;}
   it=AmethystCore_anything(self ); FAILTEST(alt5_2);
 bind_aset(bind,19/*autovar*/,it); int oldpos13=ame_getpos(self); int oldlen5=ame_getlen(self); VALUE oldsrc5=ame_getsrc(self); int fail5=0;
ame_setsrc(self,bind_aget(bind,19/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDataflow,0)));
 it=rb_funcall(self,s_root_Dataflowcb_1Dataflow,1,bind); 
 bind_aset(bind,20/*autovar*/,it); it=rb_funcall(self,s_vars_in_Dataflowcb_7Dataflow,1,bind); it=rb_funcall(self,s_vars_in_Dataflowcb_8Dataflow,1,bind); it=rb_ary_new3(0);
 bind_aset(bind,21/*autovar*/,it); int oldpos14; while(1){oldpos14=ame_getpos(self);   it=AmethystCore_anything(self ); FAILTEST(break4);
 bind_aset(bind,22/*autovar*/,it); it=rb_funcall(self,s_vars_in_Dataflowcb_9Dataflow,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos14=ame_getpos(self);goto break4;} } } break4: ame_setstop(self,Qnil);  ame_setpos(self,oldpos14); it=bind_aget(bind,21/*autovar*/);
 bind_aset(bind,23/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass5);
	goto success5;
	pass5: fail5=1;
	success5: ame_setsrc(self,oldsrc5); ame_setpos(self,oldpos13); ame_setlen(self,oldlen5);
	if(fail5) goto alt5_2;
it=bind_aget(bind,23/*autovar*/);
 bind_aset(bind,7/*autovar*/,it);  
ame_setcut(self,Qnil);goto accept5;
alt5_2: ame_setpos(self,oldpos12);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto break1;}
   it=AmethystCore_anything(self ); FAILTEST(alt5_3);
 bind_aset(bind,7/*autovar*/,it);  
ame_setcut(self,Qnil);goto accept5;
  alt5_3:  ame_setpos(self,oldpos12); goto break1;
 accept5:;
 break;case 5:; int oldpos15=ame_getpos(self);
alt6_1: ame_setpos(self,oldpos15);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto break1;}
   it=AmethystCore_anything(self ); FAILTEST(alt6_2);
 bind_aset(bind,24/*autovar*/,it); int oldpos16=ame_getpos(self); int oldlen6=ame_getlen(self); VALUE oldsrc6=ame_getsrc(self); int fail6=0;
ame_setsrc(self,bind_aget(bind,24/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDataflow,0)));
 it=rb_funcall(self,s_root_Dataflowcb_1Dataflow,1,bind); 
 bind_aset(bind,25/*autovar*/,it); it=rb_funcall(self,s_vars_in_Dataflowcb_10Dataflow,1,bind); it=rb_funcall(self,s_vars_in_Dataflowcb_8Dataflow,1,bind); it=rb_ary_new3(0);
 bind_aset(bind,26/*autovar*/,it); int oldpos17; while(1){oldpos17=ame_getpos(self);   it=AmethystCore_anything(self ); FAILTEST(break5);
 bind_aset(bind,27/*autovar*/,it); it=rb_funcall(self,s_vars_in_Dataflowcb_11Dataflow,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos17=ame_getpos(self);goto break5;} } } break5: ame_setstop(self,Qnil);  ame_setpos(self,oldpos17); it=bind_aget(bind,26/*autovar*/);
 bind_aset(bind,28/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass6);
	goto success6;
	pass6: fail6=1;
	success6: ame_setsrc(self,oldsrc6); ame_setpos(self,oldpos16); ame_setlen(self,oldlen6);
	if(fail6) goto alt6_2;
it=bind_aget(bind,28/*autovar*/);
 bind_aset(bind,7/*autovar*/,it);  
ame_setcut(self,Qnil);goto accept6;
alt6_2: ame_setpos(self,oldpos15);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto break1;}
   it=AmethystCore_anything(self ); FAILTEST(alt6_3);
 bind_aset(bind,7/*autovar*/,it);  
ame_setcut(self,Qnil);goto accept6;
  alt6_3:  ame_setpos(self,oldpos15); goto break1;
 accept6:;
 break;case 6:; int oldpos18=ame_getpos(self);
alt7_1: ame_setpos(self,oldpos18);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto break1;}
   it=AmethystCore_anything(self ); FAILTEST(alt7_2);
 bind_aset(bind,29/*autovar*/,it); int oldpos19=ame_getpos(self); int oldlen7=ame_getlen(self); VALUE oldsrc7=ame_getsrc(self); int fail7=0;
ame_setsrc(self,bind_aget(bind,29/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDataflow,0)));
   it=AmethystCore_anything(self ); FAILTEST(pass7);it=rb_funcall(self,s_root_Dataflowcb_1Dataflow,1,bind); 
 bind_aset(bind,30/*autovar*/,it); it=rb_funcall(self,s_vars_in_Dataflowcb_12Dataflow,1,bind); 
 bind_aset(bind,31/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass7);
	goto success7;
	pass7: fail7=1;
	success7: ame_setsrc(self,oldsrc7); ame_setpos(self,oldpos19); ame_setlen(self,oldlen7);
	if(fail7) goto alt7_2;
it=bind_aget(bind,31/*autovar*/);
 bind_aset(bind,7/*autovar*/,it);  
ame_setcut(self,Qnil);goto accept7;
alt7_2: ame_setpos(self,oldpos18);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto break1;}
   it=AmethystCore_anything(self ); FAILTEST(alt7_3);
 bind_aset(bind,7/*autovar*/,it);  
ame_setcut(self,Qnil);goto accept7;
  alt7_3:  ame_setpos(self,oldpos18); goto break1;
 accept7:;
 break;case 7:; int oldpos20=ame_getpos(self);
alt8_1: ame_setpos(self,oldpos20);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto break1;}
   it=AmethystCore_anything(self ); FAILTEST(alt8_2);
 bind_aset(bind,32/*autovar*/,it); int oldpos21=ame_getpos(self); int oldlen8=ame_getlen(self); VALUE oldsrc8=ame_getsrc(self); int fail8=0;
ame_setsrc(self,bind_aget(bind,32/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDataflow,0)));
 it=rb_funcall(self,s_root_Dataflowcb_1Dataflow,1,bind); 
 bind_aset(bind,33/*autovar*/,it); it=rb_funcall(self,s_vars_in_Dataflowcb_13Dataflow,1,bind); 
 bind_aset(bind,34/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass8);
	goto success8;
	pass8: fail8=1;
	success8: ame_setsrc(self,oldsrc8); ame_setpos(self,oldpos21); ame_setlen(self,oldlen8);
	if(fail8) goto alt8_2;
it=bind_aget(bind,34/*autovar*/);
 bind_aset(bind,7/*autovar*/,it);  
ame_setcut(self,Qnil);goto accept8;
alt8_2: ame_setpos(self,oldpos20);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto break1;}
   it=AmethystCore_anything(self ); FAILTEST(alt8_3);
 bind_aset(bind,7/*autovar*/,it);  
ame_setcut(self,Qnil);goto accept8;
  alt8_3:  ame_setpos(self,oldpos20); goto break1;
 accept8:;
 break;case 8:;   it=AmethystCore_anything(self ); FAILTEST(break1);
 bind_aset(bind,7/*autovar*/,it);  break;}it=rb_funcall(self,s_vars_in_Dataflowcb_14Dataflow,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos1=ame_getpos(self);goto break1;} } } break1: ame_setstop(self,Qnil);  ame_setpos(self,oldpos1); it=bind_aget(bind,1/*autovar*/);it=bind_aget(bind,0/*ary*/);
 bind_aset(bind,35/*_result*/,it); it=bind_aget(bind,35/*_result*/);
return it;
fail: return failobj; }
VALUE Dataflow_visit(VALUE self ){VALUE vals[0]; VALUE bind=bind_new2(65);  int x;VALUE arg0,arg1,arg2,arg3;VALUE it;

it=rb_ary_new3(0);
 bind_aset(bind,0/*t*/,it); unsigned char chr1=FIX2LONG(rb_hash_aref(switchhashDataflow1,rb_obj_class(ame_curobj(self))));  switch(chr1){case 0:;   it=AmethystCore_anything(self ); FAILTEST(fail);
 bind_aset(bind,1/*autovar*/,it); int oldpos1=ame_getpos(self); int oldlen1=ame_getlen(self); VALUE oldsrc1=ame_getsrc(self); int fail1=0;
ame_setsrc(self,bind_aget(bind,1/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDataflow,0)));
 it=rb_ary_new3(0);
 bind_aset(bind,2/*autovar*/,it); int oldpos2; while(1){oldpos2=ame_getpos(self);   it=Dataflow_traverse_item(self ); FAILTEST(break1);
 bind_aset(bind,3/*autovar*/,it); it=rb_funcall(self,s_visit_Dataflowcb_1Dataflow,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos2=ame_getpos(self);goto break1;} } } break1: ame_setstop(self,Qnil);  ame_setpos(self,oldpos2); it=bind_aget(bind,2/*autovar*/);
 bind_aset(bind,0/*t*/,it); it=rb_funcall(self,s_visit_Dataflowcb_2Dataflow,1,bind); 
 bind_aset(bind,4/*act*/,it); it=rb_funcall(self,s_visit_Dataflowcb_3Dataflow,1,bind); it=rb_funcall(self,s_visit_Dataflowcb_4Dataflow,1,bind); 
 bind_aset(bind,5/*autovar*/,it); it=rb_funcall(self,s_visit_Dataflowcb_5Dataflow,1,bind); int oldpos3=ame_getpos(self); int oldlen2=ame_getlen(self); VALUE oldsrc2=ame_getsrc(self); int fail2=0;
ame_setsrc(self,bind_aget(bind,5/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDataflow,0)));
   it=AmethystCore_anything(self ); FAILTEST(pass2);
 bind_aset(bind,6/*autovar*/,it); int oldpos4=ame_getpos(self); int oldlen3=ame_getlen(self); VALUE oldsrc3=ame_getsrc(self); int fail3=0;
ame_setsrc(self,bind_aget(bind,6/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDataflow,0)));
   it=Dataflow_vars_in(self ); FAILTEST(pass3);
 bind_aset(bind,7/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass3);
	goto success3;
	pass3: fail3=1;
	success3: ame_setsrc(self,oldsrc3); ame_setpos(self,oldpos4); ame_setlen(self,oldlen3);
	if(fail3) goto pass2;
it=bind_aget(bind,7/*autovar*/);
 bind_aset(bind,8/*var*/,it);   it=Amethyst_eof(self ); FAILTEST(pass2);
	goto success2;
	pass2: fail2=1;
	success2: ame_setsrc(self,oldsrc2); ame_setpos(self,oldpos3); ame_setlen(self,oldlen2);
	if(fail2) goto pass1;
it=rb_funcall(self,s_visit_Dataflowcb_6Dataflow,1,bind); 
 bind_aset(bind,9/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass1);
	goto success1;
	pass1: fail1=1;
	success1: ame_setsrc(self,oldsrc1); ame_setpos(self,oldpos1); ame_setlen(self,oldlen1);
	if(fail1) goto fail;
it=bind_aget(bind,9/*autovar*/);
 bind_aset(bind,10/*_result*/,it);  break;case 10:;   it=Amethyst_fails(self ); FAILTEST(fail); break;case 1:;   it=AmethystCore_anything(self ); FAILTEST(fail);
 bind_aset(bind,11/*autovar*/,it); int oldpos5=ame_getpos(self); int oldlen4=ame_getlen(self); VALUE oldsrc4=ame_getsrc(self); int fail4=0;
ame_setsrc(self,bind_aget(bind,11/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDataflow,0)));
 it=rb_ary_new3(0);
 bind_aset(bind,12/*autovar*/,it); int oldpos6; while(1){oldpos6=ame_getpos(self);   it=Dataflow_traverse_item(self ); FAILTEST(break2);
 bind_aset(bind,13/*autovar*/,it); it=rb_funcall(self,s_visit_Dataflowcb_7Dataflow,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos6=ame_getpos(self);goto break2;} } } break2: ame_setstop(self,Qnil);  ame_setpos(self,oldpos6); it=bind_aget(bind,12/*autovar*/);
 bind_aset(bind,0/*t*/,it); it=rb_funcall(self,s_visit_Dataflowcb_8Dataflow,1,bind); 
 bind_aset(bind,14/*app*/,it); it=bind_aget(bind,14/*app*/);
 bind_aset(bind,15/*autovar*/,it); it=rb_funcall(self,s_visit_Dataflowcb_9Dataflow,1,bind); int oldpos7=ame_getpos(self); int oldlen5=ame_getlen(self); VALUE oldsrc5=ame_getsrc(self); int fail5=0;
ame_setsrc(self,bind_aget(bind,15/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDataflow,0)));
   it=AmethystCore_anything(self ); FAILTEST(pass5);
 bind_aset(bind,16/*autovar*/,it); int oldpos8=ame_getpos(self); int oldlen6=ame_getlen(self); VALUE oldsrc6=ame_getsrc(self); int fail6=0;
ame_setsrc(self,bind_aget(bind,16/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDataflow,0)));
   it=Dataflow_vars_in(self ); FAILTEST(pass6);
 bind_aset(bind,8/*var*/,it);   it=Amethyst_eof(self ); FAILTEST(pass6);
	goto success6;
	pass6: fail6=1;
	success6: ame_setsrc(self,oldsrc6); ame_setpos(self,oldpos8); ame_setlen(self,oldlen6);
	if(fail6) goto pass5;
  it=Amethyst_eof(self ); FAILTEST(pass5);
	goto success5;
	pass5: fail5=1;
	success5: ame_setsrc(self,oldsrc5); ame_setpos(self,oldpos7); ame_setlen(self,oldlen5);
	if(fail5) goto pass4;
it=rb_funcall(self,s_visit_Dataflowcb_10Dataflow,1,bind); it=bind_aget(bind,14/*app*/);
 bind_aset(bind,17/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass4);
	goto success4;
	pass4: fail4=1;
	success4: ame_setsrc(self,oldsrc4); ame_setpos(self,oldpos5); ame_setlen(self,oldlen4);
	if(fail4) goto fail;
it=bind_aget(bind,17/*autovar*/);
 bind_aset(bind,10/*_result*/,it);  break;case 2:;   it=AmethystCore_anything(self ); FAILTEST(fail);
 bind_aset(bind,18/*autovar*/,it); int oldpos9=ame_getpos(self); int oldlen7=ame_getlen(self); VALUE oldsrc7=ame_getsrc(self); int fail7=0;
ame_setsrc(self,bind_aget(bind,18/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDataflow,0)));
 it=rb_ary_new3(0);
 bind_aset(bind,19/*autovar*/,it); int oldpos10; while(1){oldpos10=ame_getpos(self);   it=AmethystCore_anything(self ); FAILTEST(break3);
 bind_aset(bind,20/*autovar*/,it); it=rb_funcall(self,s_visit_Dataflowcb_11Dataflow,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos10=ame_getpos(self);goto break3;} } } break3: ame_setstop(self,Qnil);  ame_setpos(self,oldpos10); it=bind_aget(bind,19/*autovar*/);  it=Dataflow_traverse(self ); FAILTEST(pass7);
 bind_aset(bind,21/*autovar*/,it); int oldpos11=ame_getpos(self); int oldlen8=ame_getlen(self); VALUE oldsrc8=ame_getsrc(self); int fail8=0;
ame_setsrc(self,bind_aget(bind,21/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDataflow,0)));
 it=rb_ary_new3(0);
 bind_aset(bind,22/*autovar*/,it); int oldpos12; while(1){oldpos12=ame_getpos(self);   it=AmethystCore_anything(self ); FAILTEST(break4);
 bind_aset(bind,23/*autovar*/,it); it=rb_funcall(self,s_visit_Dataflowcb_12Dataflow,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos12=ame_getpos(self);goto break4;} } } break4: ame_setstop(self,Qnil);  ame_setpos(self,oldpos12); it=bind_aget(bind,22/*autovar*/);it=rb_funcall(self,s_visit_Dataflowcb_13Dataflow,1,bind); 
 bind_aset(bind,24/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass8);
	goto success8;
	pass8: fail8=1;
	success8: ame_setsrc(self,oldsrc8); ame_setpos(self,oldpos11); ame_setlen(self,oldlen8);
	if(fail8) goto pass7;
it=bind_aget(bind,24/*autovar*/);
 bind_aset(bind,25/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass7);
	goto success7;
	pass7: fail7=1;
	success7: ame_setsrc(self,oldsrc7); ame_setpos(self,oldpos9); ame_setlen(self,oldlen7);
	if(fail7) goto fail;
it=bind_aget(bind,25/*autovar*/);
 bind_aset(bind,10/*_result*/,it);  break;case 3:;   it=AmethystCore_anything(self ); FAILTEST(fail);
 bind_aset(bind,26/*autovar*/,it); int oldpos13=ame_getpos(self); int oldlen9=ame_getlen(self); VALUE oldsrc9=ame_getsrc(self); int fail9=0;
ame_setsrc(self,bind_aget(bind,26/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDataflow,0)));
 it=rb_ary_new3(0);
 bind_aset(bind,27/*autovar*/,it); int oldpos14; while(1){oldpos14=ame_getpos(self);   it=AmethystCore_anything(self ); FAILTEST(break5);
 bind_aset(bind,28/*autovar*/,it); it=rb_funcall(self,s_visit_Dataflowcb_14Dataflow,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos14=ame_getpos(self);goto break5;} } } break5: ame_setstop(self,Qnil);  ame_setpos(self,oldpos14); it=bind_aget(bind,27/*autovar*/);it=rb_funcall(self,s_visit_Dataflowcb_15Dataflow,1,bind); 
 bind_aset(bind,29/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass9);
	goto success9;
	pass9: fail9=1;
	success9: ame_setsrc(self,oldsrc9); ame_setpos(self,oldpos13); ame_setlen(self,oldlen9);
	if(fail9) goto fail;
it=bind_aget(bind,29/*autovar*/);
 bind_aset(bind,10/*_result*/,it);  break;case 4:;   it=AmethystCore_anything(self ); FAILTEST(fail);
 bind_aset(bind,30/*autovar*/,it); int oldpos15=ame_getpos(self); int oldlen10=ame_getlen(self); VALUE oldsrc10=ame_getsrc(self); int fail10=0;
ame_setsrc(self,bind_aget(bind,30/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDataflow,0)));
 it=rb_ary_new3(0);
 bind_aset(bind,31/*autovar*/,it); int oldpos16; while(1){oldpos16=ame_getpos(self);   it=Dataflow_traverse_item(self ); FAILTEST(break6);
 bind_aset(bind,32/*autovar*/,it); it=rb_funcall(self,s_visit_Dataflowcb_16Dataflow,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos16=ame_getpos(self);goto break6;} } } break6: ame_setstop(self,Qnil);  ame_setpos(self,oldpos16); it=bind_aget(bind,31/*autovar*/);
 bind_aset(bind,0/*t*/,it); it=rb_funcall(self,s_visit_Dataflowcb_17Dataflow,1,bind); 
 bind_aset(bind,33/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass10);
	goto success10;
	pass10: fail10=1;
	success10: ame_setsrc(self,oldsrc10); ame_setpos(self,oldpos15); ame_setlen(self,oldlen10);
	if(fail10) goto fail;
it=bind_aget(bind,33/*autovar*/);
 bind_aset(bind,10/*_result*/,it);  break;case 5:;   it=AmethystCore_anything(self ); FAILTEST(fail);
 bind_aset(bind,34/*autovar*/,it); int oldpos17=ame_getpos(self); int oldlen11=ame_getlen(self); VALUE oldsrc11=ame_getsrc(self); int fail11=0;
ame_setsrc(self,bind_aget(bind,34/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDataflow,0)));
 it=rb_funcall(self,s_visit_Dataflowcb_18Dataflow,1,bind); 
 bind_aset(bind,35/*prev*/,it); it=rb_ary_new3(0);
 bind_aset(bind,36/*autovar*/,it); int oldpos18; while(1){oldpos18=ame_getpos(self);   it=Dataflow_traverse_item(self ); FAILTEST(break7);
 bind_aset(bind,37/*autovar*/,it); it=rb_funcall(self,s_visit_Dataflowcb_19Dataflow,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos18=ame_getpos(self);goto break7;} } } break7: ame_setstop(self,Qnil);  ame_setpos(self,oldpos18); it=bind_aget(bind,36/*autovar*/);
 bind_aset(bind,0/*t*/,it); it=rb_funcall(self,s_visit_Dataflowcb_20Dataflow,1,bind); it=rb_funcall(self,s_visit_Dataflowcb_21Dataflow,1,bind); 
 bind_aset(bind,38/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass11);
	goto success11;
	pass11: fail11=1;
	success11: ame_setsrc(self,oldsrc11); ame_setpos(self,oldpos17); ame_setlen(self,oldlen11);
	if(fail11) goto fail;
it=bind_aget(bind,38/*autovar*/);
 bind_aset(bind,10/*_result*/,it);  break;case 6:;   it=AmethystCore_anything(self ); FAILTEST(fail);
 bind_aset(bind,39/*autovar*/,it); int oldpos19=ame_getpos(self); int oldlen12=ame_getlen(self); VALUE oldsrc12=ame_getsrc(self); int fail12=0;
ame_setsrc(self,bind_aget(bind,39/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDataflow,0)));
 it=rb_ary_new3(0);
 bind_aset(bind,40/*join*/,it); it=rb_funcall(self,s_visit_Dataflowcb_22Dataflow,1,bind); 
 bind_aset(bind,41/*old*/,it); it=rb_ary_new3(0);
 bind_aset(bind,42/*autovar*/,it); int oldpos20; while(1){oldpos20=ame_getpos(self); it=rb_funcall(self,s_visit_Dataflowcb_23Dataflow,1,bind);   it=Dataflow_traverse_item(self ); FAILTEST(break8);
 bind_aset(bind,43/*autovar*/,it); it=rb_funcall(self,s_visit_Dataflowcb_24Dataflow,1,bind); it=rb_funcall(self,s_visit_Dataflowcb_25Dataflow,1,bind); 
 bind_aset(bind,44/*autovar*/,it); it=rb_funcall(self,s_visit_Dataflowcb_26Dataflow,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos20=ame_getpos(self);goto break8;} } } break8: ame_setstop(self,Qnil);  ame_setpos(self,oldpos20); it=bind_aget(bind,42/*autovar*/);it=rb_funcall(self,s_visit_Dataflowcb_27Dataflow,1,bind); it=rb_funcall(self,s_visit_Dataflowcb_28Dataflow,1,bind); 
 bind_aset(bind,45/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass12);
	goto success12;
	pass12: fail12=1;
	success12: ame_setsrc(self,oldsrc12); ame_setpos(self,oldpos19); ame_setlen(self,oldlen12);
	if(fail12) goto fail;
it=bind_aget(bind,45/*autovar*/);
 bind_aset(bind,10/*_result*/,it);  break;case 7:;   it=AmethystCore_anything(self ); FAILTEST(fail);
 bind_aset(bind,46/*autovar*/,it); int oldpos21=ame_getpos(self); int oldlen13=ame_getlen(self); VALUE oldsrc13=ame_getsrc(self); int fail13=0;
ame_setsrc(self,bind_aget(bind,46/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDataflow,0)));
 it=rb_funcall(self,s_visit_Dataflowcb_29Dataflow,1,bind); 
 bind_aset(bind,47/*autovar*/,it); it=rb_funcall(self,s_visit_Dataflowcb_30Dataflow,1,bind); int oldpos22=ame_getpos(self); int oldlen14=ame_getlen(self); VALUE oldsrc14=ame_getsrc(self); int fail14=0;
ame_setsrc(self,bind_aget(bind,47/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDataflow,0)));
   it=Dataflow_traverse_item(self ); FAILTEST(pass14);
 bind_aset(bind,48/*to*/,it);   it=Amethyst_eof(self ); FAILTEST(pass14);
	goto success14;
	pass14: fail14=1;
	success14: ame_setsrc(self,oldsrc14); ame_setpos(self,oldpos22); ame_setlen(self,oldlen14);
	if(fail14) goto pass13;
it=rb_funcall(self,s_visit_Dataflowcb_31Dataflow,1,bind); 
 bind_aset(bind,49/*autovar*/,it); it=rb_funcall(self,s_visit_Dataflowcb_32Dataflow,1,bind); int oldpos23=ame_getpos(self); int oldlen15=ame_getlen(self); VALUE oldsrc15=ame_getsrc(self); int fail15=0;
ame_setsrc(self,bind_aget(bind,49/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDataflow,0)));
   it=Dataflow_traverse_item(self ); FAILTEST(pass15);
 bind_aset(bind,8/*var*/,it);   it=Amethyst_eof(self ); FAILTEST(pass15);
	goto success15;
	pass15: fail15=1;
	success15: ame_setsrc(self,oldsrc15); ame_setpos(self,oldpos23); ame_setlen(self,oldlen15);
	if(fail15) goto pass13;
it=rb_funcall(self,s_visit_Dataflowcb_33Dataflow,1,bind); it=rb_funcall(self,s_visit_Dataflowcb_34Dataflow,1,bind); 
 bind_aset(bind,50/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass13);
	goto success13;
	pass13: fail13=1;
	success13: ame_setsrc(self,oldsrc13); ame_setpos(self,oldpos21); ame_setlen(self,oldlen13);
	if(fail13) goto fail;
it=bind_aget(bind,50/*autovar*/);
 bind_aset(bind,10/*_result*/,it);  break;case 8:;   it=AmethystCore_anything(self ); FAILTEST(fail);
 bind_aset(bind,51/*autovar*/,it); int oldpos24=ame_getpos(self); int oldlen16=ame_getlen(self); VALUE oldsrc16=ame_getsrc(self); int fail16=0;
ame_setsrc(self,bind_aget(bind,51/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDataflow,0)));
 it=rb_funcall(self,s_visit_Dataflowcb_35Dataflow,1,bind); 
 bind_aset(bind,52/*autovar*/,it); it=rb_funcall(self,s_visit_Dataflowcb_36Dataflow,1,bind); int oldpos25=ame_getpos(self); int oldlen17=ame_getlen(self); VALUE oldsrc17=ame_getsrc(self); int fail17=0;
ame_setsrc(self,bind_aget(bind,52/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDataflow,0)));
   it=AmethystCore_anything(self ); FAILTEST(pass17);
 bind_aset(bind,53/*autovar*/,it); int oldpos26=ame_getpos(self); int oldlen18=ame_getlen(self); VALUE oldsrc18=ame_getsrc(self); int fail18=0;
ame_setsrc(self,bind_aget(bind,53/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDataflow,0)));
 it=rb_ary_new3(0);
 bind_aset(bind,54/*autovar*/,it); int oldpos27; while(1){oldpos27=ame_getpos(self);   it=Dataflow_traverse_item(self ); FAILTEST(break9);
 bind_aset(bind,55/*autovar*/,it); it=rb_funcall(self,s_visit_Dataflowcb_37Dataflow,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos27=ame_getpos(self);goto break9;} } } break9: ame_setstop(self,Qnil);  ame_setpos(self,oldpos27); it=bind_aget(bind,54/*autovar*/);
 bind_aset(bind,8/*var*/,it);   it=Amethyst_eof(self ); FAILTEST(pass18);
	goto success18;
	pass18: fail18=1;
	success18: ame_setsrc(self,oldsrc18); ame_setpos(self,oldpos26); ame_setlen(self,oldlen18);
	if(fail18) goto pass17;
  it=Amethyst_eof(self ); FAILTEST(pass17);
	goto success17;
	pass17: fail17=1;
	success17: ame_setsrc(self,oldsrc17); ame_setpos(self,oldpos25); ame_setlen(self,oldlen17);
	if(fail17) goto pass16;
it=rb_funcall(self,s_visit_Dataflowcb_38Dataflow,1,bind); 
 bind_aset(bind,56/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass16);
	goto success16;
	pass16: fail16=1;
	success16: ame_setsrc(self,oldsrc16); ame_setpos(self,oldpos24); ame_setlen(self,oldlen16);
	if(fail16) goto fail;
it=bind_aget(bind,56/*autovar*/);
 bind_aset(bind,10/*_result*/,it);  break;case 9:;   it=AmethystCore_anything(self ); FAILTEST(fail);
 bind_aset(bind,57/*autovar*/,it); int oldpos28=ame_getpos(self); int oldlen19=ame_getlen(self); VALUE oldsrc19=ame_getsrc(self); int fail19=0;
ame_setsrc(self,bind_aget(bind,57/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDataflow,0)));
 it=rb_ary_new3(0);
 bind_aset(bind,58/*alts*/,it); it=rb_ary_new3(0);
 bind_aset(bind,40/*join*/,it); it=rb_funcall(self,s_visit_Dataflowcb_22Dataflow,1,bind); 
 bind_aset(bind,41/*old*/,it); it=rb_ary_new3(0);
 bind_aset(bind,59/*autovar*/,it); int oldpos29; while(1){oldpos29=ame_getpos(self); it=rb_funcall(self,s_visit_Dataflowcb_23Dataflow,1,bind);   it=AmethystCore_anything(self ); FAILTEST(break10);
 bind_aset(bind,60/*autovar*/,it); int oldpos30=ame_getpos(self); int oldlen20=ame_getlen(self); VALUE oldsrc20=ame_getsrc(self); int fail20=0;
ame_setsrc(self,bind_aget(bind,60/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDataflow,0)));
   it=AmethystCore_anything(self ); FAILTEST(pass20);
 bind_aset(bind,61/*pred*/,it);   it=Dataflow_traverse_item(self ); FAILTEST(pass20);
 bind_aset(bind,62/*a*/,it); it=rb_funcall(self,s_visit_Dataflowcb_39Dataflow,1,bind);   it=Amethyst_eof(self ); FAILTEST(pass20);
	goto success20;
	pass20: fail20=1;
	success20: ame_setsrc(self,oldsrc20); ame_setpos(self,oldpos30); ame_setlen(self,oldlen20);
	if(fail20) goto break10;
it=rb_funcall(self,s_visit_Dataflowcb_25Dataflow,1,bind); 
 bind_aset(bind,63/*autovar*/,it); it=rb_funcall(self,s_visit_Dataflowcb_40Dataflow,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos29=ame_getpos(self);goto break10;} } } break10: ame_setstop(self,Qnil);  ame_setpos(self,oldpos29); it=bind_aget(bind,59/*autovar*/);it=rb_funcall(self,s_visit_Dataflowcb_27Dataflow,1,bind); it=rb_funcall(self,s_visit_Dataflowcb_41Dataflow,1,bind); 
 bind_aset(bind,64/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass19);
	goto success19;
	pass19: fail19=1;
	success19: ame_setsrc(self,oldsrc19); ame_setpos(self,oldpos28); ame_setlen(self,oldlen19);
	if(fail19) goto fail;
it=bind_aget(bind,64/*autovar*/);
 bind_aset(bind,10/*_result*/,it);  break;}it=bind_aget(bind,10/*_result*/);
return it;
fail: return failobj; }VALUE cls_Dead_Code_Deleter3;
VALUE AmethystCore_anything(VALUE self );
VALUE Amethyst_clas(VALUE self ,VALUE);
VALUE Amethyst_eof(VALUE self );
VALUE Amethyst_fails(VALUE self );
VALUE Dead_Code_Deleter3_root(VALUE self );
VALUE Dead_Code_Deleter3_traverse(VALUE self );
VALUE Dead_Code_Deleter3_traverse_item(VALUE self );
VALUE Dead_Code_Deleter3_visit(VALUE self );
VALUE switchhashDead_Code_Deleter31;
VALUE switchhashDead_Code_Deleter32;
VALUE switchhashDead_Code_Deleter33;
static VALUE c_280;
static VALUE s_root_Dead_Code_Deleter3cb_1Dead_Code_Deleter3;
static VALUE s_root_Dead_Code_Deleter3cb_2Dead_Code_Deleter3;
static VALUE s_root_Dead_Code_Deleter3cb_3Dead_Code_Deleter3;
static VALUE s_root_Dead_Code_Deleter3cb_4Dead_Code_Deleter3;
static VALUE s_sizeDead_Code_Deleter3;
static VALUE s_traverse_Dead_Code_Deleter3cb_1Dead_Code_Deleter3;
static VALUE s_traverse_Dead_Code_Deleter3cb_2Dead_Code_Deleter3;
static VALUE s_traverse_Dead_Code_Deleter3cb_3Dead_Code_Deleter3;
static VALUE s_traverse_Dead_Code_Deleter3cb_4Dead_Code_Deleter3;
static VALUE s_traverse_Dead_Code_Deleter3cb_5Dead_Code_Deleter3;
static VALUE s_traverse_Dead_Code_Deleter3cb_6Dead_Code_Deleter3;
static VALUE s_traverse_Dead_Code_Deleter3cb_7Dead_Code_Deleter3;
static VALUE s_traverse_Dead_Code_Deleter3cb_8Dead_Code_Deleter3;
static VALUE s_traverse_item_Dead_Code_Deleter3cb_1Dead_Code_Deleter3;
static VALUE s_traverse_item_Dead_Code_Deleter3cb_2Dead_Code_Deleter3;
static VALUE s_traverse_item_Dead_Code_Deleter3cb_3Dead_Code_Deleter3;
static VALUE s_visit_Dead_Code_Deleter3cb_10Dead_Code_Deleter3;
static VALUE s_visit_Dead_Code_Deleter3cb_1Dead_Code_Deleter3;
static VALUE s_visit_Dead_Code_Deleter3cb_2Dead_Code_Deleter3;
static VALUE s_visit_Dead_Code_Deleter3cb_3Dead_Code_Deleter3;
static VALUE s_visit_Dead_Code_Deleter3cb_4Dead_Code_Deleter3;
static VALUE s_visit_Dead_Code_Deleter3cb_5Dead_Code_Deleter3;
static VALUE s_visit_Dead_Code_Deleter3cb_6Dead_Code_Deleter3;
static VALUE s_visit_Dead_Code_Deleter3cb_7Dead_Code_Deleter3;
static VALUE s_visit_Dead_Code_Deleter3cb_8Dead_Code_Deleter3;
static VALUE s_visit_Dead_Code_Deleter3cb_9Dead_Code_Deleter3;
VALUE Dead_Code_Deleter3_root(VALUE self ){VALUE vals[0]; VALUE bind=bind_new2(5);  int x;VALUE arg0,arg1,arg2,arg3;VALUE it;

it=rb_funcall(self,s_root_Dead_Code_Deleter3cb_1Dead_Code_Deleter3,1,bind); 
 bind_aset(bind,0/*autovar*/,it); it=rb_funcall(self,s_root_Dead_Code_Deleter3cb_2Dead_Code_Deleter3,1,bind); int oldpos1=ame_getpos(self); int oldlen1=ame_getlen(self); VALUE oldsrc1=ame_getsrc(self); int fail1=0;
ame_setsrc(self,bind_aget(bind,0/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDead_Code_Deleter3,0)));
  it=c_280; arg0=it; it=Amethyst_clas(self ,arg0); FAILTEST(pass1);
 bind_aset(bind,1/*autovar*/,it); int oldpos2=ame_getpos(self); int oldlen2=ame_getlen(self); VALUE oldsrc2=ame_getsrc(self); int fail2=0;
ame_setsrc(self,bind_aget(bind,1/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDead_Code_Deleter3,0)));
 it=rb_funcall(self,s_root_Dead_Code_Deleter3cb_3Dead_Code_Deleter3,1,bind); it=rb_funcall(self,s_root_Dead_Code_Deleter3cb_4Dead_Code_Deleter3,1,bind);   it=Dead_Code_Deleter3_traverse(self ); FAILTEST(pass2);
 bind_aset(bind,2/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass2);
	goto success2;
	pass2: fail2=1;
	success2: ame_setsrc(self,oldsrc2); ame_setpos(self,oldpos2); ame_setlen(self,oldlen2);
	if(fail2) goto pass1;
it=bind_aget(bind,2/*autovar*/);
 bind_aset(bind,3/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass1);
	goto success1;
	pass1: fail1=1;
	success1: ame_setsrc(self,oldsrc1); ame_setpos(self,oldpos1); ame_setlen(self,oldlen1);
	if(fail1) goto fail;
it=bind_aget(bind,3/*autovar*/);
 bind_aset(bind,4/*_result*/,it); it=bind_aget(bind,4/*_result*/);
return it;
fail: return failobj; }
VALUE Dead_Code_Deleter3_traverse(VALUE self ){VALUE vals[0]; VALUE bind=bind_new2(15);  int x;VALUE arg0,arg1,arg2,arg3;VALUE it;

it=rb_ary_new3(0);
 bind_aset(bind,0/*autovar*/,it); int oldpos1; while(1){oldpos1=ame_getpos(self);   it=AmethystCore_anything(self ); FAILTEST(break1);
 bind_aset(bind,1/*autovar*/,it); it=rb_funcall(self,s_traverse_Dead_Code_Deleter3cb_1Dead_Code_Deleter3,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos1=ame_getpos(self);goto break1;} } } break1: ame_setstop(self,Qnil);  ame_setpos(self,oldpos1); it=bind_aget(bind,0/*autovar*/);it=rb_funcall(self,s_traverse_Dead_Code_Deleter3cb_2Dead_Code_Deleter3,1,bind); 
 bind_aset(bind,2/*oldchanged*/,it); it=rb_funcall(self,s_root_Dead_Code_Deleter3cb_1Dead_Code_Deleter3,1,bind); 
 bind_aset(bind,3/*this*/,it); it=Qnil;
 bind_aset(bind,4/*clon*/,it); it=Qfalse;
 bind_aset(bind,5/*changed*/,it); it=rb_funcall(self,s_traverse_Dead_Code_Deleter3cb_3Dead_Code_Deleter3,1,bind); 
 bind_aset(bind,6/*autovar*/,it); it=rb_funcall(self,s_traverse_Dead_Code_Deleter3cb_4Dead_Code_Deleter3,1,bind); int oldpos2=ame_getpos(self); int oldlen1=ame_getlen(self); VALUE oldsrc1=ame_getsrc(self); int fail1=0;
ame_setsrc(self,bind_aget(bind,6/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDead_Code_Deleter3,0)));
   it=AmethystCore_anything(self ); FAILTEST(pass1);
 bind_aset(bind,7/*autovar*/,it); int oldpos3=ame_getpos(self); int oldlen2=ame_getlen(self); VALUE oldsrc2=ame_getsrc(self); int fail2=0;
ame_setsrc(self,bind_aget(bind,7/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDead_Code_Deleter3,0)));
 it=rb_ary_new3(0);
 bind_aset(bind,8/*autovar*/,it); int oldpos4; while(1){oldpos4=ame_getpos(self);   it=AmethystCore_anything(self ); FAILTEST(break2);
 bind_aset(bind,9/*autovar*/,it); int oldpos5=ame_getpos(self); int oldlen3=ame_getlen(self); VALUE oldsrc3=ame_getsrc(self); int fail3=0;
ame_setsrc(self,bind_aget(bind,9/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDead_Code_Deleter3,0)));
   it=AmethystCore_anything(self ); FAILTEST(pass3);
 bind_aset(bind,10/*key*/,it); it=rb_funcall(self,s_traverse_Dead_Code_Deleter3cb_5Dead_Code_Deleter3,1,bind);   it=Dead_Code_Deleter3_traverse_item(self ); FAILTEST(pass3);
 bind_aset(bind,11/*val*/,it); it=rb_funcall(self,s_traverse_Dead_Code_Deleter3cb_6Dead_Code_Deleter3,1,bind); 
 bind_aset(bind,12/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass3);
	goto success3;
	pass3: fail3=1;
	success3: ame_setsrc(self,oldsrc3); ame_setpos(self,oldpos5); ame_setlen(self,oldlen3);
	if(fail3) goto break2;
it=bind_aget(bind,12/*autovar*/);
 bind_aset(bind,13/*autovar*/,it); it=rb_funcall(self,s_traverse_Dead_Code_Deleter3cb_7Dead_Code_Deleter3,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos4=ame_getpos(self);goto break2;} } } break2: ame_setstop(self,Qnil);  ame_setpos(self,oldpos4); it=bind_aget(bind,8/*autovar*/);  it=Amethyst_eof(self ); FAILTEST(pass2);
	goto success2;
	pass2: fail2=1;
	success2: ame_setsrc(self,oldsrc2); ame_setpos(self,oldpos3); ame_setlen(self,oldlen2);
	if(fail2) goto pass1;
  it=Amethyst_eof(self ); FAILTEST(pass1);
	goto success1;
	pass1: fail1=1;
	success1: ame_setsrc(self,oldsrc1); ame_setpos(self,oldpos2); ame_setlen(self,oldlen1);
	if(fail1) goto fail;
it=rb_funcall(self,s_traverse_Dead_Code_Deleter3cb_8Dead_Code_Deleter3,1,bind); 
 bind_aset(bind,14/*_result*/,it); it=bind_aget(bind,14/*_result*/);
return it;
fail: return failobj; }
VALUE Dead_Code_Deleter3_traverse_item(VALUE self ){VALUE vals[0]; VALUE bind=bind_new2(10);  int x;VALUE arg0,arg1,arg2,arg3;VALUE it;

unsigned char chr1=FIX2LONG(rb_hash_aref(switchhashDead_Code_Deleter33,rb_obj_class(ame_curobj(self))));  switch(chr1){case 0:; int oldpos1=ame_getpos(self);
alt1_1: ame_setpos(self,oldpos1);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
   it=Dead_Code_Deleter3_visit(self ); FAILTEST(alt1_2);
 bind_aset(bind,0/*a*/,it); it=rb_funcall(self,s_traverse_item_Dead_Code_Deleter3cb_1Dead_Code_Deleter3,1,bind); it=bind_aget(bind,0/*a*/);
 bind_aset(bind,1/*_result*/,it);  
ame_setcut(self,Qnil);goto accept1;
alt1_2: ame_setpos(self,oldpos1);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
   it=AmethystCore_anything(self ); FAILTEST(alt1_3);
 bind_aset(bind,2/*autovar*/,it); int oldpos2=ame_getpos(self); int oldlen1=ame_getlen(self); VALUE oldsrc1=ame_getsrc(self); int fail1=0;
ame_setsrc(self,bind_aget(bind,2/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDead_Code_Deleter3,0)));
   it=Dead_Code_Deleter3_traverse(self ); FAILTEST(pass1);
 bind_aset(bind,3/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass1);
	goto success1;
	pass1: fail1=1;
	success1: ame_setsrc(self,oldsrc1); ame_setpos(self,oldpos2); ame_setlen(self,oldlen1);
	if(fail1) goto alt1_3;
it=bind_aget(bind,3/*autovar*/);
 bind_aset(bind,1/*_result*/,it);  
ame_setcut(self,Qnil);goto accept1;
alt1_3: ame_setpos(self,oldpos1);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
   it=AmethystCore_anything(self ); FAILTEST(alt1_4);
 bind_aset(bind,1/*_result*/,it);  
ame_setcut(self,Qnil);goto accept1;
  alt1_4:  ame_setpos(self,oldpos1); goto fail;
 accept1:;
 break;case 1:; int oldpos3=ame_getpos(self);
alt2_1: ame_setpos(self,oldpos3);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
   it=Dead_Code_Deleter3_visit(self ); FAILTEST(alt2_2);
 bind_aset(bind,0/*a*/,it); it=rb_funcall(self,s_traverse_item_Dead_Code_Deleter3cb_1Dead_Code_Deleter3,1,bind); it=bind_aget(bind,0/*a*/);
 bind_aset(bind,1/*_result*/,it);  
ame_setcut(self,Qnil);goto accept2;
alt2_2: ame_setpos(self,oldpos3);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
   it=AmethystCore_anything(self ); FAILTEST(alt2_3);
 bind_aset(bind,4/*autovar*/,it); int oldpos4=ame_getpos(self); int oldlen2=ame_getlen(self); VALUE oldsrc2=ame_getsrc(self); int fail2=0;
ame_setsrc(self,bind_aget(bind,4/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDead_Code_Deleter3,0)));
 it=rb_ary_new3(0);
 bind_aset(bind,5/*ar*/,it); it=rb_ary_new3(0);
 bind_aset(bind,6/*autovar*/,it); int oldpos5; while(1){oldpos5=ame_getpos(self);   it=Dead_Code_Deleter3_traverse_item(self ); FAILTEST(break1);
 bind_aset(bind,7/*it*/,it); it=rb_funcall(self,s_traverse_item_Dead_Code_Deleter3cb_2Dead_Code_Deleter3,1,bind); 
 bind_aset(bind,8/*autovar*/,it); it=rb_funcall(self,s_traverse_item_Dead_Code_Deleter3cb_3Dead_Code_Deleter3,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos5=ame_getpos(self);goto break1;} } } break1: ame_setstop(self,Qnil);  ame_setpos(self,oldpos5); it=bind_aget(bind,6/*autovar*/);it=bind_aget(bind,5/*ar*/);
 bind_aset(bind,9/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass2);
	goto success2;
	pass2: fail2=1;
	success2: ame_setsrc(self,oldsrc2); ame_setpos(self,oldpos4); ame_setlen(self,oldlen2);
	if(fail2) goto alt2_3;
it=bind_aget(bind,9/*autovar*/);
 bind_aset(bind,1/*_result*/,it);  
ame_setcut(self,Qnil);goto accept2;
alt2_3: ame_setpos(self,oldpos3);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
   it=AmethystCore_anything(self ); FAILTEST(alt2_4);
 bind_aset(bind,1/*_result*/,it);  
ame_setcut(self,Qnil);goto accept2;
  alt2_4:  ame_setpos(self,oldpos3); goto fail;
 accept2:;
 break;case 2:; int oldpos6=ame_getpos(self);
alt3_1: ame_setpos(self,oldpos6);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
   it=Dead_Code_Deleter3_visit(self ); FAILTEST(alt3_2);
 bind_aset(bind,0/*a*/,it); it=rb_funcall(self,s_traverse_item_Dead_Code_Deleter3cb_1Dead_Code_Deleter3,1,bind); it=bind_aget(bind,0/*a*/);
 bind_aset(bind,1/*_result*/,it);  
ame_setcut(self,Qnil);goto accept3;
alt3_2: ame_setpos(self,oldpos6);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
   it=AmethystCore_anything(self ); FAILTEST(alt3_3);
 bind_aset(bind,1/*_result*/,it);  
ame_setcut(self,Qnil);goto accept3;
  alt3_3:  ame_setpos(self,oldpos6); goto fail;
 accept3:;
 break;}it=bind_aget(bind,1/*_result*/);
return it;
fail: return failobj; }
VALUE Dead_Code_Deleter3_visit(VALUE self ){VALUE vals[0]; VALUE bind=bind_new2(21);  int x;VALUE arg0,arg1,arg2,arg3;VALUE it;

unsigned char chr1=FIX2LONG(rb_hash_aref(switchhashDead_Code_Deleter32,rb_obj_class(ame_curobj(self))));  switch(chr1){case 0:;case 3:;case 5:;case 6:; unsigned char chr2=FIX2LONG(rb_hash_aref(switchhashDead_Code_Deleter31,rb_obj_class(ame_curobj(self))));  switch(chr2){case 0:;case 1:;case 2:;   it=AmethystCore_anything(self ); FAILTEST(fail);
 bind_aset(bind,0/*autovar*/,it);  break;case 3:;   it=Amethyst_fails(self ); FAILTEST(fail); break;}int oldpos1=ame_getpos(self); int oldlen1=ame_getlen(self); VALUE oldsrc1=ame_getsrc(self); int fail1=0;
ame_setsrc(self,bind_aget(bind,0/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDead_Code_Deleter3,0)));
 it=rb_funcall(self,s_root_Dead_Code_Deleter3cb_1Dead_Code_Deleter3,1,bind); 
 bind_aset(bind,1/*this*/,it); it=rb_ary_new3(0);
 bind_aset(bind,2/*autovar*/,it); int oldpos2; while(1){oldpos2=ame_getpos(self);   it=AmethystCore_anything(self ); FAILTEST(break1);
 bind_aset(bind,3/*autovar*/,it); it=rb_funcall(self,s_visit_Dead_Code_Deleter3cb_1Dead_Code_Deleter3,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos2=ame_getpos(self);goto break1;} } } break1: ame_setstop(self,Qnil);  ame_setpos(self,oldpos2); it=bind_aget(bind,2/*autovar*/);  it=Amethyst_eof(self ); FAILTEST(pass1);
	goto success1;
	pass1: fail1=1;
	success1: ame_setsrc(self,oldsrc1); ame_setpos(self,oldpos1); ame_setlen(self,oldlen1);
	if(fail1) goto fail;
it=rb_funcall(self,s_visit_Dead_Code_Deleter3cb_2Dead_Code_Deleter3,1,bind); 
 bind_aset(bind,4/*_result*/,it);  break;case 1:;   it=AmethystCore_anything(self ); FAILTEST(fail);
 bind_aset(bind,5/*autovar*/,it); int oldpos3=ame_getpos(self); int oldlen2=ame_getlen(self); VALUE oldsrc2=ame_getsrc(self); int fail2=0;
ame_setsrc(self,bind_aget(bind,5/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDead_Code_Deleter3,0)));
 it=rb_ary_new3(0);
 bind_aset(bind,6/*autovar*/,it); int oldpos4; while(1){oldpos4=ame_getpos(self);   it=AmethystCore_anything(self ); FAILTEST(break2);
 bind_aset(bind,7/*autovar*/,it); it=rb_funcall(self,s_visit_Dead_Code_Deleter3cb_3Dead_Code_Deleter3,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos4=ame_getpos(self);goto break2;} } } break2: ame_setstop(self,Qnil);  ame_setpos(self,oldpos4); it=bind_aget(bind,6/*autovar*/);it=rb_funcall(self,s_root_Dead_Code_Deleter3cb_1Dead_Code_Deleter3,1,bind); 
 bind_aset(bind,8/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass2);
	goto success2;
	pass2: fail2=1;
	success2: ame_setsrc(self,oldsrc2); ame_setpos(self,oldpos3); ame_setlen(self,oldlen2);
	if(fail2) goto fail;
it=bind_aget(bind,8/*autovar*/);
 bind_aset(bind,4/*_result*/,it);  break;case 2:;   it=AmethystCore_anything(self ); FAILTEST(fail);
 bind_aset(bind,9/*autovar*/,it); int oldpos5=ame_getpos(self); int oldlen3=ame_getlen(self); VALUE oldsrc3=ame_getsrc(self); int fail3=0;
ame_setsrc(self,bind_aget(bind,9/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDead_Code_Deleter3,0)));
 it=rb_ary_new3(0);
 bind_aset(bind,10/*autovar*/,it); int oldpos6; while(1){oldpos6=ame_getpos(self);   it=AmethystCore_anything(self ); FAILTEST(break3);
 bind_aset(bind,11/*autovar*/,it); it=rb_funcall(self,s_visit_Dead_Code_Deleter3cb_4Dead_Code_Deleter3,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos6=ame_getpos(self);goto break3;} } } break3: ame_setstop(self,Qnil);  ame_setpos(self,oldpos6); it=bind_aget(bind,10/*autovar*/);it=rb_funcall(self,s_root_Dead_Code_Deleter3cb_1Dead_Code_Deleter3,1,bind); 
 bind_aset(bind,12/*b*/,it); it=rb_funcall(self,s_visit_Dead_Code_Deleter3cb_5Dead_Code_Deleter3,1,bind);   it=Dead_Code_Deleter3_traverse(self ); FAILTEST(pass3);
 bind_aset(bind,13/*autovar*/,it); int oldpos7=ame_getpos(self); int oldlen4=ame_getlen(self); VALUE oldsrc4=ame_getsrc(self); int fail4=0;
ame_setsrc(self,bind_aget(bind,13/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDead_Code_Deleter3,0)));
 it=rb_ary_new3(0);
 bind_aset(bind,14/*autovar*/,it); int oldpos8; while(1){oldpos8=ame_getpos(self);   it=AmethystCore_anything(self ); FAILTEST(break4);
 bind_aset(bind,15/*autovar*/,it); it=rb_funcall(self,s_visit_Dead_Code_Deleter3cb_6Dead_Code_Deleter3,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos8=ame_getpos(self);goto break4;} } } break4: ame_setstop(self,Qnil);  ame_setpos(self,oldpos8); it=bind_aget(bind,14/*autovar*/);it=rb_funcall(self,s_visit_Dead_Code_Deleter3cb_7Dead_Code_Deleter3,1,bind); it=rb_funcall(self,s_visit_Dead_Code_Deleter3cb_8Dead_Code_Deleter3,1,bind); 
 bind_aset(bind,16/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass4);
	goto success4;
	pass4: fail4=1;
	success4: ame_setsrc(self,oldsrc4); ame_setpos(self,oldpos7); ame_setlen(self,oldlen4);
	if(fail4) goto pass3;
it=bind_aget(bind,16/*autovar*/);
 bind_aset(bind,17/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass3);
	goto success3;
	pass3: fail3=1;
	success3: ame_setsrc(self,oldsrc3); ame_setpos(self,oldpos5); ame_setlen(self,oldlen3);
	if(fail3) goto fail;
it=bind_aget(bind,17/*autovar*/);
 bind_aset(bind,4/*_result*/,it);  break;case 4:;   it=AmethystCore_anything(self ); FAILTEST(fail);
 bind_aset(bind,18/*autovar*/,it); int oldpos9=ame_getpos(self); int oldlen5=ame_getlen(self); VALUE oldsrc5=ame_getsrc(self); int fail5=0;
ame_setsrc(self,bind_aget(bind,18/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeDead_Code_Deleter3,0)));
 it=rb_ary_new3(0);
 bind_aset(bind,19/*autovar*/,it); int oldpos10; while(1){oldpos10=ame_getpos(self);   it=AmethystCore_anything(self ); FAILTEST(break5);
 bind_aset(bind,20/*autovar*/,it); it=rb_funcall(self,s_visit_Dead_Code_Deleter3cb_9Dead_Code_Deleter3,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos10=ame_getpos(self);goto break5;} } } break5: ame_setstop(self,Qnil);  ame_setpos(self,oldpos10); it=bind_aget(bind,19/*autovar*/);it=rb_funcall(self,s_root_Dead_Code_Deleter3cb_1Dead_Code_Deleter3,1,bind); 
 bind_aset(bind,1/*this*/,it);   it=Amethyst_eof(self ); FAILTEST(pass5);
	goto success5;
	pass5: fail5=1;
	success5: ame_setsrc(self,oldsrc5); ame_setpos(self,oldpos9); ame_setlen(self,oldlen5);
	if(fail5) goto fail;
it=rb_funcall(self,s_visit_Dead_Code_Deleter3cb_10Dead_Code_Deleter3,1,bind); 
 bind_aset(bind,4/*_result*/,it);  break;}it=bind_aget(bind,4/*_result*/);
return it;
fail: return failobj; }VALUE cls_Forget_SSA;
VALUE AmethystCore_anything(VALUE self );
VALUE Amethyst_clas(VALUE self ,VALUE);
VALUE Amethyst_eof(VALUE self );
VALUE Forget_SSA_root(VALUE self );
VALUE Forget_SSA_traverse(VALUE self );
VALUE Forget_SSA_traverse_item(VALUE self );
VALUE Forget_SSA_visit(VALUE self );
VALUE switchhashForget_SSA1;
static VALUE c_292;
static VALUE c_293;
static VALUE s_root_Forget_SSAcb_1Forget_SSA;
static VALUE s_root_Forget_SSAcb_2Forget_SSA;
static VALUE s_sizeForget_SSA;
static VALUE s_traverse_Forget_SSAcb_1Forget_SSA;
static VALUE s_traverse_Forget_SSAcb_2Forget_SSA;
static VALUE s_traverse_Forget_SSAcb_3Forget_SSA;
static VALUE s_traverse_Forget_SSAcb_4Forget_SSA;
static VALUE s_traverse_Forget_SSAcb_5Forget_SSA;
static VALUE s_traverse_Forget_SSAcb_6Forget_SSA;
static VALUE s_traverse_Forget_SSAcb_7Forget_SSA;
static VALUE s_traverse_Forget_SSAcb_8Forget_SSA;
static VALUE s_traverse_item_Forget_SSAcb_1Forget_SSA;
static VALUE s_traverse_item_Forget_SSAcb_2Forget_SSA;
static VALUE s_traverse_item_Forget_SSAcb_3Forget_SSA;
static VALUE s_visit_Forget_SSAcb_1Forget_SSA;
static VALUE s_visit_Forget_SSAcb_2Forget_SSA;
VALUE Forget_SSA_root(VALUE self ){VALUE vals[0]; VALUE bind=bind_new2(5);  int x;VALUE arg0,arg1,arg2,arg3;VALUE it;

it=rb_funcall(self,s_root_Forget_SSAcb_1Forget_SSA,1,bind); 
 bind_aset(bind,0/*autovar*/,it); it=rb_funcall(self,s_root_Forget_SSAcb_2Forget_SSA,1,bind); int oldpos1=ame_getpos(self); int oldlen1=ame_getlen(self); VALUE oldsrc1=ame_getsrc(self); int fail1=0;
ame_setsrc(self,bind_aget(bind,0/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeForget_SSA,0)));
  it=c_292; arg0=it; it=Amethyst_clas(self ,arg0); FAILTEST(pass1);
 bind_aset(bind,1/*autovar*/,it); int oldpos2=ame_getpos(self); int oldlen2=ame_getlen(self); VALUE oldsrc2=ame_getsrc(self); int fail2=0;
ame_setsrc(self,bind_aget(bind,1/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeForget_SSA,0)));
   it=Forget_SSA_traverse(self ); FAILTEST(pass2);
 bind_aset(bind,2/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass2);
	goto success2;
	pass2: fail2=1;
	success2: ame_setsrc(self,oldsrc2); ame_setpos(self,oldpos2); ame_setlen(self,oldlen2);
	if(fail2) goto pass1;
it=bind_aget(bind,2/*autovar*/);
 bind_aset(bind,3/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass1);
	goto success1;
	pass1: fail1=1;
	success1: ame_setsrc(self,oldsrc1); ame_setpos(self,oldpos1); ame_setlen(self,oldlen1);
	if(fail1) goto fail;
it=bind_aget(bind,3/*autovar*/);
 bind_aset(bind,4/*_result*/,it); it=bind_aget(bind,4/*_result*/);
return it;
fail: return failobj; }
VALUE Forget_SSA_traverse(VALUE self ){VALUE vals[0]; VALUE bind=bind_new2(15);  int x;VALUE arg0,arg1,arg2,arg3;VALUE it;

it=rb_ary_new3(0);
 bind_aset(bind,0/*autovar*/,it); int oldpos1; while(1){oldpos1=ame_getpos(self);   it=AmethystCore_anything(self ); FAILTEST(break1);
 bind_aset(bind,1/*autovar*/,it); it=rb_funcall(self,s_traverse_Forget_SSAcb_1Forget_SSA,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos1=ame_getpos(self);goto break1;} } } break1: ame_setstop(self,Qnil);  ame_setpos(self,oldpos1); it=bind_aget(bind,0/*autovar*/);it=rb_funcall(self,s_traverse_Forget_SSAcb_2Forget_SSA,1,bind); 
 bind_aset(bind,2/*oldchanged*/,it); it=rb_funcall(self,s_root_Forget_SSAcb_1Forget_SSA,1,bind); 
 bind_aset(bind,3/*this*/,it); it=Qnil;
 bind_aset(bind,4/*clon*/,it); it=Qfalse;
 bind_aset(bind,5/*changed*/,it); it=rb_funcall(self,s_traverse_Forget_SSAcb_3Forget_SSA,1,bind); 
 bind_aset(bind,6/*autovar*/,it); it=rb_funcall(self,s_traverse_Forget_SSAcb_4Forget_SSA,1,bind); int oldpos2=ame_getpos(self); int oldlen1=ame_getlen(self); VALUE oldsrc1=ame_getsrc(self); int fail1=0;
ame_setsrc(self,bind_aget(bind,6/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeForget_SSA,0)));
   it=AmethystCore_anything(self ); FAILTEST(pass1);
 bind_aset(bind,7/*autovar*/,it); int oldpos3=ame_getpos(self); int oldlen2=ame_getlen(self); VALUE oldsrc2=ame_getsrc(self); int fail2=0;
ame_setsrc(self,bind_aget(bind,7/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeForget_SSA,0)));
 it=rb_ary_new3(0);
 bind_aset(bind,8/*autovar*/,it); int oldpos4; while(1){oldpos4=ame_getpos(self);   it=AmethystCore_anything(self ); FAILTEST(break2);
 bind_aset(bind,9/*autovar*/,it); int oldpos5=ame_getpos(self); int oldlen3=ame_getlen(self); VALUE oldsrc3=ame_getsrc(self); int fail3=0;
ame_setsrc(self,bind_aget(bind,9/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeForget_SSA,0)));
   it=AmethystCore_anything(self ); FAILTEST(pass3);
 bind_aset(bind,10/*key*/,it); it=rb_funcall(self,s_traverse_Forget_SSAcb_5Forget_SSA,1,bind);   it=Forget_SSA_traverse_item(self ); FAILTEST(pass3);
 bind_aset(bind,11/*val*/,it); it=rb_funcall(self,s_traverse_Forget_SSAcb_6Forget_SSA,1,bind); 
 bind_aset(bind,12/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass3);
	goto success3;
	pass3: fail3=1;
	success3: ame_setsrc(self,oldsrc3); ame_setpos(self,oldpos5); ame_setlen(self,oldlen3);
	if(fail3) goto break2;
it=bind_aget(bind,12/*autovar*/);
 bind_aset(bind,13/*autovar*/,it); it=rb_funcall(self,s_traverse_Forget_SSAcb_7Forget_SSA,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos4=ame_getpos(self);goto break2;} } } break2: ame_setstop(self,Qnil);  ame_setpos(self,oldpos4); it=bind_aget(bind,8/*autovar*/);  it=Amethyst_eof(self ); FAILTEST(pass2);
	goto success2;
	pass2: fail2=1;
	success2: ame_setsrc(self,oldsrc2); ame_setpos(self,oldpos3); ame_setlen(self,oldlen2);
	if(fail2) goto pass1;
  it=Amethyst_eof(self ); FAILTEST(pass1);
	goto success1;
	pass1: fail1=1;
	success1: ame_setsrc(self,oldsrc1); ame_setpos(self,oldpos2); ame_setlen(self,oldlen1);
	if(fail1) goto fail;
it=rb_funcall(self,s_traverse_Forget_SSAcb_8Forget_SSA,1,bind); 
 bind_aset(bind,14/*_result*/,it); it=bind_aget(bind,14/*_result*/);
return it;
fail: return failobj; }
VALUE Forget_SSA_traverse_item(VALUE self ){VALUE vals[0]; VALUE bind=bind_new2(10);  int x;VALUE arg0,arg1,arg2,arg3;VALUE it;

unsigned char chr1=FIX2LONG(rb_hash_aref(switchhashForget_SSA1,rb_obj_class(ame_curobj(self))));  switch(chr1){case 0:; int oldpos1=ame_getpos(self);
alt1_1: ame_setpos(self,oldpos1);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
   it=Forget_SSA_visit(self ); FAILTEST(alt1_2);
 bind_aset(bind,0/*a*/,it); it=rb_funcall(self,s_traverse_item_Forget_SSAcb_1Forget_SSA,1,bind); it=bind_aget(bind,0/*a*/);
 bind_aset(bind,1/*_result*/,it);  
ame_setcut(self,Qnil);goto accept1;
alt1_2: ame_setpos(self,oldpos1);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
   it=AmethystCore_anything(self ); FAILTEST(alt1_3);
 bind_aset(bind,2/*autovar*/,it); int oldpos2=ame_getpos(self); int oldlen1=ame_getlen(self); VALUE oldsrc1=ame_getsrc(self); int fail1=0;
ame_setsrc(self,bind_aget(bind,2/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeForget_SSA,0)));
   it=Forget_SSA_traverse(self ); FAILTEST(pass1);
 bind_aset(bind,3/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass1);
	goto success1;
	pass1: fail1=1;
	success1: ame_setsrc(self,oldsrc1); ame_setpos(self,oldpos2); ame_setlen(self,oldlen1);
	if(fail1) goto alt1_3;
it=bind_aget(bind,3/*autovar*/);
 bind_aset(bind,1/*_result*/,it);  
ame_setcut(self,Qnil);goto accept1;
alt1_3: ame_setpos(self,oldpos1);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
   it=AmethystCore_anything(self ); FAILTEST(alt1_4);
 bind_aset(bind,1/*_result*/,it);  
ame_setcut(self,Qnil);goto accept1;
  alt1_4:  ame_setpos(self,oldpos1); goto fail;
 accept1:;
 break;case 1:; int oldpos3=ame_getpos(self);
alt2_1: ame_setpos(self,oldpos3);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
   it=Forget_SSA_visit(self ); FAILTEST(alt2_2);
 bind_aset(bind,0/*a*/,it); it=rb_funcall(self,s_traverse_item_Forget_SSAcb_1Forget_SSA,1,bind); it=bind_aget(bind,0/*a*/);
 bind_aset(bind,1/*_result*/,it);  
ame_setcut(self,Qnil);goto accept2;
alt2_2: ame_setpos(self,oldpos3);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
   it=AmethystCore_anything(self ); FAILTEST(alt2_3);
 bind_aset(bind,4/*autovar*/,it); int oldpos4=ame_getpos(self); int oldlen2=ame_getlen(self); VALUE oldsrc2=ame_getsrc(self); int fail2=0;
ame_setsrc(self,bind_aget(bind,4/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeForget_SSA,0)));
 it=rb_ary_new3(0);
 bind_aset(bind,5/*ar*/,it); it=rb_ary_new3(0);
 bind_aset(bind,6/*autovar*/,it); int oldpos5; while(1){oldpos5=ame_getpos(self);   it=Forget_SSA_traverse_item(self ); FAILTEST(break1);
 bind_aset(bind,7/*it*/,it); it=rb_funcall(self,s_traverse_item_Forget_SSAcb_2Forget_SSA,1,bind); 
 bind_aset(bind,8/*autovar*/,it); it=rb_funcall(self,s_traverse_item_Forget_SSAcb_3Forget_SSA,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos5=ame_getpos(self);goto break1;} } } break1: ame_setstop(self,Qnil);  ame_setpos(self,oldpos5); it=bind_aget(bind,6/*autovar*/);it=bind_aget(bind,5/*ar*/);
 bind_aset(bind,9/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass2);
	goto success2;
	pass2: fail2=1;
	success2: ame_setsrc(self,oldsrc2); ame_setpos(self,oldpos4); ame_setlen(self,oldlen2);
	if(fail2) goto alt2_3;
it=bind_aget(bind,9/*autovar*/);
 bind_aset(bind,1/*_result*/,it);  
ame_setcut(self,Qnil);goto accept2;
alt2_3: ame_setpos(self,oldpos3);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
   it=AmethystCore_anything(self ); FAILTEST(alt2_4);
 bind_aset(bind,1/*_result*/,it);  
ame_setcut(self,Qnil);goto accept2;
  alt2_4:  ame_setpos(self,oldpos3); goto fail;
 accept2:;
 break;case 2:; int oldpos6=ame_getpos(self);
alt3_1: ame_setpos(self,oldpos6);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
   it=Forget_SSA_visit(self ); FAILTEST(alt3_2);
 bind_aset(bind,0/*a*/,it); it=rb_funcall(self,s_traverse_item_Forget_SSAcb_1Forget_SSA,1,bind); it=bind_aget(bind,0/*a*/);
 bind_aset(bind,1/*_result*/,it);  
ame_setcut(self,Qnil);goto accept3;
alt3_2: ame_setpos(self,oldpos6);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto fail;}
   it=AmethystCore_anything(self ); FAILTEST(alt3_3);
 bind_aset(bind,1/*_result*/,it);  
ame_setcut(self,Qnil);goto accept3;
  alt3_3:  ame_setpos(self,oldpos6); goto fail;
 accept3:;
 break;}it=bind_aget(bind,1/*_result*/);
return it;
fail: return failobj; }
VALUE Forget_SSA_visit(VALUE self ){VALUE vals[0]; VALUE bind=bind_new2(5);  int x;VALUE arg0,arg1,arg2,arg3;VALUE it;

 it=c_293; arg0=it; it=Amethyst_clas(self ,arg0); FAILTEST(fail);
 bind_aset(bind,0/*autovar*/,it); int oldpos1=ame_getpos(self); int oldlen1=ame_getlen(self); VALUE oldsrc1=ame_getsrc(self); int fail1=0;
ame_setsrc(self,bind_aget(bind,0/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),s_sizeForget_SSA,0)));
 it=rb_ary_new3(0);
 bind_aset(bind,1/*autovar*/,it); int oldpos2; while(1){oldpos2=ame_getpos(self);   it=AmethystCore_anything(self ); FAILTEST(break1);
 bind_aset(bind,2/*autovar*/,it); it=rb_funcall(self,s_visit_Forget_SSAcb_1Forget_SSA,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos2=ame_getpos(self);goto break1;} } } break1: ame_setstop(self,Qnil);  ame_setpos(self,oldpos2); it=bind_aget(bind,1/*autovar*/);it=rb_funcall(self,s_visit_Forget_SSAcb_2Forget_SSA,1,bind); 
 bind_aset(bind,3/*autovar*/,it);   it=Amethyst_eof(self ); FAILTEST(pass1);
	goto success1;
	pass1: fail1=1;
	success1: ame_setsrc(self,oldsrc1); ame_setpos(self,oldpos1); ame_setlen(self,oldlen1);
	if(fail1) goto fail;
it=bind_aget(bind,3/*autovar*/);
 bind_aset(bind,4/*_result*/,it); it=bind_aget(bind,4/*_result*/);
return it;
fail: return failobj; }
void Init_dataflow_ssa_c(){ 
 cls_Dataflow=rb_define_class("Dataflow",rb_const_get(rb_cObject,rb_intern("Traverser_Clone2"))); 
failobj=rb_eval_string("FAIL");
c_252=rb_const_get(rb_cObject, rb_intern("Rule"));rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),c_252);
s_root_Dataflowcb_10Dataflow=rb_intern("root_Dataflowcb_10");
s_root_Dataflowcb_11Dataflow=rb_intern("root_Dataflowcb_11");
s_root_Dataflowcb_1Dataflow=rb_intern("root_Dataflowcb_1");
s_root_Dataflowcb_2Dataflow=rb_intern("root_Dataflowcb_2");
s_root_Dataflowcb_3Dataflow=rb_intern("root_Dataflowcb_3");
s_root_Dataflowcb_4Dataflow=rb_intern("root_Dataflowcb_4");
s_root_Dataflowcb_5Dataflow=rb_intern("root_Dataflowcb_5");
s_root_Dataflowcb_6Dataflow=rb_intern("root_Dataflowcb_6");
s_root_Dataflowcb_7Dataflow=rb_intern("root_Dataflowcb_7");
s_root_Dataflowcb_8Dataflow=rb_intern("root_Dataflowcb_8");
s_root_Dataflowcb_9Dataflow=rb_intern("root_Dataflowcb_9");
s_sizeDataflow=rb_intern("size");
s_traverse_Dataflowcb_1Dataflow=rb_intern("traverse_Dataflowcb_1");
s_traverse_Dataflowcb_2Dataflow=rb_intern("traverse_Dataflowcb_2");
s_traverse_Dataflowcb_3Dataflow=rb_intern("traverse_Dataflowcb_3");
s_traverse_Dataflowcb_4Dataflow=rb_intern("traverse_Dataflowcb_4");
s_traverse_Dataflowcb_5Dataflow=rb_intern("traverse_Dataflowcb_5");
s_traverse_Dataflowcb_6Dataflow=rb_intern("traverse_Dataflowcb_6");
s_traverse_Dataflowcb_7Dataflow=rb_intern("traverse_Dataflowcb_7");
s_traverse_Dataflowcb_8Dataflow=rb_intern("traverse_Dataflowcb_8");
s_traverse_item_Dataflowcb_1Dataflow=rb_intern("traverse_item_Dataflowcb_1");
s_traverse_item_Dataflowcb_2Dataflow=rb_intern("traverse_item_Dataflowcb_2");
s_traverse_item_Dataflowcb_3Dataflow=rb_intern("traverse_item_Dataflowcb_3");
s_vars_in_Dataflowcb_10Dataflow=rb_intern("vars_in_Dataflowcb_10");
s_vars_in_Dataflowcb_11Dataflow=rb_intern("vars_in_Dataflowcb_11");
s_vars_in_Dataflowcb_12Dataflow=rb_intern("vars_in_Dataflowcb_12");
s_vars_in_Dataflowcb_13Dataflow=rb_intern("vars_in_Dataflowcb_13");
s_vars_in_Dataflowcb_14Dataflow=rb_intern("vars_in_Dataflowcb_14");
s_vars_in_Dataflowcb_1Dataflow=rb_intern("vars_in_Dataflowcb_1");
s_vars_in_Dataflowcb_2Dataflow=rb_intern("vars_in_Dataflowcb_2");
s_vars_in_Dataflowcb_3Dataflow=rb_intern("vars_in_Dataflowcb_3");
s_vars_in_Dataflowcb_4Dataflow=rb_intern("vars_in_Dataflowcb_4");
s_vars_in_Dataflowcb_5Dataflow=rb_intern("vars_in_Dataflowcb_5");
s_vars_in_Dataflowcb_6Dataflow=rb_intern("vars_in_Dataflowcb_6");
s_vars_in_Dataflowcb_7Dataflow=rb_intern("vars_in_Dataflowcb_7");
s_vars_in_Dataflowcb_8Dataflow=rb_intern("vars_in_Dataflowcb_8");
s_vars_in_Dataflowcb_9Dataflow=rb_intern("vars_in_Dataflowcb_9");
s_visit_Dataflowcb_10Dataflow=rb_intern("visit_Dataflowcb_10");
s_visit_Dataflowcb_11Dataflow=rb_intern("visit_Dataflowcb_11");
s_visit_Dataflowcb_12Dataflow=rb_intern("visit_Dataflowcb_12");
s_visit_Dataflowcb_13Dataflow=rb_intern("visit_Dataflowcb_13");
s_visit_Dataflowcb_14Dataflow=rb_intern("visit_Dataflowcb_14");
s_visit_Dataflowcb_15Dataflow=rb_intern("visit_Dataflowcb_15");
s_visit_Dataflowcb_16Dataflow=rb_intern("visit_Dataflowcb_16");
s_visit_Dataflowcb_17Dataflow=rb_intern("visit_Dataflowcb_17");
s_visit_Dataflowcb_18Dataflow=rb_intern("visit_Dataflowcb_18");
s_visit_Dataflowcb_19Dataflow=rb_intern("visit_Dataflowcb_19");
s_visit_Dataflowcb_1Dataflow=rb_intern("visit_Dataflowcb_1");
s_visit_Dataflowcb_20Dataflow=rb_intern("visit_Dataflowcb_20");
s_visit_Dataflowcb_21Dataflow=rb_intern("visit_Dataflowcb_21");
s_visit_Dataflowcb_22Dataflow=rb_intern("visit_Dataflowcb_22");
s_visit_Dataflowcb_23Dataflow=rb_intern("visit_Dataflowcb_23");
s_visit_Dataflowcb_24Dataflow=rb_intern("visit_Dataflowcb_24");
s_visit_Dataflowcb_25Dataflow=rb_intern("visit_Dataflowcb_25");
s_visit_Dataflowcb_26Dataflow=rb_intern("visit_Dataflowcb_26");
s_visit_Dataflowcb_27Dataflow=rb_intern("visit_Dataflowcb_27");
s_visit_Dataflowcb_28Dataflow=rb_intern("visit_Dataflowcb_28");
s_visit_Dataflowcb_29Dataflow=rb_intern("visit_Dataflowcb_29");
s_visit_Dataflowcb_2Dataflow=rb_intern("visit_Dataflowcb_2");
s_visit_Dataflowcb_30Dataflow=rb_intern("visit_Dataflowcb_30");
s_visit_Dataflowcb_31Dataflow=rb_intern("visit_Dataflowcb_31");
s_visit_Dataflowcb_32Dataflow=rb_intern("visit_Dataflowcb_32");
s_visit_Dataflowcb_33Dataflow=rb_intern("visit_Dataflowcb_33");
s_visit_Dataflowcb_34Dataflow=rb_intern("visit_Dataflowcb_34");
s_visit_Dataflowcb_35Dataflow=rb_intern("visit_Dataflowcb_35");
s_visit_Dataflowcb_36Dataflow=rb_intern("visit_Dataflowcb_36");
s_visit_Dataflowcb_37Dataflow=rb_intern("visit_Dataflowcb_37");
s_visit_Dataflowcb_38Dataflow=rb_intern("visit_Dataflowcb_38");
s_visit_Dataflowcb_39Dataflow=rb_intern("visit_Dataflowcb_39");
s_visit_Dataflowcb_3Dataflow=rb_intern("visit_Dataflowcb_3");
s_visit_Dataflowcb_40Dataflow=rb_intern("visit_Dataflowcb_40");
s_visit_Dataflowcb_41Dataflow=rb_intern("visit_Dataflowcb_41");
s_visit_Dataflowcb_4Dataflow=rb_intern("visit_Dataflowcb_4");
s_visit_Dataflowcb_5Dataflow=rb_intern("visit_Dataflowcb_5");
s_visit_Dataflowcb_6Dataflow=rb_intern("visit_Dataflowcb_6");
s_visit_Dataflowcb_7Dataflow=rb_intern("visit_Dataflowcb_7");
s_visit_Dataflowcb_8Dataflow=rb_intern("visit_Dataflowcb_8");
s_visit_Dataflowcb_9Dataflow=rb_intern("visit_Dataflowcb_9");
switchhashDataflow1=rb_eval_string("Hash.new{|h,k|\nnext h[k]=0 if k<=Act\nnext h[k]=1 if k<=Apply\nnext h[k]=2 if k<=Bind\nnext h[k]=3 if k<=Local\nnext h[k]=4 if k<=Lookahead\nnext h[k]=5 if k<=Many\nnext h[k]=6 if k<=Or\nnext h[k]=7 if k<=Pass\nnext h[k]=8 if k<=Result\nnext h[k]=9 if k<=Switch\nnext h[k]=10 if k<=Object\n}\n");rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),switchhashDataflow1);
switchhashDataflow2=rb_eval_string("Hash.new{|h,k|\nnext h[k]=0 if k<=Act\nnext h[k]=1 if k<=Args\nnext h[k]=2 if k<=Bind\nnext h[k]=3 if k<=CAct\nnext h[k]=4 if k<=Global\nnext h[k]=5 if k<=Key\nnext h[k]=6 if k<=Local\nnext h[k]=7 if k<=Result\nnext h[k]=8 if k<=Object\n}\n");rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),switchhashDataflow2);
switchhashDataflow3=rb_eval_string("Hash.new{|h,k|\nnext h[k]=0 if k<=AmethystAST\nnext h[k]=1 if k<=Array\nnext h[k]=2 if k<=Object\n}\n");rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),switchhashDataflow3);
rb_define_method(cls_Dataflow,"root",Dataflow_root,0);
rb_define_method(cls_Dataflow,"traverse",Dataflow_traverse,0);
rb_define_method(cls_Dataflow,"traverse_item",Dataflow_traverse_item,0);
rb_define_method(cls_Dataflow,"vars_in",Dataflow_vars_in,0);
rb_define_method(cls_Dataflow,"visit",Dataflow_visit,0);

 cls_Dead_Code_Deleter3=rb_define_class("Dead_Code_Deleter3",rb_const_get(rb_cObject,rb_intern("Traverser_Clone2"))); 
failobj=rb_eval_string("FAIL");
c_280=rb_const_get(rb_cObject, rb_intern("Rule"));rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),c_280);
s_root_Dead_Code_Deleter3cb_1Dead_Code_Deleter3=rb_intern("root_Dead_Code_Deleter3cb_1");
s_root_Dead_Code_Deleter3cb_2Dead_Code_Deleter3=rb_intern("root_Dead_Code_Deleter3cb_2");
s_root_Dead_Code_Deleter3cb_3Dead_Code_Deleter3=rb_intern("root_Dead_Code_Deleter3cb_3");
s_root_Dead_Code_Deleter3cb_4Dead_Code_Deleter3=rb_intern("root_Dead_Code_Deleter3cb_4");
s_sizeDead_Code_Deleter3=rb_intern("size");
s_traverse_Dead_Code_Deleter3cb_1Dead_Code_Deleter3=rb_intern("traverse_Dead_Code_Deleter3cb_1");
s_traverse_Dead_Code_Deleter3cb_2Dead_Code_Deleter3=rb_intern("traverse_Dead_Code_Deleter3cb_2");
s_traverse_Dead_Code_Deleter3cb_3Dead_Code_Deleter3=rb_intern("traverse_Dead_Code_Deleter3cb_3");
s_traverse_Dead_Code_Deleter3cb_4Dead_Code_Deleter3=rb_intern("traverse_Dead_Code_Deleter3cb_4");
s_traverse_Dead_Code_Deleter3cb_5Dead_Code_Deleter3=rb_intern("traverse_Dead_Code_Deleter3cb_5");
s_traverse_Dead_Code_Deleter3cb_6Dead_Code_Deleter3=rb_intern("traverse_Dead_Code_Deleter3cb_6");
s_traverse_Dead_Code_Deleter3cb_7Dead_Code_Deleter3=rb_intern("traverse_Dead_Code_Deleter3cb_7");
s_traverse_Dead_Code_Deleter3cb_8Dead_Code_Deleter3=rb_intern("traverse_Dead_Code_Deleter3cb_8");
s_traverse_item_Dead_Code_Deleter3cb_1Dead_Code_Deleter3=rb_intern("traverse_item_Dead_Code_Deleter3cb_1");
s_traverse_item_Dead_Code_Deleter3cb_2Dead_Code_Deleter3=rb_intern("traverse_item_Dead_Code_Deleter3cb_2");
s_traverse_item_Dead_Code_Deleter3cb_3Dead_Code_Deleter3=rb_intern("traverse_item_Dead_Code_Deleter3cb_3");
s_visit_Dead_Code_Deleter3cb_10Dead_Code_Deleter3=rb_intern("visit_Dead_Code_Deleter3cb_10");
s_visit_Dead_Code_Deleter3cb_1Dead_Code_Deleter3=rb_intern("visit_Dead_Code_Deleter3cb_1");
s_visit_Dead_Code_Deleter3cb_2Dead_Code_Deleter3=rb_intern("visit_Dead_Code_Deleter3cb_2");
s_visit_Dead_Code_Deleter3cb_3Dead_Code_Deleter3=rb_intern("visit_Dead_Code_Deleter3cb_3");
s_visit_Dead_Code_Deleter3cb_4Dead_Code_Deleter3=rb_intern("visit_Dead_Code_Deleter3cb_4");
s_visit_Dead_Code_Deleter3cb_5Dead_Code_Deleter3=rb_intern("visit_Dead_Code_Deleter3cb_5");
s_visit_Dead_Code_Deleter3cb_6Dead_Code_Deleter3=rb_intern("visit_Dead_Code_Deleter3cb_6");
s_visit_Dead_Code_Deleter3cb_7Dead_Code_Deleter3=rb_intern("visit_Dead_Code_Deleter3cb_7");
s_visit_Dead_Code_Deleter3cb_8Dead_Code_Deleter3=rb_intern("visit_Dead_Code_Deleter3cb_8");
s_visit_Dead_Code_Deleter3cb_9Dead_Code_Deleter3=rb_intern("visit_Dead_Code_Deleter3cb_9");
switchhashDead_Code_Deleter31=rb_eval_string("Hash.new{|h,k|\nnext h[k]=0 if k<=Act\nnext h[k]=1 if k<=CAct\nnext h[k]=2 if k<=Result\nnext h[k]=3 if k<=Object\n}\n");rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),switchhashDead_Code_Deleter31);
switchhashDead_Code_Deleter32=rb_eval_string("Hash.new{|h,k|\nnext h[k]=0 if k<=Act\nnext h[k]=1 if k<=Apply\nnext h[k]=2 if k<=Bind\nnext h[k]=3 if k<=CAct\nnext h[k]=4 if k<=Local\nnext h[k]=5 if k<=Result\nnext h[k]=6 if k<=Object\n}\n");rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),switchhashDead_Code_Deleter32);
switchhashDead_Code_Deleter33=rb_eval_string("Hash.new{|h,k|\nnext h[k]=0 if k<=AmethystAST\nnext h[k]=1 if k<=Array\nnext h[k]=2 if k<=Object\n}\n");rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),switchhashDead_Code_Deleter33);
rb_define_method(cls_Dead_Code_Deleter3,"root",Dead_Code_Deleter3_root,0);
rb_define_method(cls_Dead_Code_Deleter3,"traverse",Dead_Code_Deleter3_traverse,0);
rb_define_method(cls_Dead_Code_Deleter3,"traverse_item",Dead_Code_Deleter3_traverse_item,0);
rb_define_method(cls_Dead_Code_Deleter3,"visit",Dead_Code_Deleter3_visit,0);

 cls_Forget_SSA=rb_define_class("Forget_SSA",rb_const_get(rb_cObject,rb_intern("Traverser_Clone2"))); 
failobj=rb_eval_string("FAIL");
c_292=rb_const_get(rb_cObject, rb_intern("Rule"));rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),c_292);
c_293=rb_const_get(rb_cObject, rb_intern("Local"));rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),c_293);
s_root_Forget_SSAcb_1Forget_SSA=rb_intern("root_Forget_SSAcb_1");
s_root_Forget_SSAcb_2Forget_SSA=rb_intern("root_Forget_SSAcb_2");
s_sizeForget_SSA=rb_intern("size");
s_traverse_Forget_SSAcb_1Forget_SSA=rb_intern("traverse_Forget_SSAcb_1");
s_traverse_Forget_SSAcb_2Forget_SSA=rb_intern("traverse_Forget_SSAcb_2");
s_traverse_Forget_SSAcb_3Forget_SSA=rb_intern("traverse_Forget_SSAcb_3");
s_traverse_Forget_SSAcb_4Forget_SSA=rb_intern("traverse_Forget_SSAcb_4");
s_traverse_Forget_SSAcb_5Forget_SSA=rb_intern("traverse_Forget_SSAcb_5");
s_traverse_Forget_SSAcb_6Forget_SSA=rb_intern("traverse_Forget_SSAcb_6");
s_traverse_Forget_SSAcb_7Forget_SSA=rb_intern("traverse_Forget_SSAcb_7");
s_traverse_Forget_SSAcb_8Forget_SSA=rb_intern("traverse_Forget_SSAcb_8");
s_traverse_item_Forget_SSAcb_1Forget_SSA=rb_intern("traverse_item_Forget_SSAcb_1");
s_traverse_item_Forget_SSAcb_2Forget_SSA=rb_intern("traverse_item_Forget_SSAcb_2");
s_traverse_item_Forget_SSAcb_3Forget_SSA=rb_intern("traverse_item_Forget_SSAcb_3");
s_visit_Forget_SSAcb_1Forget_SSA=rb_intern("visit_Forget_SSAcb_1");
s_visit_Forget_SSAcb_2Forget_SSA=rb_intern("visit_Forget_SSAcb_2");
switchhashForget_SSA1=rb_eval_string("Hash.new{|h,k|\nnext h[k]=0 if k<=AmethystAST\nnext h[k]=1 if k<=Array\nnext h[k]=2 if k<=Object\n}\n");rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),switchhashForget_SSA1);
rb_define_method(cls_Forget_SSA,"root",Forget_SSA_root,0);
rb_define_method(cls_Forget_SSA,"traverse",Forget_SSA_traverse,0);
rb_define_method(cls_Forget_SSA,"traverse_item",Forget_SSA_traverse_item,0);
rb_define_method(cls_Forget_SSA,"visit",Forget_SSA_visit,0);
 rb_eval_string("testversiondataflow_ssa('d0a20fbb9d791fc4979e73d04e2d83fa')");}
