#include "cthyst.h"
VALUE cls_Remove_Left_Recursion;
VALUE AmethystCore_anything(VALUE self );
VALUE Amethyst_clas(VALUE self ,VALUE);
VALUE Amethyst_eof(VALUE self );
VALUE Amethyst_fails(VALUE self );
VALUE Remove_Left_Recursion_rec(VALUE self ,VALUE a0,VALUE a1);
VALUE Remove_Left_Recursion_rec(VALUE self ,VALUE,VALUE);
VALUE Remove_Left_Recursion_root(VALUE self );
VALUE switchhashRemove_Left_Recursion1;
VALUE switchhashRemove_Left_Recursion2;
static VALUE c_Or;
static VALUE c_Rule;
static VALUE sy_Remove_Left_Recursion_Bind_lb_bin2;
static VALUE sy_Remove_Left_Recursion_Bind_lb_bin;
static VALUE sy_Remove_Left_Recursion_Seq_lb_Bind;
static VALUE sy_Remove_Left_Recursion_Seq_lb__ti__lp__lb_b;
static VALUE sy_Remove_Left_Recursion__append_lp_2;
static VALUE sy_Remove_Left_Recursion__append_lp_3;
static VALUE sy_Remove_Left_Recursion__append_lp_4;
static VALUE sy_Remove_Left_Recursion__append_lp_;
static VALUE sy_Remove_Left_Recursion__lp_src_dot_nam2;
static VALUE sy_Remove_Left_Recursion__lp_src_dot_nam;
static VALUE sy_Remove_Left_Recursion_autovar;
static VALUE sy_Remove_Left_Recursion_bind_lb_17_rb_;
static VALUE sy_Remove_Left_Recursion_bind_lb_5_rb__eq_;
static VALUE sy_Remove_Left_Recursion_bind_lb_7_rb__eq_;
static VALUE sy_Remove_Left_Recursion_src_dot_body;
static VALUE sy_Remove_Left_Recursion_src_dot_expr;
static VALUE sy_Remove_Left_Recursion_src_dot_name;
static VALUE sy_size;
VALUE Remove_Left_Recursion_rec(VALUE self ,VALUE a0,VALUE a1){VALUE vals[2]; VALUE bind=bind_new2(10); bind_aset(bind,1/*name*/,a0);bind_aset(bind,2/*a*/,a1); int x;VALUE arg0,arg1,arg2,arg3;VALUE it;

unsigned char chr1=FIX2LONG(rb_hash_aref(switchhashRemove_Left_Recursion1,rb_obj_class(ame_curobj(self))));  switch(chr1){case 0:;   it=AmethystCore_anything(self ); FAILTEST(fail); bind_aset(bind,0/*autovar*/,it);
int oldpos1=ame_getpos(self); int oldlen1=ame_getlen(self); VALUE oldsrc1=ame_getsrc(self); int fail1=0;
ame_setsrc(self,bind_aget(bind,0/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),sy_size,0)));
 it=rb_funcall(self,sy_Remove_Left_Recursion__lp_src_dot_nam2,1,bind); FAILTEST(pass1);  it=AmethystCore_anything(self ); FAILTEST(pass1);it=bind_aget(bind,2/*a*/); bind_aset(bind,3/*autovar*/,it);
  it=Amethyst_eof(self ); FAILTEST(pass1);
	goto success1;
	pass1: fail1=1;
	success1: ame_setsrc(self,oldsrc1); ame_setpos(self,oldpos1); ame_setlen(self,oldlen1);
	if(fail1) goto fail;
it=bind_aget(bind,3/*autovar*/); bind_aset(bind,4/*_result*/,it);
 break;case 1:;   it=AmethystCore_anything(self ); FAILTEST(fail); bind_aset(bind,5/*autovar*/,it);
int oldpos2=ame_getpos(self); int oldlen2=ame_getlen(self); VALUE oldsrc2=ame_getsrc(self); int fail2=0;
ame_setsrc(self,bind_aget(bind,5/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),sy_size,0)));
 it=rb_funcall(self,sy_Remove_Left_Recursion_src_dot_name,1,bind);  bind_aset(bind,6/*n*/,it);
it=rb_funcall(self,sy_Remove_Left_Recursion_src_dot_expr,1,bind);  bind_aset(bind,7/*autovar*/,it);
it=rb_funcall(self,sy_Remove_Left_Recursion_bind_lb_7_rb__eq_,1,bind); int oldpos3=ame_getpos(self); int oldlen3=ame_getlen(self); VALUE oldsrc3=ame_getsrc(self); int fail3=0;
ame_setsrc(self,bind_aget(bind,7/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),sy_size,0)));
  it=bind_aget(bind,1/*name*/); arg0=it;it=bind_aget(bind,2/*a*/); arg1=it; it=Remove_Left_Recursion_rec(self ,arg0,arg1); FAILTEST(pass3); bind_aset(bind,8/*expr*/,it);
  it=Amethyst_eof(self ); FAILTEST(pass3);
	goto success3;
	pass3: fail3=1;
	success3: ame_setsrc(self,oldsrc3); ame_setpos(self,oldpos3); ame_setlen(self,oldlen3);
	if(fail3) goto pass2;
it=rb_funcall(self,sy_Remove_Left_Recursion_Bind_lb_bin2,1,bind);  bind_aset(bind,9/*autovar*/,it);
  it=Amethyst_eof(self ); FAILTEST(pass2);
	goto success2;
	pass2: fail2=1;
	success2: ame_setsrc(self,oldsrc2); ame_setpos(self,oldpos2); ame_setlen(self,oldlen2);
	if(fail2) goto fail;
it=bind_aget(bind,9/*autovar*/); bind_aset(bind,4/*_result*/,it);
 break;case 2:;   it=Amethyst_fails(self ); FAILTEST(fail); break;}it=bind_aget(bind,4/*_result*/);
return it;
fail: return failobj; }
VALUE Remove_Left_Recursion_root(VALUE self ){VALUE vals[0]; VALUE bind=bind_new2(30);  int x;VALUE arg0,arg1,arg2,arg3;VALUE it;

it=rb_ary_new3(0); bind_aset(bind,0/*next*/,it);
it=rb_ary_new3(0); bind_aset(bind,1/*first*/,it);
 it=c_Rule; arg0=it; it=Amethyst_clas(self ,arg0); FAILTEST(fail); bind_aset(bind,2/*autovar*/,it);
int oldpos1=ame_getpos(self); int oldlen1=ame_getlen(self); VALUE oldsrc1=ame_getsrc(self); int fail1=0;
ame_setsrc(self,bind_aget(bind,2/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),sy_size,0)));
 it=rb_funcall(self,sy_Remove_Left_Recursion_src_dot_name,1,bind);  bind_aset(bind,3/*name*/,it);
it=rb_funcall(self,sy_Remove_Left_Recursion_autovar,1,bind);  bind_aset(bind,4/*a*/,it);
it=rb_funcall(self,sy_Remove_Left_Recursion_src_dot_body,1,bind);  bind_aset(bind,5/*autovar*/,it);
it=rb_funcall(self,sy_Remove_Left_Recursion_bind_lb_5_rb__eq_,1,bind); int oldpos2=ame_getpos(self); int oldlen2=ame_getlen(self); VALUE oldsrc2=ame_getsrc(self); int fail2=0;
ame_setsrc(self,bind_aget(bind,5/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),sy_size,0)));
  it=c_Or; arg0=it; it=Amethyst_clas(self ,arg0); FAILTEST(pass2); bind_aset(bind,6/*autovar*/,it);
int oldpos3=ame_getpos(self); int oldlen3=ame_getlen(self); VALUE oldsrc3=ame_getsrc(self); int fail3=0;
ame_setsrc(self,bind_aget(bind,6/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),sy_size,0)));
 it=rb_ary_new3(0); bind_aset(bind,7/*autovar*/,it);
int oldpos4; while(1){oldpos4=ame_getpos(self); unsigned char chr1=FIX2LONG(rb_hash_aref(switchhashRemove_Left_Recursion2,rb_obj_class(ame_curobj(self))));  switch(chr1){case 0:;   it=AmethystCore_anything(self ); FAILTEST(break1); bind_aset(bind,8/*autovar*/,it);
int oldpos5=ame_getpos(self);
alt1_1: ame_setpos(self,oldpos5);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto break1;}
 it=bind_aget(bind,8/*autovar*/); bind_aset(bind,9/*autovar*/,it);
int oldpos6=ame_getpos(self); int oldlen4=ame_getlen(self); VALUE oldsrc4=ame_getsrc(self); int fail4=0;
ame_setsrc(self,bind_aget(bind,9/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),sy_size,0)));
 it=bind_aget(bind,4/*a*/); bind_aset(bind,10/*a*/,it);
it=bind_aget(bind,3/*name*/); bind_aset(bind,11/*name*/,it);
unsigned char chr2=FIX2LONG(rb_hash_aref(switchhashRemove_Left_Recursion1,rb_obj_class(ame_curobj(self))));  switch(chr2){case 0:;   it=AmethystCore_anything(self ); FAILTEST(pass4); bind_aset(bind,12/*autovar*/,it);
int oldpos7=ame_getpos(self); int oldlen5=ame_getlen(self); VALUE oldsrc5=ame_getsrc(self); int fail5=0;
ame_setsrc(self,bind_aget(bind,12/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),sy_size,0)));
 it=rb_funcall(self,sy_Remove_Left_Recursion__lp_src_dot_nam,1,bind); FAILTEST(pass5);  it=AmethystCore_anything(self ); FAILTEST(pass5);it=bind_aget(bind,10/*a*/); bind_aset(bind,13/*autovar*/,it);
  it=Amethyst_eof(self ); FAILTEST(pass5);
	goto success5;
	pass5: fail5=1;
	success5: ame_setsrc(self,oldsrc5); ame_setpos(self,oldpos7); ame_setlen(self,oldlen5);
	if(fail5) goto pass4;
it=bind_aget(bind,13/*autovar*/); bind_aset(bind,14/*_result*/,it);
 break;case 1:;   it=AmethystCore_anything(self ); FAILTEST(pass4); bind_aset(bind,15/*autovar*/,it);
int oldpos8=ame_getpos(self); int oldlen6=ame_getlen(self); VALUE oldsrc6=ame_getsrc(self); int fail6=0;
ame_setsrc(self,bind_aget(bind,15/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),sy_size,0)));
 it=rb_funcall(self,sy_Remove_Left_Recursion_src_dot_name,1,bind);  bind_aset(bind,16/*n*/,it);
it=rb_funcall(self,sy_Remove_Left_Recursion_src_dot_expr,1,bind);  bind_aset(bind,17/*autovar*/,it);
it=rb_funcall(self,sy_Remove_Left_Recursion_bind_lb_17_rb_,1,bind); int oldpos9=ame_getpos(self); int oldlen7=ame_getlen(self); VALUE oldsrc7=ame_getsrc(self); int fail7=0;
ame_setsrc(self,bind_aget(bind,17/*autovar*/)); ame_setpos(self,0); ame_setlen(self,FIX2LONG(rb_funcall(ame_getsrc(self),sy_size,0)));
  it=bind_aget(bind,11/*name*/); arg0=it;it=bind_aget(bind,10/*a*/); arg1=it; it=Remove_Left_Recursion_rec(self ,arg0,arg1); FAILTEST(pass7); bind_aset(bind,18/*expr*/,it);
  it=Amethyst_eof(self ); FAILTEST(pass7);
	goto success7;
	pass7: fail7=1;
	success7: ame_setsrc(self,oldsrc7); ame_setpos(self,oldpos9); ame_setlen(self,oldlen7);
	if(fail7) goto pass6;
it=rb_funcall(self,sy_Remove_Left_Recursion_Bind_lb_bin,1,bind);  bind_aset(bind,19/*autovar*/,it);
  it=Amethyst_eof(self ); FAILTEST(pass6);
	goto success6;
	pass6: fail6=1;
	success6: ame_setsrc(self,oldsrc6); ame_setpos(self,oldpos8); ame_setlen(self,oldlen6);
	if(fail6) goto pass4;
it=bind_aget(bind,19/*autovar*/); bind_aset(bind,14/*_result*/,it);
 break;case 2:;   it=Amethyst_fails(self ); FAILTEST(pass4); break;}it=bind_aget(bind,14/*_result*/); bind_aset(bind,20/*r*/,it);
it=rb_ary_new3(0); bind_aset(bind,21/*autovar*/,it);
int oldpos10; while(1){oldpos10=ame_getpos(self);   it=AmethystCore_anything(self ); FAILTEST(break2); bind_aset(bind,22/*autovar*/,it);
it=rb_funcall(self,sy_Remove_Left_Recursion__append_lp_,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos10=ame_getpos(self);goto break2;} } } break2: ame_setstop(self,Qnil);  ame_setpos(self,oldpos10); it=bind_aget(bind,21/*autovar*/); bind_aset(bind,23/*rest*/,it);
it=rb_funcall(self,sy_Remove_Left_Recursion_Seq_lb__ti__lp__lb_b,1,bind);  bind_aset(bind,24/*autovar*/,it);
it=rb_funcall(self,sy_Remove_Left_Recursion__append_lp_2,1,bind); it=bind_aget(bind,24/*autovar*/); bind_aset(bind,25/*autovar*/,it);
  it=Amethyst_eof(self ); FAILTEST(pass4);
	goto success4;
	pass4: fail4=1;
	success4: ame_setsrc(self,oldsrc4); ame_setpos(self,oldpos6); ame_setlen(self,oldlen4);
	if(fail4) goto alt1_2;
it=bind_aget(bind,25/*autovar*/); bind_aset(bind,26/*autovar*/,it);
 
ame_setcut(self,Qnil);goto accept1;
alt1_2: ame_setpos(self,oldpos5);if (ame_getcut(self)!=Qnil) {ame_setcut(self,Qnil); goto break1;}
 it=bind_aget(bind,8/*autovar*/); bind_aset(bind,27/*autovar*/,it);
it=rb_funcall(self,sy_Remove_Left_Recursion__append_lp_3,1,bind); it=bind_aget(bind,27/*autovar*/); bind_aset(bind,26/*autovar*/,it);
 
ame_setcut(self,Qnil);goto accept1;
  alt1_3:  ame_setpos(self,oldpos5); goto break1;
 accept1:;
 break;case 1:;   it=AmethystCore_anything(self ); FAILTEST(break1); bind_aset(bind,27/*autovar*/,it);
it=rb_funcall(self,sy_Remove_Left_Recursion__append_lp_3,1,bind); it=bind_aget(bind,27/*autovar*/); bind_aset(bind,26/*autovar*/,it);
 break;}it=rb_funcall(self,sy_Remove_Left_Recursion__append_lp_4,1,bind);  if (ame_getstop(self)!=Qnil){{oldpos4=ame_getpos(self);goto break1;} } } break1: ame_setstop(self,Qnil);  ame_setpos(self,oldpos4); it=bind_aget(bind,7/*autovar*/);  it=Amethyst_eof(self ); FAILTEST(pass3);
	goto success3;
	pass3: fail3=1;
	success3: ame_setsrc(self,oldsrc3); ame_setpos(self,oldpos3); ame_setlen(self,oldlen3);
	if(fail3) goto pass2;
  it=Amethyst_eof(self ); FAILTEST(pass2);
	goto success2;
	pass2: fail2=1;
	success2: ame_setsrc(self,oldsrc2); ame_setpos(self,oldpos2); ame_setlen(self,oldlen2);
	if(fail2) goto pass1;
it=rb_funcall(self,sy_Remove_Left_Recursion_Seq_lb_Bind,1,bind);  bind_aset(bind,28/*autovar*/,it);
  it=Amethyst_eof(self ); FAILTEST(pass1);
	goto success1;
	pass1: fail1=1;
	success1: ame_setsrc(self,oldsrc1); ame_setpos(self,oldpos1); ame_setlen(self,oldlen1);
	if(fail1) goto fail;
it=bind_aget(bind,28/*autovar*/); bind_aset(bind,29/*_result*/,it);
it=bind_aget(bind,29/*_result*/);
return it;
fail: return failobj; }VALUE cls_Remove_Rigth_Recursion;

void Init_remove_left_rigth_recursion_c(){ 
 cls_Remove_Left_Recursion=rb_define_class("Remove_Left_Recursion",rb_const_get(rb_cObject,rb_intern("Traverser_Clone2"))); 
failobj=rb_eval_string("FAIL");
c_Or=rb_const_get(rb_cObject, rb_intern("Or"));rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),c_Or);
c_Rule=rb_const_get(rb_cObject, rb_intern("Rule"));rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),c_Rule);
switchhashRemove_Left_Recursion1=rb_eval_string("Hash.new{|h,k|\nnext h[k]=0 if k<=Apply\nnext h[k]=1 if k<=Bind\nnext h[k]=2 if k<=Object\n}\n");rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),switchhashRemove_Left_Recursion1);
switchhashRemove_Left_Recursion2=rb_eval_string("Hash.new{|h,k|\nnext h[k]=0 if k<=Seq\nnext h[k]=1 if k<=Object\n}\n");rb_ary_push(rb_const_get(rb_cObject,rb_intern("GC_mark")),switchhashRemove_Left_Recursion2);
sy_Remove_Left_Recursion_Bind_lb_bin2=rb_intern("Remove_Left_Recursion_Bind_lb_bin2");
sy_Remove_Left_Recursion_Bind_lb_bin=rb_intern("Remove_Left_Recursion_Bind_lb_bin");
sy_Remove_Left_Recursion_Seq_lb_Bind=rb_intern("Remove_Left_Recursion_Seq_lb_Bind");
sy_Remove_Left_Recursion_Seq_lb__ti__lp__lb_b=rb_intern("Remove_Left_Recursion_Seq_lb__ti__lp__lb_b");
sy_Remove_Left_Recursion__append_lp_2=rb_intern("Remove_Left_Recursion__append_lp_2");
sy_Remove_Left_Recursion__append_lp_3=rb_intern("Remove_Left_Recursion__append_lp_3");
sy_Remove_Left_Recursion__append_lp_4=rb_intern("Remove_Left_Recursion__append_lp_4");
sy_Remove_Left_Recursion__append_lp_=rb_intern("Remove_Left_Recursion__append_lp_");
sy_Remove_Left_Recursion__lp_src_dot_nam2=rb_intern("Remove_Left_Recursion__lp_src_dot_nam2");
sy_Remove_Left_Recursion__lp_src_dot_nam=rb_intern("Remove_Left_Recursion__lp_src_dot_nam");
sy_Remove_Left_Recursion_autovar=rb_intern("Remove_Left_Recursion_autovar");
sy_Remove_Left_Recursion_bind_lb_17_rb_=rb_intern("Remove_Left_Recursion_bind_lb_17_rb_");
sy_Remove_Left_Recursion_bind_lb_5_rb__eq_=rb_intern("Remove_Left_Recursion_bind_lb_5_rb__eq_");
sy_Remove_Left_Recursion_bind_lb_7_rb__eq_=rb_intern("Remove_Left_Recursion_bind_lb_7_rb__eq_");
sy_Remove_Left_Recursion_src_dot_body=rb_intern("Remove_Left_Recursion_src_dot_body");
sy_Remove_Left_Recursion_src_dot_expr=rb_intern("Remove_Left_Recursion_src_dot_expr");
sy_Remove_Left_Recursion_src_dot_name=rb_intern("Remove_Left_Recursion_src_dot_name");
sy_size=rb_intern("size");
rb_define_method(cls_Remove_Left_Recursion,"rec",Remove_Left_Recursion_rec,2);
rb_define_method(cls_Remove_Left_Recursion,"root",Remove_Left_Recursion_root,0);

 cls_Remove_Rigth_Recursion=rb_define_class("Remove_Rigth_Recursion",rb_const_get(rb_cObject,rb_intern("Traverser_Clone2"))); 
failobj=rb_eval_string("FAIL");


 rb_eval_string("testversionremove_left_rigth_recursion('3632fe882b6739d497e2713eece93d9a')");}
