#define TP_char 1
#define TP_revert_r_state 2
#define TP_revert_r_rstr 3
#define TP_call_finished 4
#define TP_finish 5
#define TP_enter 6
#define TP_use_lambda 7
#define TP_make_lambda 8
#define TP_stop 9
#define TP_many 10
#define TP_switch 11
#define TP_revert_a_cont 12
#define TP_nested 13
#define TP_revert_a_stops 14
#define TP_revert_a_str 15
#define TP_revert_a_closure 16
#define TP_act 17
#define TP_bind 18
#define TP_revert_local 19
#define TP_call 20
#define TP_call_conted 21
#define TP_return 22
#define TP_seq 23
#define TP_nested_end 24
#define TP_switch2 25
#define TP_rule 26
