#define TP_char 1
#define TP_revert_r_state 2
#define TP_revert_r_rstr 3
#define TP_lambda_finished 4
#define TP_call_finished 5
#define TP_finish 6
#define TP_enter 7
#define TP_use_lambda 8
#define TP_make_lambda 9
#define TP_stop 10
#define TP_many 11
#define TP_switch 12
#define TP_revert_a_cont 13
#define TP_nested 14
#define TP_cont_ended 15
#define TP_revert_a_stops 16
#define TP_revert_a_str 17
#define TP_revert_a_closure 18
#define TP_act 19
#define TP_bind 20
#define TP_revert_local 21
#define TP_call 22
#define TP_call_conted 23
#define TP_return 24
#define TP_seq 25
#define TP_nested_end 26
#define TP_switch2 27
#define TP_rule 28
