#include "cthyst.h"
VALUE cls_Dead_Code_Detector;
VALUE Dead_Code_Detector_trans(VALUE self );
VALUE Dead_Code_Detector_vars_in(VALUE self );
VALUE Dead_Code_Detector_trans(VALUE self ){VALUE vals[0]; VALUE bind=rb_hash_new();  int x;VALUE arg0,arg1,arg2,arg3;
VALUE oldinput2=IGET(input);
alt3: ISET(input,oldinput2);if (IGET(cut)!=Qnil) goto fail;
  arg0=CALL(trans_Dead_Code_Detectorcb_1,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt4);
 BSET(autovar_1,BGET(it)); VALUE oldinput6=IGET(input);  VALUE oldsrc7=IGET(src); int fail9=0;
ISET(src,BGET(autovar_1)); ISET(input,INT2FIX(0));
 BSET(it,CALL(trans_Dead_Code_Detectorcb_2,1,bind)); 
 BSET(name_1,BGET(it)); BSET(it,CALL(trans_Dead_Code_Detectorcb_3,1,bind)); BSET(it,CALL(trans_Dead_Code_Detectorcb_4,1,bind)); 
 BSET(autovar_2,BGET(it)); VALUE oldinput11=IGET(input);  VALUE oldsrc12=IGET(src); int fail14=0;
ISET(src,rb_ary_new3(1,BGET(autovar_2))); ISET(input,INT2FIX(0));
   BSET(it,CALL(args,0 )); FAILTEST(pass10);
 BSET(args_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass10;
	goto success13;
	pass10: fail14=1;
	success13: ISET(src,oldsrc12); ISET(input,oldinput11);
	if(fail14) goto pass5;
BSET(it,CALL(trans_Dead_Code_Detectorcb_5,1,bind)); 
 BSET(autovar_3,BGET(it)); VALUE oldinput16=IGET(input);  VALUE oldsrc17=IGET(src); int fail19=0;
ISET(src,rb_ary_new3(1,BGET(autovar_3))); ISET(input,INT2FIX(0));
   BSET(it,CALL(trans,0 )); FAILTEST(pass15);
	if (CALL(eof,0)==failobj) goto pass15;
	goto success18;
	pass15: fail19=1;
	success18: ISET(src,oldsrc17); ISET(input,oldinput16);
	if(fail19) goto pass5;
BSET(it,CALL(trans_Dead_Code_Detectorcb_6,1,bind)); 
 BSET(body_1,BGET(it)); BSET(it,CALL(trans_Dead_Code_Detectorcb_7,1,bind)); 
 BSET(locals_1,BGET(it)); BSET(it,CALL(trans_Dead_Code_Detectorcb_8,1,bind)); 
 BSET(reachable_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass5;
	goto success8;
	pass5: fail9=1;
	success8: ISET(src,oldsrc7); ISET(input,oldinput6);
	if(fail9) goto alt4;
BSET(it,CALL(trans_Dead_Code_Detectorcb_9,1,bind));
 BSET(_result_1,BGET(it));  
ISET(cut,Qnil);goto accept1;
alt4: ISET(input,oldinput2);if (IGET(cut)!=Qnil) goto fail;
  arg0=CALL(trans_Dead_Code_Detectorcb_10,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt20);
 BSET(autovar_4,BGET(it)); VALUE oldinput22=IGET(input);  VALUE oldsrc23=IGET(src); int fail25=0;
ISET(src,BGET(autovar_4)); ISET(input,INT2FIX(0));
   BSET(it,CALL(anything,0 )); FAILTEST(pass21);
 BSET(name_1,BGET(it));   BSET(it,CALL(vars_in,0 )); FAILTEST(pass21);
 BSET(var_1,BGET(it)); BSET(it,CALL(trans_Dead_Code_Detectorcb_11,1,bind)); 
 BSET(_result_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass21;
	goto success24;
	pass21: fail25=1;
	success24: ISET(src,oldsrc23); ISET(input,oldinput22);
	if(fail25) goto alt20;
 
ISET(cut,Qnil);goto accept1;
alt20: ISET(input,oldinput2);if (IGET(cut)!=Qnil) goto fail;
  arg0=CALL(trans_Dead_Code_Detectorcb_12,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt26);
 BSET(autovar_5,BGET(it)); VALUE oldinput28=IGET(input);  VALUE oldsrc29=IGET(src); int fail31=0;
ISET(src,BGET(autovar_5)); ISET(input,INT2FIX(0));
 BSET(it,CALL(trans_Dead_Code_Detectorcb_13,1,bind)); 
 BSET(autovar_6,BGET(it)); VALUE oldinput33=IGET(input);  VALUE oldsrc34=IGET(src); int fail36=0;
ISET(src,rb_ary_new3(1,BGET(autovar_6))); ISET(input,INT2FIX(0));
   BSET(it,CALL(vars_in,0 )); FAILTEST(pass32);
 BSET(var_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass32;
	goto success35;
	pass32: fail36=1;
	success35: ISET(src,oldsrc34); ISET(input,oldinput33);
	if(fail36) goto pass27;
BSET(it,CALL(trans_Dead_Code_Detectorcb_14,1,bind)); BSET(it,CALL(trans_Dead_Code_Detectorcb_15,1,bind)); 
 BSET(autovar_7,BGET(it)); VALUE oldinput38=IGET(input);  VALUE oldsrc39=IGET(src); int fail41=0;
ISET(src,rb_ary_new3(1,BGET(autovar_7))); ISET(input,INT2FIX(0));
   BSET(it,CALL(trans,0 )); FAILTEST(pass37);
 BSET(_result_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass37;
	goto success40;
	pass37: fail41=1;
	success40: ISET(src,oldsrc39); ISET(input,oldinput38);
	if(fail41) goto pass27;

	if (CALL(eof,0)==failobj) goto pass27;
	goto success30;
	pass27: fail31=1;
	success30: ISET(src,oldsrc29); ISET(input,oldinput28);
	if(fail31) goto alt26;
 
ISET(cut,Qnil);goto accept1;
alt26: ISET(input,oldinput2);if (IGET(cut)!=Qnil) goto fail;
  arg0=CALL(trans_Dead_Code_Detectorcb_16,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt42);
 BSET(autovar_8,BGET(it)); VALUE oldinput44=IGET(input);  VALUE oldsrc45=IGET(src); int fail47=0;
ISET(src,BGET(autovar_8)); ISET(input,INT2FIX(0));
 BSET(it,CALL(trans_Dead_Code_Detectorcb_17,1,bind)); 
 BSET(this_1,BGET(it)); BSET(it,CALL(trans_Dead_Code_Detectorcb_18,1,bind));   BSET(it,CALL(vars_in,0 )); FAILTEST(pass43);
 BSET(var_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass43;
	goto success46;
	pass43: fail47=1;
	success46: ISET(src,oldsrc45); ISET(input,oldinput44);
	if(fail47) goto alt42;
BSET(it,CALL(trans_Dead_Code_Detectorcb_19,1,bind)); 
 BSET(_result_1,BGET(it));  
ISET(cut,Qnil);goto accept1;
alt42: ISET(input,oldinput2);if (IGET(cut)!=Qnil) goto fail;
  arg0=CALL(trans_Dead_Code_Detectorcb_20,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt48);
 BSET(autovar_9,BGET(it)); VALUE oldinput50=IGET(input);  VALUE oldsrc51=IGET(src); int fail53=0;
ISET(src,BGET(autovar_9)); ISET(input,INT2FIX(0));
 BSET(it,CALL(trans_Dead_Code_Detectorcb_21,1,bind)); 
 BSET(autovar_10,BGET(it)); VALUE oldinput55=IGET(input);  VALUE oldsrc56=IGET(src); int fail58=0;
ISET(src,rb_ary_new3(1,BGET(autovar_10))); ISET(input,INT2FIX(0));
   BSET(it,CALL(vars_in,0 )); FAILTEST(pass54);
 BSET(v_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass54;
	goto success57;
	pass54: fail58=1;
	success57: ISET(src,oldsrc56); ISET(input,oldinput55);
	if(fail58) goto pass49;
BSET(it,CALL(trans_Dead_Code_Detectorcb_22,1,bind)); BSET(it,CALL(trans_Dead_Code_Detectorcb_23,1,bind)); 
 BSET(autovar_11,BGET(it)); VALUE oldinput60=IGET(input);  VALUE oldsrc61=IGET(src); int fail63=0;
ISET(src,rb_ary_new3(1,BGET(autovar_11))); ISET(input,INT2FIX(0));
   BSET(it,CALL(trans,0 )); FAILTEST(pass59);
	if (CALL(eof,0)==failobj) goto pass59;
	goto success62;
	pass59: fail63=1;
	success62: ISET(src,oldsrc61); ISET(input,oldinput60);
	if(fail63) goto pass49;
BSET(it,CALL(trans_Dead_Code_Detectorcb_24,1,bind)); 
 BSET(autovar_12,BGET(it)); VALUE oldinput65=IGET(input);  VALUE oldsrc66=IGET(src); int fail68=0;
ISET(src,rb_ary_new3(1,BGET(autovar_12))); ISET(input,INT2FIX(0));
   BSET(it,CALL(vars_in,0 )); FAILTEST(pass64);
 BSET(var_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass64;
	goto success67;
	pass64: fail68=1;
	success67: ISET(src,oldsrc66); ISET(input,oldinput65);
	if(fail68) goto pass49;

	if (CALL(eof,0)==failobj) goto pass49;
	goto success52;
	pass49: fail53=1;
	success52: ISET(src,oldsrc51); ISET(input,oldinput50);
	if(fail53) goto alt48;
BSET(it,CALL(trans_Dead_Code_Detectorcb_25,1,bind)); 
 BSET(_result_1,BGET(it));  
ISET(cut,Qnil);goto accept1;
alt48: ISET(input,oldinput2);if (IGET(cut)!=Qnil) goto fail;
  arg0=CALL(trans_Dead_Code_Detectorcb_26,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt69);
 BSET(autovar_13,BGET(it)); VALUE oldinput71=IGET(input);  VALUE oldsrc72=IGET(src); int fail74=0;
ISET(src,BGET(autovar_13)); ISET(input,INT2FIX(0));
 BSET(it,CALL(trans_Dead_Code_Detectorcb_27,1,bind)); 
 BSET(autovar_14,BGET(it)); VALUE oldinput76=IGET(input);  VALUE oldsrc77=IGET(src); int fail79=0;
ISET(src,rb_ary_new3(1,BGET(autovar_14))); ISET(input,INT2FIX(0));
   BSET(it,CALL(anything,0 )); FAILTEST(pass75);
 BSET(autovar_15,BGET(it)); VALUE oldinput81=IGET(input);  VALUE oldsrc82=IGET(src); int fail84=0;
ISET(src,BGET(autovar_15)); ISET(input,INT2FIX(0));
   BSET(it,CALL(vars_in,0 )); FAILTEST(pass80);
 BSET(var_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass80;
	goto success83;
	pass80: fail84=1;
	success83: ISET(src,oldsrc82); ISET(input,oldinput81);
	if(fail84) goto pass75;

	if (CALL(eof,0)==failobj) goto pass75;
	goto success78;
	pass75: fail79=1;
	success78: ISET(src,oldsrc77); ISET(input,oldinput76);
	if(fail79) goto pass70;
BSET(it,CALL(trans_Dead_Code_Detectorcb_28,1,bind)); 
 BSET(v_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass70;
	goto success73;
	pass70: fail74=1;
	success73: ISET(src,oldsrc72); ISET(input,oldinput71);
	if(fail74) goto alt69;
BSET(it,CALL(trans_Dead_Code_Detectorcb_29,1,bind)); 
 BSET(_result_1,BGET(it));  
ISET(cut,Qnil);goto accept1;
alt69: ISET(input,oldinput2);if (IGET(cut)!=Qnil) goto fail;
 BSET(it,rb_call_super(0,vals)); FAILTEST(alt85);
 BSET(_result_1,BGET(it));  
ISET(cut,Qnil);goto accept1;
  alt85:  ISET(input,oldinput2); goto fail;
 accept1:;
BSET(it,BGET(_result_1));
return BGET(_result_1);
fail: return failobj; }
VALUE Dead_Code_Detector_vars_in(VALUE self ){VALUE vals[0]; VALUE bind=rb_hash_new();  int x;VALUE arg0,arg1,arg2,arg3;
BSET(it,CALL(vars_in_Dead_Code_Detectorcb_1,1,bind)); BSET(it,CALL(vars_in_Dead_Code_Detectorcb_2,1,bind)); 
 BSET(autovar_1,BGET(it)); VALUE oldinput87; while(1){oldinput87=IGET(input); VALUE oldinput89=IGET(input);
alt90: ISET(input,oldinput89);if (IGET(cut)!=Qnil) goto break86;
  arg0=CALL(vars_in_Dead_Code_Detectorcb_3,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt91);
 BSET(autovar_2,BGET(it)); VALUE oldinput93=IGET(input);  VALUE oldsrc94=IGET(src); int fail96=0;
ISET(src,BGET(autovar_2)); ISET(input,INT2FIX(0));
 BSET(it,CALL(vars_in_Dead_Code_Detectorcb_4,1,bind)); 
 BSET(autovar_3,BGET(it)); BSET(it,CALL(vars_in_Dead_Code_Detectorcb_5,1,bind)); BSET(it,CALL(vars_in_Dead_Code_Detectorcb_6,1,bind)); BSET(it,CALL(vars_in_Dead_Code_Detectorcb_7,1,bind)); 
 BSET(autovar_4,BGET(it)); VALUE oldinput98; while(1){oldinput98=IGET(input);   BSET(it,CALL(anything,0 )); FAILTEST(break97);
 BSET(autovar_5,BGET(it)); BSET(it,CALL(vars_in_Dead_Code_Detectorcb_8,1,bind));  } break97: ISET(input,oldinput98); BSET(it,BGET(autovar_4));
 BSET(autovar_6,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass92;
	goto success95;
	pass92: fail96=1;
	success95: ISET(src,oldsrc94); ISET(input,oldinput93);
	if(fail96) goto alt91;
 
ISET(cut,Qnil);goto accept88;
alt91: ISET(input,oldinput89);if (IGET(cut)!=Qnil) goto break86;
  arg0=CALL(vars_in_Dead_Code_Detectorcb_9,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt99);
 BSET(autovar_7,BGET(it)); VALUE oldinput101=IGET(input);  VALUE oldsrc102=IGET(src); int fail104=0;
ISET(src,BGET(autovar_7)); ISET(input,INT2FIX(0));
 BSET(it,CALL(vars_in_Dead_Code_Detectorcb_10,1,bind)); 
 BSET(autovar_8,BGET(it)); BSET(it,CALL(vars_in_Dead_Code_Detectorcb_11,1,bind)); BSET(it,CALL(vars_in_Dead_Code_Detectorcb_12,1,bind)); 
 BSET(autovar_9,BGET(it)); VALUE oldinput106; while(1){oldinput106=IGET(input);   BSET(it,CALL(anything,0 )); FAILTEST(break105);
 BSET(autovar_10,BGET(it)); BSET(it,CALL(vars_in_Dead_Code_Detectorcb_13,1,bind));  } break105: ISET(input,oldinput106); BSET(it,BGET(autovar_9));
 BSET(autovar_6,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass100;
	goto success103;
	pass100: fail104=1;
	success103: ISET(src,oldsrc102); ISET(input,oldinput101);
	if(fail104) goto alt99;
 
ISET(cut,Qnil);goto accept88;
alt99: ISET(input,oldinput89);if (IGET(cut)!=Qnil) goto break86;
  arg0=CALL(vars_in_Dead_Code_Detectorcb_14,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt107);
 BSET(autovar_11,BGET(it)); VALUE oldinput109=IGET(input);  VALUE oldsrc110=IGET(src); int fail112=0;
ISET(src,BGET(autovar_11)); ISET(input,INT2FIX(0));
 BSET(it,CALL(vars_in_Dead_Code_Detectorcb_15,1,bind)); 
 BSET(autovar_12,BGET(it)); BSET(it,CALL(vars_in_Dead_Code_Detectorcb_16,1,bind)); BSET(it,CALL(vars_in_Dead_Code_Detectorcb_17,1,bind)); BSET(it,CALL(vars_in_Dead_Code_Detectorcb_18,1,bind)); 
 BSET(autovar_13,BGET(it)); VALUE oldinput114; while(1){oldinput114=IGET(input);   BSET(it,CALL(anything,0 )); FAILTEST(break113);
 BSET(autovar_14,BGET(it)); BSET(it,CALL(vars_in_Dead_Code_Detectorcb_19,1,bind));  } break113: ISET(input,oldinput114); BSET(it,BGET(autovar_13));
 BSET(autovar_6,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass108;
	goto success111;
	pass108: fail112=1;
	success111: ISET(src,oldsrc110); ISET(input,oldinput109);
	if(fail112) goto alt107;
 
ISET(cut,Qnil);goto accept88;
alt107: ISET(input,oldinput89);if (IGET(cut)!=Qnil) goto break86;
  arg0=CALL(vars_in_Dead_Code_Detectorcb_20,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt115);
 BSET(autovar_15,BGET(it)); VALUE oldinput117=IGET(input);  VALUE oldsrc118=IGET(src); int fail120=0;
ISET(src,BGET(autovar_15)); ISET(input,INT2FIX(0));
   BSET(it,CALL(trans,0 )); FAILTEST(pass116);
 BSET(autovar_6,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass116;
	goto success119;
	pass116: fail120=1;
	success119: ISET(src,oldsrc118); ISET(input,oldinput117);
	if(fail120) goto alt115;
 
ISET(cut,Qnil);goto accept88;
alt115: ISET(input,oldinput89);if (IGET(cut)!=Qnil) goto break86;
  arg0=CALL(vars_in_Dead_Code_Detectorcb_21,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt121);
 BSET(autovar_16,BGET(it)); VALUE oldinput123=IGET(input);  VALUE oldsrc124=IGET(src); int fail126=0;
ISET(src,BGET(autovar_16)); ISET(input,INT2FIX(0));
 BSET(it,CALL(vars_in_Dead_Code_Detectorcb_22,1,bind)); 
 BSET(autovar_17,BGET(it)); BSET(it,CALL(vars_in_Dead_Code_Detectorcb_23,1,bind)); 
 BSET(autovar_6,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass122;
	goto success125;
	pass122: fail126=1;
	success125: ISET(src,oldsrc124); ISET(input,oldinput123);
	if(fail126) goto alt121;
 
ISET(cut,Qnil);goto accept88;
alt121: ISET(input,oldinput89);if (IGET(cut)!=Qnil) goto break86;
  arg0=CALL(vars_in_Dead_Code_Detectorcb_24,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt127);
 BSET(autovar_18,BGET(it)); VALUE oldinput129=IGET(input);  VALUE oldsrc130=IGET(src); int fail132=0;
ISET(src,BGET(autovar_18)); ISET(input,INT2FIX(0));
   BSET(it,CALL(vars_in,0 )); FAILTEST(pass128);
 BSET(autovar_19,BGET(it)); BSET(it,CALL(vars_in_Dead_Code_Detectorcb_25,1,bind)); 
 BSET(autovar_6,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass128;
	goto success131;
	pass128: fail132=1;
	success131: ISET(src,oldsrc130); ISET(input,oldinput129);
	if(fail132) goto alt127;
 
ISET(cut,Qnil);goto accept88;
alt127: ISET(input,oldinput89);if (IGET(cut)!=Qnil) goto break86;
  arg0=CALL(vars_in_Dead_Code_Detectorcb_26,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt133);
 BSET(autovar_20,BGET(it)); VALUE oldinput135=IGET(input);  VALUE oldsrc136=IGET(src); int fail138=0;
ISET(src,BGET(autovar_20)); ISET(input,INT2FIX(0));
   BSET(it,CALL(vars_in,0 )); FAILTEST(pass134);
 BSET(autovar_21,BGET(it)); BSET(it,CALL(vars_in_Dead_Code_Detectorcb_27,1,bind)); 
 BSET(autovar_6,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass134;
	goto success137;
	pass134: fail138=1;
	success137: ISET(src,oldsrc136); ISET(input,oldinput135);
	if(fail138) goto alt133;
 
ISET(cut,Qnil);goto accept88;
alt133: ISET(input,oldinput89);if (IGET(cut)!=Qnil) goto break86;
  arg0=CALL(vars_in_Dead_Code_Detectorcb_28,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt139);
 BSET(autovar_22,BGET(it)); VALUE oldinput141=IGET(input);  VALUE oldsrc142=IGET(src); int fail144=0;
ISET(src,BGET(autovar_22)); ISET(input,INT2FIX(0));
 BSET(it,CALL(vars_in_Dead_Code_Detectorcb_29,1,bind)); 
 BSET(autovar_23,BGET(it)); VALUE oldinput146=IGET(input);  VALUE oldsrc147=IGET(src); int fail149=0;
ISET(src,rb_ary_new3(1,BGET(autovar_23))); ISET(input,INT2FIX(0));
   BSET(it,CALL(vars_in,0 )); FAILTEST(pass145);
 BSET(autovar_24,BGET(it)); BSET(it,CALL(vars_in_Dead_Code_Detectorcb_30,1,bind)); 
 BSET(autovar_6,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass145;
	goto success148;
	pass145: fail149=1;
	success148: ISET(src,oldsrc147); ISET(input,oldinput146);
	if(fail149) goto pass140;

	if (CALL(eof,0)==failobj) goto pass140;
	goto success143;
	pass140: fail144=1;
	success143: ISET(src,oldsrc142); ISET(input,oldinput141);
	if(fail144) goto alt139;
 
ISET(cut,Qnil);goto accept88;
alt139: ISET(input,oldinput89);if (IGET(cut)!=Qnil) goto break86;
  arg0=CALL(vars_in_Dead_Code_Detectorcb_31,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt150);
 BSET(autovar_25,BGET(it)); VALUE oldinput152=IGET(input);  VALUE oldsrc153=IGET(src); int fail155=0;
ISET(src,BGET(autovar_25)); ISET(input,INT2FIX(0));
   BSET(it,CALL(anything,0 )); FAILTEST(pass151);
 BSET(name_1,BGET(it)); BSET(it,CALL(vars_in_Dead_Code_Detectorcb_32,1,bind)); BSET(it,CALL(vars_in_Dead_Code_Detectorcb_33,1,bind)); 
 BSET(autovar_26,BGET(it)); BSET(it,CALL(vars_in_Dead_Code_Detectorcb_34,1,bind)); 
 BSET(autovar_6,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass151;
	goto success154;
	pass151: fail155=1;
	success154: ISET(src,oldsrc153); ISET(input,oldinput152);
	if(fail155) goto alt150;
 
ISET(cut,Qnil);goto accept88;
alt150: ISET(input,oldinput89);if (IGET(cut)!=Qnil) goto break86;
   BSET(it,CALL(anything,0 )); FAILTEST(alt156);
 BSET(autovar_6,BGET(it));  
ISET(cut,Qnil);goto accept88;
  alt156:  ISET(input,oldinput89); goto break86;
 accept88:;
BSET(it,CALL(vars_in_Dead_Code_Detectorcb_35,1,bind));  } break86: ISET(input,oldinput87); BSET(it,BGET(autovar_1));BSET(it,BGET(ary_1));
 BSET(_result_1,BGET(it)); BSET(it,BGET(_result_1));
return BGET(_result_1);
fail: return failobj; }
VALUE cls_Dead_Code_Deleter;
VALUE Dead_Code_Deleter_trans(VALUE self );
VALUE Dead_Code_Deleter_trans(VALUE self ){VALUE vals[0]; VALUE bind=rb_hash_new();  int x;VALUE arg0,arg1,arg2,arg3;
VALUE oldinput158=IGET(input);
alt159: ISET(input,oldinput158);if (IGET(cut)!=Qnil) goto fail;
  arg0=CALL(trans_Dead_Code_Deletercb_1,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt160);
 BSET(autovar_1,BGET(it)); VALUE oldinput162=IGET(input);  VALUE oldsrc163=IGET(src); int fail165=0;
ISET(src,BGET(autovar_1)); ISET(input,INT2FIX(0));
 BSET(it,CALL(trans_Dead_Code_Deletercb_2,1,bind)); 
 BSET(name_1,BGET(it)); BSET(it,CALL(trans_Dead_Code_Deletercb_3,1,bind)); 
 BSET(it_1,BGET(it)); BSET(it,CALL(trans_Dead_Code_Deletercb_4,1,bind)); BSET(it,CALL(trans_Dead_Code_Deletercb_5,1,bind)); 
 BSET(autovar_2,BGET(it)); VALUE oldinput167=IGET(input);  VALUE oldsrc168=IGET(src); int fail170=0;
ISET(src,rb_ary_new3(1,BGET(autovar_2))); ISET(input,INT2FIX(0));
   BSET(it,CALL(args,0 )); FAILTEST(pass166);
 BSET(args_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass166;
	goto success169;
	pass166: fail170=1;
	success169: ISET(src,oldsrc168); ISET(input,oldinput167);
	if(fail170) goto pass161;
BSET(it,CALL(trans_Dead_Code_Deletercb_6,1,bind)); 
 BSET(autovar_3,BGET(it)); VALUE oldinput172=IGET(input);  VALUE oldsrc173=IGET(src); int fail175=0;
ISET(src,rb_ary_new3(1,BGET(autovar_3))); ISET(input,INT2FIX(0));
   BSET(it,CALL(trans,0 )); FAILTEST(pass171);
 BSET(body_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass171;
	goto success174;
	pass171: fail175=1;
	success174: ISET(src,oldsrc173); ISET(input,oldinput172);
	if(fail175) goto pass161;
BSET(it,CALL(trans_Dead_Code_Deletercb_7,1,bind)); 
 BSET(locals_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass161;
	goto success164;
	pass161: fail165=1;
	success164: ISET(src,oldsrc163); ISET(input,oldinput162);
	if(fail165) goto alt160;
BSET(it,CALL(trans_Dead_Code_Deletercb_8,1,bind));
 BSET(_result_1,BGET(it));  
ISET(cut,Qnil);goto accept157;
alt160: ISET(input,oldinput158);if (IGET(cut)!=Qnil) goto fail;
  arg0=CALL(trans_Dead_Code_Deletercb_9,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt176);
 BSET(autovar_4,BGET(it)); VALUE oldinput178=IGET(input);  VALUE oldsrc179=IGET(src); int fail181=0;
ISET(src,BGET(autovar_4)); ISET(input,INT2FIX(0));
 BSET(it,CALL(trans_Dead_Code_Deletercb_10,1,bind)); 
 BSET(this_1,BGET(it)); BSET(it,CALL(trans_Dead_Code_Deletercb_11,1,bind)); 
 BSET(autovar_5,BGET(it)); VALUE oldinput183; while(1){oldinput183=IGET(input);   BSET(it,CALL(anything,0 )); FAILTEST(break182);
 BSET(autovar_6,BGET(it)); BSET(it,CALL(trans_Dead_Code_Deletercb_12,1,bind));  } break182: ISET(input,oldinput183); BSET(it,BGET(autovar_5));
	if (CALL(eof,0)==failobj) goto pass177;
	goto success180;
	pass177: fail181=1;
	success180: ISET(src,oldsrc179); ISET(input,oldinput178);
	if(fail181) goto alt176;
BSET(it,CALL(trans_Dead_Code_Deletercb_13,1,bind)); 
 BSET(_result_1,BGET(it));  
ISET(cut,Qnil);goto accept157;
alt176: ISET(input,oldinput158);if (IGET(cut)!=Qnil) goto fail;
  arg0=CALL(trans_Dead_Code_Deletercb_14,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt184);
 BSET(autovar_7,BGET(it)); VALUE oldinput186=IGET(input);  VALUE oldsrc187=IGET(src); int fail189=0;
ISET(src,BGET(autovar_7)); ISET(input,INT2FIX(0));
 BSET(it,CALL(trans_Dead_Code_Deletercb_15,1,bind)); 
 BSET(name_1,BGET(it)); BSET(it,CALL(trans_Dead_Code_Deletercb_16,1,bind)); 
 BSET(autovar_8,BGET(it)); VALUE oldinput191=IGET(input);  VALUE oldsrc192=IGET(src); int fail194=0;
ISET(src,rb_ary_new3(1,BGET(autovar_8))); ISET(input,INT2FIX(0));
   BSET(it,CALL(trans,0 )); FAILTEST(pass190);
 BSET(expr_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass190;
	goto success193;
	pass190: fail194=1;
	success193: ISET(src,oldsrc192); ISET(input,oldinput191);
	if(fail194) goto pass185;
BSET(it,CALL(trans_Dead_Code_Deletercb_17,1,bind)); 
 BSET(append_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass185;
	goto success188;
	pass185: fail189=1;
	success188: ISET(src,oldsrc187); ISET(input,oldinput186);
	if(fail189) goto alt184;
BSET(it,CALL(trans_Dead_Code_Deletercb_18,1,bind)); 
 BSET(_result_1,BGET(it));  
ISET(cut,Qnil);goto accept157;
alt184: ISET(input,oldinput158);if (IGET(cut)!=Qnil) goto fail;
  arg0=CALL(trans_Dead_Code_Deletercb_19,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt195);
 BSET(autovar_9,BGET(it)); VALUE oldinput197=IGET(input);  VALUE oldsrc198=IGET(src); int fail200=0;
ISET(src,BGET(autovar_9)); ISET(input,INT2FIX(0));
 BSET(it,CALL(trans_Dead_Code_Deletercb_20,1,bind)); 
 BSET(this_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass196;
	goto success199;
	pass196: fail200=1;
	success199: ISET(src,oldsrc198); ISET(input,oldinput197);
	if(fail200) goto alt195;
BSET(it,CALL(trans_Dead_Code_Deletercb_21,1,bind)); 
 BSET(_result_1,BGET(it));  
ISET(cut,Qnil);goto accept157;
alt195: ISET(input,oldinput158);if (IGET(cut)!=Qnil) goto fail;
  arg0=CALL(trans_Dead_Code_Deletercb_22,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt201);
 BSET(autovar_10,BGET(it)); VALUE oldinput203=IGET(input);  VALUE oldsrc204=IGET(src); int fail206=0;
ISET(src,BGET(autovar_10)); ISET(input,INT2FIX(0));
 BSET(it,CALL(trans_Dead_Code_Deletercb_23,1,bind)); 
 BSET(autovar_11,BGET(it)); VALUE oldinput208; while(1){oldinput208=IGET(input);   BSET(it,CALL(anything,0 )); FAILTEST(break207);
 BSET(autovar_12,BGET(it)); BSET(it,CALL(trans_Dead_Code_Deletercb_24,1,bind));  } break207: ISET(input,oldinput208); BSET(it,BGET(autovar_11));BSET(it,CALL(trans_Dead_Code_Deletercb_25,1,bind)); 
 BSET(this_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass202;
	goto success205;
	pass202: fail206=1;
	success205: ISET(src,oldsrc204); ISET(input,oldinput203);
	if(fail206) goto alt201;
BSET(it,CALL(trans_Dead_Code_Deletercb_26,1,bind)); 
 BSET(_result_1,BGET(it));  
ISET(cut,Qnil);goto accept157;
alt201: ISET(input,oldinput158);if (IGET(cut)!=Qnil) goto fail;
 BSET(it,rb_call_super(0,vals)); FAILTEST(alt209);
 BSET(_result_1,BGET(it));  
ISET(cut,Qnil);goto accept157;
  alt209:  ISET(input,oldinput158); goto fail;
 accept157:;
BSET(it,BGET(_result_1));
return BGET(_result_1);
fail: return failobj; }
VALUE cls_Communize_Or;
VALUE Communize_Or_trans(VALUE self );
VALUE Communize_Or_trans(VALUE self ){VALUE vals[0]; VALUE bind=rb_hash_new();  int x;VALUE arg0,arg1,arg2,arg3;
VALUE oldinput211=IGET(input);
alt212: ISET(input,oldinput211);if (IGET(cut)!=Qnil) goto fail;
  arg0=CALL(trans_Communize_Orcb_1,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt213);
 BSET(autovar_1,BGET(it)); VALUE oldinput215=IGET(input);  VALUE oldsrc216=IGET(src); int fail218=0;
ISET(src,BGET(autovar_1)); ISET(input,INT2FIX(0));
 VALUE oldinput221=IGET(input);
  arg0=CALL(trans_Communize_Orcb_2,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(reject220);
 BSET(autovar_2,BGET(it)); VALUE oldinput223=IGET(input);  VALUE oldsrc224=IGET(src); int fail226=0;
ISET(src,BGET(autovar_2)); ISET(input,INT2FIX(0));
   BSET(it,CALL(trans,0 )); FAILTEST(pass222);
 BSET(first_1,BGET(it)); BSET(it,CALL(trans_Communize_Orcb_3,1,bind)); 
 BSET(autovar_3,BGET(it)); VALUE oldinput228; while(1){oldinput228=IGET(input);   BSET(it,CALL(anything,0 )); FAILTEST(break227);
 BSET(autovar_4,BGET(it)); BSET(it,CALL(trans_Communize_Orcb_4,1,bind));  } break227: ISET(input,oldinput228); BSET(it,BGET(autovar_3));
	if (CALL(eof,0)==failobj) goto pass222;
	goto success225;
	pass222: fail226=1;
	success225: ISET(src,oldsrc224); ISET(input,oldinput223);
	if(fail226) goto reject220;
 x=1; goto accept219;  reject220: x=0; accept219: BSET(it,Qnil); ISET(input,oldinput221); if (x==0) goto pass214;BSET(it,CALL(trans_Communize_Orcb_5,1,bind)); 
 BSET(autovar_5,BGET(it)); VALUE oldinput230; while(1){oldinput230=IGET(input);  arg0=CALL(trans_Communize_Orcb_6,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(break229);
 BSET(autovar_6,BGET(it)); VALUE oldinput232=IGET(input);  VALUE oldsrc233=IGET(src); int fail235=0;
ISET(src,BGET(autovar_6)); ISET(input,INT2FIX(0));
   BSET(it,CALL(trans,0 )); FAILTEST(pass231);
 BSET(fst_1,BGET(it)); BSET(it,CALL(trans_Communize_Orcb_7,1,bind)); FAILTEST(pass231);BSET(it,CALL(trans_Communize_Orcb_8,1,bind)); 
 BSET(autovar_7,BGET(it)); VALUE oldinput237; while(1){oldinput237=IGET(input);   BSET(it,CALL(trans,0 )); FAILTEST(break236);
 BSET(autovar_8,BGET(it)); BSET(it,CALL(trans_Communize_Orcb_9,1,bind));  } break236: ISET(input,oldinput237); BSET(it,BGET(autovar_7));
 BSET(rest_1,BGET(it)); BSET(it,CALL(trans_Communize_Orcb_10,1,bind)); 
 BSET(autovar_9,BGET(it)); BSET(it,CALL(trans_Communize_Orcb_11,1,bind)); 
 BSET(autovar_10,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass231;
	goto success234;
	pass231: fail235=1;
	success234: ISET(src,oldsrc233); ISET(input,oldinput232);
	if(fail235) goto break229;
BSET(it,CALL(trans_Communize_Orcb_12,1,bind));  } break229: ISET(input,oldinput230); BSET(it,BGET(autovar_5));
	if (CALL(eof,0)==failobj) goto pass214;
	goto success217;
	pass214: fail218=1;
	success217: ISET(src,oldsrc216); ISET(input,oldinput215);
	if(fail218) goto alt213;
BSET(it,CALL(trans_Communize_Orcb_13,1,bind)); 
 BSET(_result_1,BGET(it));  
ISET(cut,Qnil);goto accept210;
alt213: ISET(input,oldinput211);if (IGET(cut)!=Qnil) goto fail;
 BSET(it,rb_call_super(0,vals)); FAILTEST(alt238);
 BSET(_result_1,BGET(it));  
ISET(cut,Qnil);goto accept210;
  alt238:  ISET(input,oldinput211); goto fail;
 accept210:;
BSET(it,BGET(_result_1));
return BGET(_result_1);
fail: return failobj; }
VALUE cls_Move_Assignments;
VALUE Move_Assignments_move(VALUE self ,VALUE a0,VALUE a1);
VALUE Move_Assignments_trans(VALUE self );
VALUE Move_Assignments_move(VALUE self ,VALUE a0,VALUE a1){VALUE vals[2]; VALUE bind=rb_hash_new(); BSET(append_1,a0); vals[0]=a0;BSET(name_1,a1); vals[1]=a1; int x;VALUE arg0,arg1,arg2,arg3;
VALUE oldinput260=IGET(input);
alt261: ISET(input,oldinput260);if (IGET(cut)!=Qnil) goto fail;
  arg0=CALL(move_Move_Assignmentscb_1,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt262);
 BSET(autovar_1,BGET(it)); VALUE oldinput264=IGET(input);  VALUE oldsrc265=IGET(src); int fail267=0;
ISET(src,BGET(autovar_1)); ISET(input,INT2FIX(0));
 BSET(it,CALL(move_Move_Assignmentscb_2,1,bind)); 
 BSET(autovar_2,BGET(it)); VALUE oldinput269; while(1){oldinput269=IGET(input);  arg0=CALL(move_Move_Assignmentscb_3,1,bind);arg1=CALL(move_Move_Assignmentscb_4,1,bind); BSET(it,CALL(move,2 ,arg0,arg1)); FAILTEST(break268);
 BSET(autovar_3,BGET(it)); BSET(it,CALL(move_Move_Assignmentscb_5,1,bind));  } break268: ISET(input,oldinput269); BSET(it,BGET(autovar_2));
 BSET(ary_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass263;
	goto success266;
	pass263: fail267=1;
	success266: ISET(src,oldsrc265); ISET(input,oldinput264);
	if(fail267) goto alt262;
BSET(it,CALL(move_Move_Assignmentscb_6,1,bind));
 BSET(_result_1,BGET(it));  
ISET(cut,Qnil);goto accept259;
alt262: ISET(input,oldinput260);if (IGET(cut)!=Qnil) goto fail;
  arg0=CALL(move_Move_Assignmentscb_7,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt270);
 BSET(autovar_4,BGET(it)); VALUE oldinput272=IGET(input);  VALUE oldsrc273=IGET(src); int fail275=0;
ISET(src,BGET(autovar_4)); ISET(input,INT2FIX(0));
 BSET(it,CALL(move_Move_Assignmentscb_8,1,bind)); 
 BSET(autovar_5,BGET(it)); VALUE oldinput277; while(1){oldinput277=IGET(input);   BSET(it,CALL(anything,0 )); FAILTEST(break276);
 BSET(el_1,BGET(it)); VALUE oldinput279=IGET(input);
alt280: ISET(input,oldinput279);if (IGET(cut)!=Qnil) goto break276;
 VALUE oldinput284=IGET(input);
   BSET(it,CALL(eof,0 )); FAILTEST(reject283); x=1; goto accept282;  reject283: x=0; accept282: BSET(it,Qnil); ISET(input,oldinput284); if (x==0) goto alt281;BSET(it,BGET(el_1));
 BSET(autovar_6,BGET(it)); VALUE oldinput286=IGET(input);  VALUE oldsrc287=IGET(src); int fail289=0;
ISET(src,rb_ary_new3(1,BGET(autovar_6))); ISET(input,INT2FIX(0));
  arg0=CALL(move_Move_Assignmentscb_9,1,bind);arg1=CALL(move_Move_Assignmentscb_10,1,bind); BSET(it,CALL(move,2 ,arg0,arg1)); FAILTEST(pass285);
 BSET(autovar_7,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass285;
	goto success288;
	pass285: fail289=1;
	success288: ISET(src,oldsrc287); ISET(input,oldinput286);
	if(fail289) goto alt281;
 
ISET(cut,Qnil);goto accept278;
alt281: ISET(input,oldinput279);if (IGET(cut)!=Qnil) goto break276;
 BSET(it,BGET(el_1));
 BSET(autovar_7,BGET(it));  
ISET(cut,Qnil);goto accept278;
  alt290:  ISET(input,oldinput279); goto break276;
 accept278:;
BSET(it,CALL(move_Move_Assignmentscb_11,1,bind));  } break276: ISET(input,oldinput277); BSET(it,BGET(autovar_5));
 BSET(ary_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass271;
	goto success274;
	pass271: fail275=1;
	success274: ISET(src,oldsrc273); ISET(input,oldinput272);
	if(fail275) goto alt270;
BSET(it,CALL(move_Move_Assignmentscb_12,1,bind));
 BSET(_result_1,BGET(it));  
ISET(cut,Qnil);goto accept259;
alt270: ISET(input,oldinput260);if (IGET(cut)!=Qnil) goto fail;
  arg0=CALL(move_Move_Assignmentscb_13,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt291);
 BSET(autovar_8,BGET(it)); VALUE oldinput293=IGET(input);  VALUE oldsrc294=IGET(src); int fail296=0;
ISET(src,BGET(autovar_8)); ISET(input,INT2FIX(0));
 BSET(it,CALL(move_Move_Assignmentscb_14,1,bind)); 
 BSET(var_1,BGET(it)); BSET(it,CALL(move_Move_Assignmentscb_15,1,bind)); 
 BSET(autovar_9,BGET(it)); VALUE oldinput298=IGET(input);  VALUE oldsrc299=IGET(src); int fail301=0;
ISET(src,rb_ary_new3(1,BGET(autovar_9))); ISET(input,INT2FIX(0));
  arg0=CALL(move_Move_Assignmentscb_16,1,bind);arg1=CALL(move_Move_Assignmentscb_17,1,bind); BSET(it,CALL(move,2 ,arg0,arg1)); FAILTEST(pass297);
 BSET(to_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass297;
	goto success300;
	pass297: fail301=1;
	success300: ISET(src,oldsrc299); ISET(input,oldinput298);
	if(fail301) goto pass292;
BSET(it,CALL(move_Move_Assignmentscb_18,1,bind)); 
 BSET(enter_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass292;
	goto success295;
	pass292: fail296=1;
	success295: ISET(src,oldsrc294); ISET(input,oldinput293);
	if(fail296) goto alt291;
BSET(it,CALL(move_Move_Assignmentscb_19,1,bind));
 BSET(_result_1,BGET(it));  
ISET(cut,Qnil);goto accept259;
alt291: ISET(input,oldinput260);if (IGET(cut)!=Qnil) goto fail;
   BSET(it,CALL(anything,0 )); FAILTEST(alt302);
 BSET(it_1,BGET(it)); BSET(it,CALL(move_Move_Assignmentscb_20,1,bind)); 
 BSET(_result_1,BGET(it));  
ISET(cut,Qnil);goto accept259;
  alt302:  ISET(input,oldinput260); goto fail;
 accept259:;
BSET(it,BGET(_result_1));
return BGET(_result_1);
fail: return failobj; }
VALUE Move_Assignments_trans(VALUE self ){VALUE vals[0]; VALUE bind=rb_hash_new();  int x;VALUE arg0,arg1,arg2,arg3;
VALUE oldinput240=IGET(input);
alt241: ISET(input,oldinput240);if (IGET(cut)!=Qnil) goto fail;
  arg0=CALL(trans_Move_Assignmentscb_1,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt242);
 BSET(autovar_1,BGET(it)); VALUE oldinput244=IGET(input);  VALUE oldsrc245=IGET(src); int fail247=0;
ISET(src,BGET(autovar_1)); ISET(input,INT2FIX(0));
 BSET(it,CALL(trans_Move_Assignmentscb_2,1,bind)); 
 BSET(name_1,BGET(it)); BSET(it,CALL(trans_Move_Assignmentscb_3,1,bind)); 
 BSET(autovar_2,BGET(it)); VALUE oldinput249=IGET(input);  VALUE oldsrc250=IGET(src); int fail252=0;
ISET(src,rb_ary_new3(1,BGET(autovar_2))); ISET(input,INT2FIX(0));
   BSET(it,CALL(trans,0 )); FAILTEST(pass248);
 BSET(expr_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass248;
	goto success251;
	pass248: fail252=1;
	success251: ISET(src,oldsrc250); ISET(input,oldinput249);
	if(fail252) goto pass243;
BSET(it,CALL(trans_Move_Assignmentscb_4,1,bind)); 
 BSET(append_1,BGET(it)); BSET(it,BGET(expr_1));
 BSET(autovar_3,BGET(it)); VALUE oldinput254=IGET(input);  VALUE oldsrc255=IGET(src); int fail257=0;
ISET(src,rb_ary_new3(1,BGET(autovar_3))); ISET(input,INT2FIX(0));
  arg0=CALL(trans_Move_Assignmentscb_5,1,bind);arg1=CALL(trans_Move_Assignmentscb_6,1,bind); BSET(it,CALL(move,2 ,arg0,arg1)); FAILTEST(pass253);
 BSET(_result_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass253;
	goto success256;
	pass253: fail257=1;
	success256: ISET(src,oldsrc255); ISET(input,oldinput254);
	if(fail257) goto pass243;

	if (CALL(eof,0)==failobj) goto pass243;
	goto success246;
	pass243: fail247=1;
	success246: ISET(src,oldsrc245); ISET(input,oldinput244);
	if(fail247) goto alt242;
 
ISET(cut,Qnil);goto accept239;
alt242: ISET(input,oldinput240);if (IGET(cut)!=Qnil) goto fail;
 BSET(it,rb_call_super(0,vals)); FAILTEST(alt258);
 BSET(_result_1,BGET(it));  
ISET(cut,Qnil);goto accept239;
  alt258:  ISET(input,oldinput240); goto fail;
 accept239:;
BSET(it,BGET(_result_1));
return BGET(_result_1);
fail: return failobj; }
void Init_dead_code_elimination_c(){ 
 cls_Dead_Code_Detector=rb_define_class("Dead_Code_Detector",rb_const_get(rb_cObject,rb_intern("AmethystOptimizer"))); 
failobj=rb_eval_string("FAIL");
rb_define_method(cls_Dead_Code_Detector,"trans",Dead_Code_Detector_trans,0);
rb_define_method(cls_Dead_Code_Detector,"vars_in",Dead_Code_Detector_vars_in,0);

 cls_Dead_Code_Deleter=rb_define_class("Dead_Code_Deleter",rb_const_get(rb_cObject,rb_intern("AmethystOptimizer"))); 
failobj=rb_eval_string("FAIL");
rb_define_method(cls_Dead_Code_Deleter,"trans",Dead_Code_Deleter_trans,0);

 cls_Communize_Or=rb_define_class("Communize_Or",rb_const_get(rb_cObject,rb_intern("AmethystOptimizer"))); 
failobj=rb_eval_string("FAIL");
rb_define_method(cls_Communize_Or,"trans",Communize_Or_trans,0);

 cls_Move_Assignments=rb_define_class("Move_Assignments",rb_const_get(rb_cObject,rb_intern("AmethystOptimizer"))); 
failobj=rb_eval_string("FAIL");
rb_define_method(cls_Move_Assignments,"move",Move_Assignments_move,2);
rb_define_method(cls_Move_Assignments,"trans",Move_Assignments_trans,0);
 }
