#include "cthyst.h"
VALUE cls_Analyze_Variables2;
VALUE Analyze_Variables2_flat(VALUE self );
VALUE Analyze_Variables2_itrans(VALUE self );
VALUE Analyze_Variables2_root(VALUE self );
VALUE Analyze_Variables2_visit(VALUE self );
VALUE Analyze_Variables2_flat(VALUE self ){VALUE vals[0]; VALUE bind=rb_hash_new();  int x;VALUE arg0,arg1,arg2,arg3;
BSET(it,CALL(flat_Analyze_Variables2cb26,1,bind)); 
 BSET(autovar_1,BGET(it)); VALUE oldinput82; while(1){oldinput82=IGET(input); VALUE oldinput84=IGET(input);
alt85: ISET(input,oldinput84);if (IGET(cut)!=Qnil) goto break81;
  arg0=CALL(flat_Analyze_Variables2cb27,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt86);
 BSET(autovar_2,BGET(it)); VALUE oldinput88=IGET(input);  VALUE oldsrc89=IGET(src); int fail91=0;
ISET(src,BGET(autovar_2)); ISET(input,INT2FIX(0));
   BSET(it,CALL(flat,0 )); FAILTEST(pass87);
 BSET(autovar_3,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass87;
	goto success90;
	pass87: fail91=1;
	success90: ISET(src,oldsrc89); ISET(input,oldinput88);
	if(fail91) goto alt86;
 
ISET(cut,Qnil);goto accept83;
alt86: ISET(input,oldinput84);if (IGET(cut)!=Qnil) goto break81;
  arg0=CALL(flat_Analyze_Variables2cb28,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt92);
 BSET(autovar_4,BGET(it)); VALUE oldinput94=IGET(input);  VALUE oldsrc95=IGET(src); int fail97=0;
ISET(src,BGET(autovar_4)); ISET(input,INT2FIX(0));
   BSET(it,CALL(flat,0 )); FAILTEST(pass93);
 BSET(autovar_3,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass93;
	goto success96;
	pass93: fail97=1;
	success96: ISET(src,oldsrc95); ISET(input,oldinput94);
	if(fail97) goto alt92;
 
ISET(cut,Qnil);goto accept83;
alt92: ISET(input,oldinput84);if (IGET(cut)!=Qnil) goto break81;
   BSET(it,CALL(anything,0 )); FAILTEST(alt98);
 BSET(autovar_3,BGET(it));  
ISET(cut,Qnil);goto accept83;
  alt98:  ISET(input,oldinput84); goto break81;
 accept83:;
BSET(it,CALL(flat_Analyze_Variables2cb29,1,bind));  } break81: ISET(input,oldinput82); BSET(it,BGET(autovar_1));
 BSET(_result_1,BGET(it)); BSET(it,BGET(_result_1));
return BGET(_result_1);
fail: return failobj; }
VALUE Analyze_Variables2_itrans(VALUE self ){VALUE vals[0]; VALUE bind=rb_hash_new();  int x;VALUE arg0,arg1,arg2,arg3;
BSET(it,CALL(itrans_Analyze_Variables2cb1,1,bind)); 
 BSET(autovar_1,BGET(it)); VALUE oldinput2; while(1){oldinput2=IGET(input); VALUE oldinput4=IGET(input);
alt5: ISET(input,oldinput4);if (IGET(cut)!=Qnil) goto break1;
  arg0=CALL(itrans_Analyze_Variables2cb2,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt6);
 BSET(autovar_2,BGET(it)); VALUE oldinput8=IGET(input);  VALUE oldsrc9=IGET(src); int fail11=0;
ISET(src,BGET(autovar_2)); ISET(input,INT2FIX(0));
 BSET(it,CALL(itrans_Analyze_Variables2cb3,1,bind)); 
 BSET(autovar_3,BGET(it)); VALUE oldinput13=IGET(input);  VALUE oldsrc14=IGET(src); int fail16=0;
ISET(src,rb_ary_new3(1,BGET(autovar_3))); ISET(input,INT2FIX(0));
   BSET(it,CALL(anything,0 )); FAILTEST(pass12);
 BSET(autovar_4,BGET(it)); VALUE oldinput18=IGET(input);  VALUE oldsrc19=IGET(src); int fail21=0;
ISET(src,BGET(autovar_4)); ISET(input,INT2FIX(0));
 BSET(it,CALL(itrans_Analyze_Variables2cb4,1,bind)); 
 BSET(autovar_5,BGET(it)); VALUE oldinput23; while(1){oldinput23=IGET(input);  arg0=CALL(itrans_Analyze_Variables2cb5,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(break22);
 BSET(autovar_6,BGET(it)); VALUE oldinput25=IGET(input);  VALUE oldsrc26=IGET(src); int fail28=0;
ISET(src,BGET(autovar_6)); ISET(input,INT2FIX(0));
   BSET(it,CALL(root,0 )); FAILTEST(pass24);
 BSET(autovar_7,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass24;
	goto success27;
	pass24: fail28=1;
	success27: ISET(src,oldsrc26); ISET(input,oldinput25);
	if(fail28) goto break22;
BSET(it,CALL(itrans_Analyze_Variables2cb6,1,bind));  } break22: ISET(input,oldinput23); BSET(it,BGET(autovar_5));
 BSET(rules_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass17;
	goto success20;
	pass17: fail21=1;
	success20: ISET(src,oldsrc19); ISET(input,oldinput18);
	if(fail21) goto pass12;

	if (CALL(eof,0)==failobj) goto pass12;
	goto success15;
	pass12: fail16=1;
	success15: ISET(src,oldsrc14); ISET(input,oldinput13);
	if(fail16) goto pass7;
BSET(it,CALL(itrans_Analyze_Variables2cb7,1,bind)); BSET(it,CALL(itrans_Analyze_Variables2cb8,1,bind)); 
 BSET(autovar_8,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass7;
	goto success10;
	pass7: fail11=1;
	success10: ISET(src,oldsrc9); ISET(input,oldinput8);
	if(fail11) goto alt6;
 
ISET(cut,Qnil);goto accept3;
alt6: ISET(input,oldinput4);if (IGET(cut)!=Qnil) goto break1;
   BSET(it,CALL(anything,0 )); FAILTEST(alt29);
 BSET(autovar_8,BGET(it));  
ISET(cut,Qnil);goto accept3;
  alt29:  ISET(input,oldinput4); goto break1;
 accept3:;
BSET(it,CALL(itrans_Analyze_Variables2cb9,1,bind));  } break1: ISET(input,oldinput2); BSET(it,BGET(autovar_1));
 BSET(_result_1,BGET(it)); BSET(it,BGET(_result_1));
return BGET(_result_1);
fail: return failobj; }
VALUE Analyze_Variables2_root(VALUE self ){VALUE vals[0]; VALUE bind=rb_hash_new();  int x;VALUE arg0,arg1,arg2,arg3;
BSET(it,CALL(root_Analyze_Variables2cb10,1,bind)); 
 BSET(autovar_1,BGET(it)); VALUE oldinput31=IGET(input);  VALUE oldsrc32=IGET(src); int fail34=0;
ISET(src,rb_ary_new3(1,BGET(autovar_1))); ISET(input,INT2FIX(0));
  arg0=CALL(root_Analyze_Variables2cb11,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(pass30);
 BSET(autovar_2,BGET(it)); VALUE oldinput36=IGET(input);  VALUE oldsrc37=IGET(src); int fail39=0;
ISET(src,BGET(autovar_2)); ISET(input,INT2FIX(0));
 BSET(it,CALL(root_Analyze_Variables2cb12,1,bind)); BSET(it,CALL(root_Analyze_Variables2cb13,1,bind));   BSET(it,CALL(traverse,0 )); FAILTEST(pass35);BSET(it,CALL(root_Analyze_Variables2cb14,1,bind)); BSET(it,CALL(root_Analyze_Variables2cb15,1,bind)); 
 BSET(_result_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass35;
	goto success38;
	pass35: fail39=1;
	success38: ISET(src,oldsrc37); ISET(input,oldinput36);
	if(fail39) goto pass30;

	if (CALL(eof,0)==failobj) goto pass30;
	goto success33;
	pass30: fail34=1;
	success33: ISET(src,oldsrc32); ISET(input,oldinput31);
	if(fail34) goto fail;
BSET(it,BGET(_result_1));
return BGET(_result_1);
fail: return failobj; }
VALUE Analyze_Variables2_visit(VALUE self ){VALUE vals[0]; VALUE bind=rb_hash_new();  int x;VALUE arg0,arg1,arg2,arg3;
VALUE oldinput41=IGET(input);
alt42: ISET(input,oldinput41);if (IGET(cut)!=Qnil) goto fail;
  arg0=CALL(visit_Analyze_Variables2cb16,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt43);
 BSET(autovar_1,BGET(it)); VALUE oldinput45=IGET(input);  VALUE oldsrc46=IGET(src); int fail48=0;
ISET(src,BGET(autovar_1)); ISET(input,INT2FIX(0));
   BSET(it,CALL(traverse,0 )); FAILTEST(pass44);BSET(it,CALL(visit_Analyze_Variables2cb17,1,bind)); 
 BSET(autovar_2,BGET(it)); VALUE oldinput50=IGET(input);  VALUE oldsrc51=IGET(src); int fail53=0;
ISET(src,rb_ary_new3(1,BGET(autovar_2))); ISET(input,INT2FIX(0));
   BSET(it,CALL(anything,0 )); FAILTEST(pass49);
 BSET(autovar_3,BGET(it)); VALUE oldinput55=IGET(input);  VALUE oldsrc56=IGET(src); int fail58=0;
ISET(src,BGET(autovar_3)); ISET(input,INT2FIX(0));
   BSET(it,CALL(flat,0 )); FAILTEST(pass54);
 BSET(a_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass54;
	goto success57;
	pass54: fail58=1;
	success57: ISET(src,oldsrc56); ISET(input,oldinput55);
	if(fail58) goto pass49;

	if (CALL(eof,0)==failobj) goto pass49;
	goto success52;
	pass49: fail53=1;
	success52: ISET(src,oldsrc51); ISET(input,oldinput50);
	if(fail53) goto pass44;
BSET(it,CALL(visit_Analyze_Variables2cb18,1,bind)); BSET(it,CALL(visit_Analyze_Variables2cb19,1,bind)); 
 BSET(_result_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass44;
	goto success47;
	pass44: fail48=1;
	success47: ISET(src,oldsrc46); ISET(input,oldinput45);
	if(fail48) goto alt43;
 
ISET(cut,Qnil);goto accept40;
alt43: ISET(input,oldinput41);if (IGET(cut)!=Qnil) goto fail;
  arg0=CALL(visit_Analyze_Variables2cb20,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt59);
 BSET(autovar_4,BGET(it)); VALUE oldinput61=IGET(input);  VALUE oldsrc62=IGET(src); int fail64=0;
ISET(src,BGET(autovar_4)); ISET(input,INT2FIX(0));
   BSET(it,CALL(traverse,0 )); FAILTEST(pass60);BSET(it,CALL(visit_Analyze_Variables2cb21,1,bind)); 
 BSET(autovar_5,BGET(it)); VALUE oldinput66=IGET(input);  VALUE oldsrc67=IGET(src); int fail69=0;
ISET(src,rb_ary_new3(1,BGET(autovar_5))); ISET(input,INT2FIX(0));
   BSET(it,CALL(anything,0 )); FAILTEST(pass65);
 BSET(autovar_6,BGET(it)); VALUE oldinput71=IGET(input);  VALUE oldsrc72=IGET(src); int fail74=0;
ISET(src,BGET(autovar_6)); ISET(input,INT2FIX(0));
  arg0=CALL(visit_Analyze_Variables2cb22,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(pass70);
 BSET(_result_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass70;
	goto success73;
	pass70: fail74=1;
	success73: ISET(src,oldsrc72); ISET(input,oldinput71);
	if(fail74) goto pass65;

	if (CALL(eof,0)==failobj) goto pass65;
	goto success68;
	pass65: fail69=1;
	success68: ISET(src,oldsrc67); ISET(input,oldinput66);
	if(fail69) goto pass60;

	if (CALL(eof,0)==failobj) goto pass60;
	goto success63;
	pass60: fail64=1;
	success63: ISET(src,oldsrc62); ISET(input,oldinput61);
	if(fail64) goto alt59;
 
ISET(cut,Qnil);goto accept40;
alt59: ISET(input,oldinput41);if (IGET(cut)!=Qnil) goto fail;
  arg0=CALL(visit_Analyze_Variables2cb23,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt75);
 BSET(autovar_7,BGET(it)); VALUE oldinput77=IGET(input);  VALUE oldsrc78=IGET(src); int fail80=0;
ISET(src,BGET(autovar_7)); ISET(input,INT2FIX(0));
 BSET(it,CALL(visit_Analyze_Variables2cb24,1,bind)); BSET(it,CALL(visit_Analyze_Variables2cb25,1,bind)); 
 BSET(_result_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass76;
	goto success79;
	pass76: fail80=1;
	success79: ISET(src,oldsrc78); ISET(input,oldinput77);
	if(fail80) goto alt75;
 
ISET(cut,Qnil);goto accept40;
  alt75:  ISET(input,oldinput41); goto fail;
 accept40:;
BSET(it,BGET(_result_1));
return BGET(_result_1);
fail: return failobj; }
void Init_Analyze_Variables2(){ cls_Analyze_Variables2=rb_define_class("Analyze_Variables2",rb_const_get(rb_cObject,rb_intern("Traverser"))); 
failobj=rb_eval_string("FAIL");
rb_define_method(cls_Analyze_Variables2,"flat",Analyze_Variables2_flat,0);
rb_define_method(cls_Analyze_Variables2,"itrans",Analyze_Variables2_itrans,0);
rb_define_method(cls_Analyze_Variables2,"root",Analyze_Variables2_root,0);
rb_define_method(cls_Analyze_Variables2,"visit",Analyze_Variables2_visit,0);
rb_eval_string("class Analyze_Variables2 < Traverser\ndef flat_Analyze_Variables2cb26(bind)\n[]\nend\ndef flat_Analyze_Variables2cb27(bind)\nArgs\nend\ndef flat_Analyze_Variables2cb28(bind)\nStrin\nend\ndef flat_Analyze_Variables2cb29(bind)\nbind[:autovar_1]||=[];_append(bind[:autovar_1],bind[:autovar_3])\nend\ndef itrans_Analyze_Variables2cb1(bind)\n[]\nend\ndef itrans_Analyze_Variables2cb2(bind)\nGrammar\nend\ndef itrans_Analyze_Variables2cb3(bind)\n@src.rules\nend\ndef itrans_Analyze_Variables2cb4(bind)\n[]\nend\ndef itrans_Analyze_Variables2cb5(bind)\nRule\nend\ndef itrans_Analyze_Variables2cb6(bind)\nbind[:autovar_5]||=[];_append(bind[:autovar_5],bind[:autovar_7])\nend\ndef itrans_Analyze_Variables2cb7(bind)\n@src.rules=bind[:rules_1]\nend\ndef itrans_Analyze_Variables2cb8(bind)\n@src.self\nend\ndef itrans_Analyze_Variables2cb9(bind)\nbind[:autovar_1]||=[];_append(bind[:autovar_1],bind[:autovar_8])\nend\ndef root_Analyze_Variables2cb10(bind)\n@src.self\nend\ndef root_Analyze_Variables2cb11(bind)\nRule\nend\ndef root_Analyze_Variables2cb12(bind)\n@variables=Hash.new{|k,v| k[v]=v} ;(@src.locals+@src.args).each{|v| @variables[v[0]]=v}\nend\ndef root_Analyze_Variables2cb13(bind)\n@locals=@src.locals\nend\ndef root_Analyze_Variables2cb14(bind)\n@src.body=Seq[{:ary=>[@src.body] }];@src.locals=nil\nend\ndef root_Analyze_Variables2cb15(bind)\n@src.self\nend\ndef visit_Analyze_Variables2cb16(bind)\nArgs\nend\ndef visit_Analyze_Variables2cb17(bind)\n@src.ary.map{|bind[:a_1]| @variables[bind[:a_1]] }\nend\ndef visit_Analyze_Variables2cb18(bind)\n@src.ary=connectstring(bind[:a_1].flatten)\nend\ndef visit_Analyze_Variables2cb19(bind)\n(@src.ary.size==1&&(@src.ary[0].is_a?(Local)||@src.ary[0].is_a?(Global)||@src.ary[0].is_a?(Key))) ? @src.ary[0] : @src.self\nend\ndef visit_Analyze_Variables2cb20(bind)\nAct\nend\ndef visit_Analyze_Variables2cb21(bind)\n@src.ary\nend\ndef visit_Analyze_Variables2cb22(bind)\nLocal\nend\ndef visit_Analyze_Variables2cb23(bind)\nResult\nend\ndef visit_Analyze_Variables2cb24(bind)\n@src.vars=@locals.select{|bind[:a_1]| @src.vars.include? bind[:a_1][0].to_sym}.uniq\nend\ndef visit_Analyze_Variables2cb25(bind)\n@src.self\nend\n\nend");
}
