#include "cthyst.h"
VALUE cls_AmethystOptimizer;
VALUE AmethystOptimizer_arg(VALUE self );
VALUE AmethystOptimizer_args(VALUE self );
VALUE AmethystOptimizer_itrans(VALUE self );
VALUE AmethystOptimizer_trans(VALUE self );
VALUE AmethystOptimizer_transfn(VALUE self );
VALUE AmethystOptimizer_transs(VALUE self );
VALUE AmethystOptimizer_arg(VALUE self ){VALUE vals[0]; VALUE bind=rb_hash_new();  int x;VALUE arg0,arg1,arg2,arg3;
VALUE oldinput1=IGET(input);
alt1_1: ISET(input,oldinput1);if (IGET(cut)!=Qnil) goto fail;
  arg0=CALL(arg_AmethystOptimizercb_1,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt1_2);
 BSET(autovar_1,BGET(it)); VALUE oldinput2=IGET(input);  VALUE oldsrc1=IGET(src); int fail1=0;
ISET(src,BGET(autovar_1)); ISET(input,INT2FIX(0));
 BSET(it,CALL(arg_AmethystOptimizercb_2,1,bind)); 
 BSET(autovar_2,BGET(it)); VALUE oldinput3; while(1){oldinput3=IGET(input);   BSET(it,CALL(arg,0 )); FAILTEST(break1);
 BSET(autovar_3,BGET(it)); BSET(it,CALL(arg_AmethystOptimizercb_3,1,bind));  if (IGET(stop)!=Qnil){{oldinput3=IGET(input);goto break1;} } } break1: ISET(stop,Qnil);  ISET(input,oldinput3); BSET(it,BGET(autovar_2));
 BSET(ary_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass1;
	goto success1;
	pass1: fail1=1;
	success1: ISET(src,oldsrc1); ISET(input,oldinput2);
	if(fail1) goto alt1_2;
BSET(it,CALL(arg_AmethystOptimizercb_4,1,bind));
 BSET(_result_1,BGET(it));  
ISET(cut,Qnil);goto accept1;
alt1_2: ISET(input,oldinput1);if (IGET(cut)!=Qnil) goto fail;
  arg0=CALL(arg_AmethystOptimizercb_5,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt1_3);
 BSET(autovar_4,BGET(it)); VALUE oldinput4=IGET(input);  VALUE oldsrc2=IGET(src); int fail2=0;
ISET(src,BGET(autovar_4)); ISET(input,INT2FIX(0));
 BSET(it,CALL(arg_AmethystOptimizercb_6,1,bind)); 
 BSET(autovar_5,BGET(it)); VALUE oldinput5; while(1){oldinput5=IGET(input); VALUE oldinput6=IGET(input);
alt2_1: ISET(input,oldinput6);if (IGET(cut)!=Qnil) goto break2;
   BSET(it,CALL(char,0 )); FAILTEST(alt2_2);
 BSET(autovar_6,BGET(it));  
ISET(cut,Qnil);goto accept2;
alt2_2: ISET(input,oldinput6);if (IGET(cut)!=Qnil) goto break2;
   BSET(it,CALL(arg,0 )); FAILTEST(alt2_3);
 BSET(autovar_6,BGET(it));  
ISET(cut,Qnil);goto accept2;
  alt2_3:  ISET(input,oldinput6); goto break2;
 accept2:;
BSET(it,CALL(arg_AmethystOptimizercb_7,1,bind));  if (IGET(stop)!=Qnil){{oldinput5=IGET(input);goto break2;} } } break2: ISET(stop,Qnil);  ISET(input,oldinput5); BSET(it,BGET(autovar_5));
 BSET(ary_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass2;
	goto success2;
	pass2: fail2=1;
	success2: ISET(src,oldsrc2); ISET(input,oldinput4);
	if(fail2) goto alt1_3;
BSET(it,CALL(arg_AmethystOptimizercb_8,1,bind));
 BSET(_result_1,BGET(it));  
ISET(cut,Qnil);goto accept1;
alt1_3: ISET(input,oldinput1);if (IGET(cut)!=Qnil) goto fail;
  arg0=CALL(arg_AmethystOptimizercb_9,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt1_4);
 BSET(autovar_7,BGET(it)); VALUE oldinput7=IGET(input);  VALUE oldsrc3=IGET(src); int fail3=0;
ISET(src,BGET(autovar_7)); ISET(input,INT2FIX(0));
   BSET(it,CALL(transfn,0 )); FAILTEST(pass3);
 BSET(autovar_8,BGET(it)); BSET(it,CALL(arg_AmethystOptimizercb_10,1,bind)); 
	if (CALL(eof,0)==failobj) goto pass3;
	goto success3;
	pass3: fail3=1;
	success3: ISET(src,oldsrc3); ISET(input,oldinput7);
	if(fail3) goto alt1_4;
BSET(it,CALL(arg_AmethystOptimizercb_11,1,bind));
 BSET(_result_1,BGET(it));  
ISET(cut,Qnil);goto accept1;
alt1_4: ISET(input,oldinput1);if (IGET(cut)!=Qnil) goto fail;
  arg0=CALL(arg_AmethystOptimizercb_12,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt1_5);
 BSET(autovar_9,BGET(it)); VALUE oldinput8=IGET(input);  VALUE oldsrc4=IGET(src); int fail4=0;
ISET(src,BGET(autovar_9)); ISET(input,INT2FIX(0));
 BSET(it,CALL(arg_AmethystOptimizercb_13,1,bind)); 
 BSET(name_1,BGET(it)); BSET(it,CALL(arg_AmethystOptimizercb_14,1,bind)); 
 BSET(autovar_10,BGET(it)); VALUE oldinput9=IGET(input);  VALUE oldsrc5=IGET(src); int fail5=0;
ISET(src,rb_ary_new3(1,BGET(autovar_10))); ISET(input,INT2FIX(0));
   BSET(it,CALL(args,0 )); FAILTEST(pass5);
 BSET(args_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass5;
	goto success5;
	pass5: fail5=1;
	success5: ISET(src,oldsrc5); ISET(input,oldinput9);
	if(fail5) goto pass4;
BSET(it,CALL(arg_AmethystOptimizercb_15,1,bind)); 
 BSET(autovar_11,BGET(it)); VALUE oldinput10=IGET(input);  VALUE oldsrc6=IGET(src); int fail6=0;
ISET(src,rb_ary_new3(1,BGET(autovar_11))); ISET(input,INT2FIX(0));
   BSET(it,CALL(args,0 )); FAILTEST(pass6);
 BSET(vars_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass6;
	goto success6;
	pass6: fail6=1;
	success6: ISET(src,oldsrc6); ISET(input,oldinput10);
	if(fail6) goto pass4;

	if (CALL(eof,0)==failobj) goto pass4;
	goto success4;
	pass4: fail4=1;
	success4: ISET(src,oldsrc4); ISET(input,oldinput8);
	if(fail4) goto alt1_5;
BSET(it,CALL(arg_AmethystOptimizercb_16,1,bind));
 BSET(_result_1,BGET(it));  
ISET(cut,Qnil);goto accept1;
alt1_5: ISET(input,oldinput1);if (IGET(cut)!=Qnil) goto fail;
   BSET(it,CALL(anything,0 )); FAILTEST(alt1_6);
 BSET(_result_1,BGET(it));  
ISET(cut,Qnil);goto accept1;
  alt1_6:  ISET(input,oldinput1); goto fail;
 accept1:;
BSET(it,BGET(_result_1));
return BGET(it);
fail: return failobj; }
VALUE AmethystOptimizer_args(VALUE self ){VALUE vals[0]; VALUE bind=rb_hash_new();  int x;VALUE arg0,arg1,arg2,arg3;
VALUE oldinput1=IGET(input);
alt1_1: ISET(input,oldinput1);if (IGET(cut)!=Qnil) goto fail;
  arg0=CALL(args_AmethystOptimizercb_1,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt1_2);
 BSET(autovar_1,BGET(it)); VALUE oldinput2=IGET(input);  VALUE oldsrc1=IGET(src); int fail1=0;
ISET(src,BGET(autovar_1)); ISET(input,INT2FIX(0));
 BSET(it,CALL(args_AmethystOptimizercb_2,1,bind)); 
 BSET(autovar_2,BGET(it)); VALUE oldinput3; while(1){oldinput3=IGET(input);   BSET(it,CALL(arg,0 )); FAILTEST(break1);
 BSET(autovar_3,BGET(it)); BSET(it,CALL(args_AmethystOptimizercb_3,1,bind));  if (IGET(stop)!=Qnil){{oldinput3=IGET(input);goto break1;} } } break1: ISET(stop,Qnil);  ISET(input,oldinput3); BSET(it,BGET(autovar_2));
 BSET(a_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass1;
	goto success1;
	pass1: fail1=1;
	success1: ISET(src,oldsrc1); ISET(input,oldinput2);
	if(fail1) goto alt1_2;
BSET(it,BGET(a_1));
 BSET(_result_1,BGET(it));  
ISET(cut,Qnil);goto accept1;
alt1_2: ISET(input,oldinput1);if (IGET(cut)!=Qnil) goto fail;
 BSET(it,CALL(args_AmethystOptimizercb_4,1,bind)); 
 BSET(autovar_4,BGET(it)); VALUE oldinput4; while(1){oldinput4=IGET(input);   BSET(it,CALL(arg,0 )); FAILTEST(break2);
 BSET(autovar_5,BGET(it)); BSET(it,CALL(args_AmethystOptimizercb_5,1,bind));  if (IGET(stop)!=Qnil){{oldinput4=IGET(input);goto break2;} } } break2: ISET(stop,Qnil);  ISET(input,oldinput4); BSET(it,BGET(autovar_4));
 BSET(_result_1,BGET(it));  
ISET(cut,Qnil);goto accept1;
  alt1_3:  ISET(input,oldinput1); goto fail;
 accept1:;
BSET(it,BGET(_result_1));
return BGET(it);
fail: return failobj; }
VALUE AmethystOptimizer_itrans(VALUE self ){VALUE vals[0]; VALUE bind=rb_hash_new();  int x;VALUE arg0,arg1,arg2,arg3;
BSET(it,CALL(itrans_AmethystOptimizercb_1,1,bind)); 
 BSET(autovar_1,BGET(it)); VALUE oldinput1; while(1){oldinput1=IGET(input); VALUE oldinput2=IGET(input);
alt1_1: ISET(input,oldinput2);if (IGET(cut)!=Qnil) goto break1;
   BSET(it,CALL(char,0 )); FAILTEST(alt1_2);
 BSET(autovar_2,BGET(it));  
ISET(cut,Qnil);goto accept1;
alt1_2: ISET(input,oldinput2);if (IGET(cut)!=Qnil) goto break1;
   BSET(it,CALL(trans,0 )); FAILTEST(alt1_3);
 BSET(autovar_2,BGET(it));  
ISET(cut,Qnil);goto accept1;
  alt1_3:  ISET(input,oldinput2); goto break1;
 accept1:;
BSET(it,CALL(itrans_AmethystOptimizercb_2,1,bind));  if (IGET(stop)!=Qnil){{oldinput1=IGET(input);goto break1;} } } break1: ISET(stop,Qnil);  ISET(input,oldinput1); BSET(it,BGET(autovar_1));
 BSET(r_1,BGET(it)); BSET(it,BGET(r_1));
 BSET(_result_1,BGET(it)); BSET(it,BGET(_result_1));
return BGET(it);
fail: return failobj; }
VALUE AmethystOptimizer_trans(VALUE self ){VALUE vals[0]; VALUE bind=rb_hash_new();  int x;VALUE arg0,arg1,arg2,arg3;
VALUE oldinput1=IGET(input);
alt1_1: ISET(input,oldinput1);if (IGET(cut)!=Qnil) goto fail;
  arg0=CALL(trans_AmethystOptimizercb_1,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt1_2);
 BSET(autovar_1,BGET(it)); VALUE oldinput2=IGET(input);  VALUE oldsrc1=IGET(src); int fail1=0;
ISET(src,BGET(autovar_1)); ISET(input,INT2FIX(0));
 BSET(it,CALL(trans_AmethystOptimizercb_2,1,bind)); 
 BSET(name_1,BGET(it)); BSET(it,CALL(trans_AmethystOptimizercb_3,1,bind)); 
 BSET(parent_1,BGET(it)); BSET(it,CALL(trans_AmethystOptimizercb_4,1,bind)); 
 BSET(autovar_2,BGET(it)); VALUE oldinput3=IGET(input);  VALUE oldsrc2=IGET(src); int fail2=0;
ISET(src,rb_ary_new3(1,BGET(autovar_2))); ISET(input,INT2FIX(0));
   BSET(it,CALL(transs,0 )); FAILTEST(pass2);
 BSET(rules_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass2;
	goto success2;
	pass2: fail2=1;
	success2: ISET(src,oldsrc2); ISET(input,oldinput3);
	if(fail2) goto pass1;

	if (CALL(eof,0)==failobj) goto pass1;
	goto success1;
	pass1: fail1=1;
	success1: ISET(src,oldsrc1); ISET(input,oldinput2);
	if(fail1) goto alt1_2;
BSET(it,CALL(trans_AmethystOptimizercb_5,1,bind));
 BSET(_result_1,BGET(it));  
ISET(cut,Qnil);goto accept1;
alt1_2: ISET(input,oldinput1);if (IGET(cut)!=Qnil) goto fail;
  arg0=CALL(trans_AmethystOptimizercb_6,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt1_3);
 BSET(autovar_3,BGET(it)); VALUE oldinput4=IGET(input);  VALUE oldsrc3=IGET(src); int fail3=0;
ISET(src,BGET(autovar_3)); ISET(input,INT2FIX(0));
 BSET(it,CALL(trans_AmethystOptimizercb_7,1,bind)); 
 BSET(name_1,BGET(it)); BSET(it,CALL(trans_AmethystOptimizercb_8,1,bind)); 
 BSET(autovar_4,BGET(it)); VALUE oldinput5=IGET(input);  VALUE oldsrc4=IGET(src); int fail4=0;
ISET(src,rb_ary_new3(1,BGET(autovar_4))); ISET(input,INT2FIX(0));
   BSET(it,CALL(args,0 )); FAILTEST(pass4);
 BSET(args_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass4;
	goto success4;
	pass4: fail4=1;
	success4: ISET(src,oldsrc4); ISET(input,oldinput5);
	if(fail4) goto pass3;
BSET(it,CALL(trans_AmethystOptimizercb_9,1,bind)); 
 BSET(autovar_5,BGET(it)); VALUE oldinput6=IGET(input);  VALUE oldsrc5=IGET(src); int fail5=0;
ISET(src,rb_ary_new3(1,BGET(autovar_5))); ISET(input,INT2FIX(0));
   BSET(it,CALL(trans,0 )); FAILTEST(pass5);
 BSET(body_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass5;
	goto success5;
	pass5: fail5=1;
	success5: ISET(src,oldsrc5); ISET(input,oldinput6);
	if(fail5) goto pass3;
BSET(it,CALL(trans_AmethystOptimizercb_10,1,bind)); 
 BSET(bnding_1,BGET(it)); BSET(it,CALL(trans_AmethystOptimizercb_11,1,bind)); 
 BSET(locals_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass3;
	goto success3;
	pass3: fail3=1;
	success3: ISET(src,oldsrc3); ISET(input,oldinput4);
	if(fail3) goto alt1_3;
BSET(it,CALL(trans_AmethystOptimizercb_12,1,bind));
 BSET(_result_1,BGET(it));  
ISET(cut,Qnil);goto accept1;
alt1_3: ISET(input,oldinput1);if (IGET(cut)!=Qnil) goto fail;
  arg0=CALL(trans_AmethystOptimizercb_13,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt1_4);
 BSET(autovar_6,BGET(it)); VALUE oldinput7=IGET(input);  VALUE oldsrc6=IGET(src); int fail6=0;
ISET(src,BGET(autovar_6)); ISET(input,INT2FIX(0));
 BSET(it,CALL(trans_AmethystOptimizercb_14,1,bind)); 
 BSET(autovar_7,BGET(it)); VALUE oldinput8; while(1){oldinput8=IGET(input);   BSET(it,CALL(transfn,0 )); FAILTEST(break1);
 BSET(autovar_8,BGET(it)); BSET(it,CALL(trans_AmethystOptimizercb_15,1,bind));  if (IGET(stop)!=Qnil){{oldinput8=IGET(input);goto break1;} } } break1: ISET(stop,Qnil);  ISET(input,oldinput8); BSET(it,BGET(autovar_7));
 BSET(ary_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass6;
	goto success6;
	pass6: fail6=1;
	success6: ISET(src,oldsrc6); ISET(input,oldinput7);
	if(fail6) goto alt1_4;
BSET(it,CALL(trans_AmethystOptimizercb_16,1,bind));
 BSET(_result_1,BGET(it));  
ISET(cut,Qnil);goto accept1;
alt1_4: ISET(input,oldinput1);if (IGET(cut)!=Qnil) goto fail;
  arg0=CALL(trans_AmethystOptimizercb_17,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt1_5);
 BSET(autovar_9,BGET(it)); VALUE oldinput9=IGET(input);  VALUE oldsrc7=IGET(src); int fail7=0;
ISET(src,BGET(autovar_9)); ISET(input,INT2FIX(0));
 BSET(it,CALL(trans_AmethystOptimizercb_18,1,bind)); 
 BSET(autovar_10,BGET(it)); VALUE oldinput10; while(1){oldinput10=IGET(input);   BSET(it,CALL(trans,0 )); FAILTEST(break2);
 BSET(autovar_11,BGET(it)); BSET(it,CALL(trans_AmethystOptimizercb_19,1,bind));  if (IGET(stop)!=Qnil){{oldinput10=IGET(input);goto break2;} } } break2: ISET(stop,Qnil);  ISET(input,oldinput10); BSET(it,BGET(autovar_10));
 BSET(ary_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass7;
	goto success7;
	pass7: fail7=1;
	success7: ISET(src,oldsrc7); ISET(input,oldinput9);
	if(fail7) goto alt1_5;
BSET(it,CALL(trans_AmethystOptimizercb_20,1,bind));
 BSET(_result_1,BGET(it));  
ISET(cut,Qnil);goto accept1;
alt1_5: ISET(input,oldinput1);if (IGET(cut)!=Qnil) goto fail;
  arg0=CALL(trans_AmethystOptimizercb_21,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt1_6);
 BSET(autovar_12,BGET(it)); VALUE oldinput11=IGET(input);  VALUE oldsrc8=IGET(src); int fail8=0;
ISET(src,BGET(autovar_12)); ISET(input,INT2FIX(0));
   BSET(it,CALL(trans,0 )); FAILTEST(pass8);
 BSET(autovar_13,BGET(it)); BSET(it,CALL(trans_AmethystOptimizercb_22,1,bind)); BSET(it,CALL(trans_AmethystOptimizercb_23,1,bind)); 
 BSET(neg_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass8;
	goto success8;
	pass8: fail8=1;
	success8: ISET(src,oldsrc8); ISET(input,oldinput11);
	if(fail8) goto alt1_6;
BSET(it,CALL(trans_AmethystOptimizercb_24,1,bind));
 BSET(_result_1,BGET(it));  
ISET(cut,Qnil);goto accept1;
alt1_6: ISET(input,oldinput1);if (IGET(cut)!=Qnil) goto fail;
  arg0=CALL(trans_AmethystOptimizercb_25,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt1_7);
 BSET(autovar_14,BGET(it)); VALUE oldinput12=IGET(input);  VALUE oldsrc9=IGET(src); int fail9=0;
ISET(src,BGET(autovar_14)); ISET(input,INT2FIX(0));
 BSET(it,CALL(trans_AmethystOptimizercb_26,1,bind)); 
 BSET(autovar_15,BGET(it)); VALUE oldinput13; while(1){oldinput13=IGET(input);   BSET(it,CALL(anything,0 )); FAILTEST(break3);
 BSET(autovar_16,BGET(it)); BSET(it,CALL(trans_AmethystOptimizercb_27,1,bind));  if (IGET(stop)!=Qnil){{oldinput13=IGET(input);goto break3;} } } break3: ISET(stop,Qnil);  ISET(input,oldinput13); BSET(it,BGET(autovar_15));
 BSET(ary_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass9;
	goto success9;
	pass9: fail9=1;
	success9: ISET(src,oldsrc9); ISET(input,oldinput12);
	if(fail9) goto alt1_7;
BSET(it,CALL(trans_AmethystOptimizercb_28,1,bind));
 BSET(_result_1,BGET(it));  
ISET(cut,Qnil);goto accept1;
alt1_7: ISET(input,oldinput1);if (IGET(cut)!=Qnil) goto fail;
  arg0=CALL(trans_AmethystOptimizercb_29,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt1_8);
 BSET(autovar_17,BGET(it)); VALUE oldinput14=IGET(input);  VALUE oldsrc10=IGET(src); int fail10=0;
ISET(src,BGET(autovar_17)); ISET(input,INT2FIX(0));
   BSET(it,CALL(trans,0 )); FAILTEST(pass10);
 BSET(autovar_18,BGET(it)); BSET(it,CALL(trans_AmethystOptimizercb_30,1,bind)); BSET(it,CALL(trans_AmethystOptimizercb_31,1,bind)); 
 BSET(o_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass10;
	goto success10;
	pass10: fail10=1;
	success10: ISET(src,oldsrc10); ISET(input,oldinput14);
	if(fail10) goto alt1_8;
BSET(it,CALL(trans_AmethystOptimizercb_32,1,bind));
 BSET(_result_1,BGET(it));  
ISET(cut,Qnil);goto accept1;
alt1_8: ISET(input,oldinput1);if (IGET(cut)!=Qnil) goto fail;
  arg0=CALL(trans_AmethystOptimizercb_33,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt1_9);
 BSET(autovar_19,BGET(it)); VALUE oldinput15=IGET(input);  VALUE oldsrc11=IGET(src); int fail11=0;
ISET(src,BGET(autovar_19)); ISET(input,INT2FIX(0));
   BSET(it,CALL(anything,0 )); FAILTEST(pass11);
 BSET(autovar_20,BGET(it)); BSET(it,CALL(trans_AmethystOptimizercb_34,1,bind));   BSET(it,CALL(args,0 )); FAILTEST(pass11);
 BSET(autovar_21,BGET(it)); BSET(it,CALL(trans_AmethystOptimizercb_35,1,bind)); 
	if (CALL(eof,0)==failobj) goto pass11;
	goto success11;
	pass11: fail11=1;
	success11: ISET(src,oldsrc11); ISET(input,oldinput15);
	if(fail11) goto alt1_9;
BSET(it,CALL(trans_AmethystOptimizercb_36,1,bind));
 BSET(_result_1,BGET(it));  
ISET(cut,Qnil);goto accept1;
alt1_9: ISET(input,oldinput1);if (IGET(cut)!=Qnil) goto fail;
  arg0=CALL(trans_AmethystOptimizercb_37,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt1_10);
 BSET(autovar_22,BGET(it)); VALUE oldinput16=IGET(input);  VALUE oldsrc12=IGET(src); int fail12=0;
ISET(src,BGET(autovar_22)); ISET(input,INT2FIX(0));
 BSET(it,CALL(trans_AmethystOptimizercb_38,1,bind)); 
 BSET(autovar_23,BGET(it)); VALUE oldinput17=IGET(input);  VALUE oldsrc13=IGET(src); int fail13=0;
ISET(src,rb_ary_new3(1,BGET(autovar_23))); ISET(input,INT2FIX(0));
   BSET(it,CALL(arg,0 )); FAILTEST(pass13);
 BSET(name_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass13;
	goto success13;
	pass13: fail13=1;
	success13: ISET(src,oldsrc13); ISET(input,oldinput17);
	if(fail13) goto pass12;
BSET(it,CALL(trans_AmethystOptimizercb_39,1,bind)); 
 BSET(autovar_24,BGET(it)); VALUE oldinput18=IGET(input);  VALUE oldsrc14=IGET(src); int fail14=0;
ISET(src,rb_ary_new3(1,BGET(autovar_24))); ISET(input,INT2FIX(0));
   BSET(it,CALL(trans,0 )); FAILTEST(pass14);
 BSET(expr_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass14;
	goto success14;
	pass14: fail14=1;
	success14: ISET(src,oldsrc14); ISET(input,oldinput18);
	if(fail14) goto pass12;
BSET(it,CALL(trans_AmethystOptimizercb_40,1,bind)); 
 BSET(append_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass12;
	goto success12;
	pass12: fail12=1;
	success12: ISET(src,oldsrc12); ISET(input,oldinput16);
	if(fail12) goto alt1_10;
BSET(it,CALL(trans_AmethystOptimizercb_41,1,bind));
 BSET(_result_1,BGET(it));  
ISET(cut,Qnil);goto accept1;
alt1_10: ISET(input,oldinput1);if (IGET(cut)!=Qnil) goto fail;
  arg0=CALL(trans_AmethystOptimizercb_42,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt1_11);
 BSET(autovar_25,BGET(it)); VALUE oldinput19=IGET(input);  VALUE oldsrc15=IGET(src); int fail15=0;
ISET(src,BGET(autovar_25)); ISET(input,INT2FIX(0));
   BSET(it,CALL(args,0 )); FAILTEST(pass15);
 BSET(ary_1,BGET(it)); BSET(it,CALL(trans_AmethystOptimizercb_43,1,bind)); 
 BSET(pred_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass15;
	goto success15;
	pass15: fail15=1;
	success15: ISET(src,oldsrc15); ISET(input,oldinput19);
	if(fail15) goto alt1_11;
BSET(it,CALL(trans_AmethystOptimizercb_44,1,bind));
 BSET(_result_1,BGET(it));  
ISET(cut,Qnil);goto accept1;
alt1_11: ISET(input,oldinput1);if (IGET(cut)!=Qnil) goto fail;
  arg0=CALL(trans_AmethystOptimizercb_45,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt1_12);
 BSET(autovar_26,BGET(it)); VALUE oldinput20=IGET(input);  VALUE oldsrc16=IGET(src); int fail16=0;
ISET(src,BGET(autovar_26)); ISET(input,INT2FIX(0));
 BSET(it,CALL(trans_AmethystOptimizercb_46,1,bind)); 
 BSET(name_1,BGET(it)); BSET(it,CALL(trans_AmethystOptimizercb_47,1,bind)); 
 BSET(autovar_27,BGET(it)); VALUE oldinput21=IGET(input);  VALUE oldsrc17=IGET(src); int fail17=0;
ISET(src,rb_ary_new3(1,BGET(autovar_27))); ISET(input,INT2FIX(0));
   BSET(it,CALL(args,0 )); FAILTEST(pass17);
 BSET(args_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass17;
	goto success17;
	pass17: fail17=1;
	success17: ISET(src,oldsrc17); ISET(input,oldinput21);
	if(fail17) goto pass16;
BSET(it,CALL(trans_AmethystOptimizercb_48,1,bind)); 
 BSET(autovar_28,BGET(it)); VALUE oldinput22=IGET(input);  VALUE oldsrc18=IGET(src); int fail18=0;
ISET(src,rb_ary_new3(1,BGET(autovar_28))); ISET(input,INT2FIX(0));
   BSET(it,CALL(args,0 )); FAILTEST(pass18);
 BSET(vars_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass18;
	goto success18;
	pass18: fail18=1;
	success18: ISET(src,oldsrc18); ISET(input,oldinput22);
	if(fail18) goto pass16;

	if (CALL(eof,0)==failobj) goto pass16;
	goto success16;
	pass16: fail16=1;
	success16: ISET(src,oldsrc16); ISET(input,oldinput20);
	if(fail16) goto alt1_12;
BSET(it,CALL(trans_AmethystOptimizercb_49,1,bind));
 BSET(_result_1,BGET(it));  
ISET(cut,Qnil);goto accept1;
alt1_12: ISET(input,oldinput1);if (IGET(cut)!=Qnil) goto fail;
  arg0=CALL(trans_AmethystOptimizercb_50,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt1_13);
 BSET(autovar_29,BGET(it)); VALUE oldinput23=IGET(input);  VALUE oldsrc19=IGET(src); int fail19=0;
ISET(src,BGET(autovar_29)); ISET(input,INT2FIX(0));
 BSET(it,CALL(trans_AmethystOptimizercb_51,1,bind)); 
 BSET(autovar_30,BGET(it)); VALUE oldinput24; while(1){oldinput24=IGET(input);   BSET(it,CALL(arg,0 )); FAILTEST(break4);
 BSET(autovar_31,BGET(it)); BSET(it,CALL(trans_AmethystOptimizercb_52,1,bind));  if (IGET(stop)!=Qnil){{oldinput24=IGET(input);goto break4;} } } break4: ISET(stop,Qnil);  ISET(input,oldinput24); BSET(it,BGET(autovar_30));
 BSET(ary_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass19;
	goto success19;
	pass19: fail19=1;
	success19: ISET(src,oldsrc19); ISET(input,oldinput23);
	if(fail19) goto alt1_13;
BSET(it,CALL(trans_AmethystOptimizercb_53,1,bind));
 BSET(_result_1,BGET(it));  
ISET(cut,Qnil);goto accept1;
alt1_13: ISET(input,oldinput1);if (IGET(cut)!=Qnil) goto fail;
  arg0=CALL(trans_AmethystOptimizercb_54,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt1_14);
 BSET(autovar_32,BGET(it)); VALUE oldinput25=IGET(input);  VALUE oldsrc20=IGET(src); int fail20=0;
ISET(src,BGET(autovar_32)); ISET(input,INT2FIX(0));
 BSET(it,CALL(trans_AmethystOptimizercb_55,1,bind)); 
 BSET(autovar_33,BGET(it)); VALUE oldinput26=IGET(input);  VALUE oldsrc21=IGET(src); int fail21=0;
ISET(src,rb_ary_new3(1,BGET(autovar_33))); ISET(input,INT2FIX(0));
   BSET(it,CALL(trans,0 )); FAILTEST(pass21);
 BSET(to_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass21;
	goto success21;
	pass21: fail21=1;
	success21: ISET(src,oldsrc21); ISET(input,oldinput26);
	if(fail21) goto pass20;
BSET(it,CALL(trans_AmethystOptimizercb_56,1,bind)); 
 BSET(autovar_34,BGET(it)); VALUE oldinput27=IGET(input);  VALUE oldsrc22=IGET(src); int fail22=0;
ISET(src,rb_ary_new3(1,BGET(autovar_34))); ISET(input,INT2FIX(0));
   BSET(it,CALL(arg,0 )); FAILTEST(pass22);
 BSET(var_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass22;
	goto success22;
	pass22: fail22=1;
	success22: ISET(src,oldsrc22); ISET(input,oldinput27);
	if(fail22) goto pass20;
BSET(it,CALL(trans_AmethystOptimizercb_57,1,bind)); 
 BSET(enter_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass20;
	goto success20;
	pass20: fail20=1;
	success20: ISET(src,oldsrc20); ISET(input,oldinput25);
	if(fail20) goto alt1_14;
BSET(it,CALL(trans_AmethystOptimizercb_58,1,bind));
 BSET(_result_1,BGET(it));  
ISET(cut,Qnil);goto accept1;
alt1_14: ISET(input,oldinput1);if (IGET(cut)!=Qnil) goto fail;
  arg0=CALL(trans_AmethystOptimizercb_59,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt1_15);
 BSET(autovar_35,BGET(it)); VALUE oldinput28=IGET(input);  VALUE oldsrc23=IGET(src); int fail23=0;
ISET(src,BGET(autovar_35)); ISET(input,INT2FIX(0));
 
	if (CALL(eof,0)==failobj) goto pass23;
	goto success23;
	pass23: fail23=1;
	success23: ISET(src,oldsrc23); ISET(input,oldinput28);
	if(fail23) goto alt1_15;
BSET(it,CALL(trans_AmethystOptimizercb_60,1,bind));
 BSET(_result_1,BGET(it));  
ISET(cut,Qnil);goto accept1;
alt1_15: ISET(input,oldinput1);if (IGET(cut)!=Qnil) goto fail;
  arg0=CALL(trans_AmethystOptimizercb_61,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt1_16);
 BSET(autovar_36,BGET(it)); VALUE oldinput29=IGET(input);  VALUE oldsrc24=IGET(src); int fail24=0;
ISET(src,BGET(autovar_36)); ISET(input,INT2FIX(0));
 
	if (CALL(eof,0)==failobj) goto pass24;
	goto success24;
	pass24: fail24=1;
	success24: ISET(src,oldsrc24); ISET(input,oldinput29);
	if(fail24) goto alt1_16;
BSET(it,CALL(trans_AmethystOptimizercb_62,1,bind));
 BSET(_result_1,BGET(it));  
ISET(cut,Qnil);goto accept1;
alt1_16: ISET(input,oldinput1);if (IGET(cut)!=Qnil) goto fail;
  arg0=CALL(trans_AmethystOptimizercb_63,1,bind); BSET(it,CALL(clas,1 ,arg0)); FAILTEST(alt1_17);
 BSET(autovar_37,BGET(it)); VALUE oldinput30=IGET(input);  VALUE oldsrc25=IGET(src); int fail25=0;
ISET(src,BGET(autovar_37)); ISET(input,INT2FIX(0));
 VALUE oldinput31; while(1){oldinput31=IGET(input);   BSET(it,CALL(anything,0 )); FAILTEST(break5); if (IGET(stop)!=Qnil){{oldinput31=IGET(input);goto break5;} } } break5: ISET(stop,Qnil);  ISET(input,oldinput31); BSET(it,CALL(trans_AmethystOptimizercb_64,1,bind)); 
 BSET(_result_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass25;
	goto success25;
	pass25: fail25=1;
	success25: ISET(src,oldsrc25); ISET(input,oldinput30);
	if(fail25) goto alt1_17;
 
ISET(cut,Qnil);goto accept1;
  alt1_17:  ISET(input,oldinput1); goto fail;
 accept1:;
BSET(it,BGET(_result_1));
return BGET(it);
fail: return failobj; }
VALUE AmethystOptimizer_transfn(VALUE self ){VALUE vals[0]; VALUE bind=rb_hash_new();  int x;VALUE arg0,arg1,arg2,arg3;
  BSET(it,CALL(trans,0 )); FAILTEST(fail);
 BSET(_result_1,BGET(it)); BSET(it,BGET(_result_1));
return BGET(it);
fail: return failobj; }
VALUE AmethystOptimizer_transs(VALUE self ){VALUE vals[0]; VALUE bind=rb_hash_new();  int x;VALUE arg0,arg1,arg2,arg3;
  BSET(it,CALL(anything,0 )); FAILTEST(fail);
 BSET(autovar_1,BGET(it)); VALUE oldinput1=IGET(input);  VALUE oldsrc1=IGET(src); int fail1=0;
ISET(src,BGET(autovar_1)); ISET(input,INT2FIX(0));
 BSET(it,CALL(transs_AmethystOptimizercb_1,1,bind)); 
 BSET(autovar_2,BGET(it)); VALUE oldinput2; while(1){oldinput2=IGET(input);   BSET(it,CALL(trans,0 )); FAILTEST(break1);
 BSET(autovar_3,BGET(it)); BSET(it,CALL(transs_AmethystOptimizercb_2,1,bind));  if (IGET(stop)!=Qnil){{oldinput2=IGET(input);goto break1;} } } break1: ISET(stop,Qnil);  ISET(input,oldinput2); BSET(it,BGET(autovar_2));
 BSET(t_1,BGET(it)); 
	if (CALL(eof,0)==failobj) goto pass1;
	goto success1;
	pass1: fail1=1;
	success1: ISET(src,oldsrc1); ISET(input,oldinput1);
	if(fail1) goto fail;
BSET(it,BGET(t_1));
 BSET(_result_1,BGET(it)); BSET(it,BGET(_result_1));
return BGET(it);
fail: return failobj; }
void Init_optimizer_null_c(){ 
 cls_AmethystOptimizer=rb_define_class("AmethystOptimizer",rb_const_get(rb_cObject,rb_intern("Amethyst"))); 
failobj=rb_eval_string("FAIL");
rb_define_method(cls_AmethystOptimizer,"arg",AmethystOptimizer_arg,0);
rb_define_method(cls_AmethystOptimizer,"args",AmethystOptimizer_args,0);
rb_define_method(cls_AmethystOptimizer,"itrans",AmethystOptimizer_itrans,0);
rb_define_method(cls_AmethystOptimizer,"trans",AmethystOptimizer_trans,0);
rb_define_method(cls_AmethystOptimizer,"transfn",AmethystOptimizer_transfn,0);
rb_define_method(cls_AmethystOptimizer,"transs",AmethystOptimizer_transs,0);
 }
